[toolchain]
moc = "1.14.0"

[moc]
args = ["--default-persistent-actors"]

[dependencies]
core = "2.6.1"

[canisters.mini_league_domain]
main = "src/main.mo"
candid = "mini_league_domain.did"

[canisters.mini_league_domain.migrations]
chain = "src/backend/migrations"
check-limit = 1
