/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChildClubPoints {
  'updated_at_ms' : bigint,
  'child_id' : string,
  'club_id' : string,
  'points' : number,
}
export interface ClubPointsSettings {
  'updated_at_ms' : bigint,
  'display_name' : [] | [string],
  'disabled' : boolean,
  'club_id' : string,
}
export interface ClubReward {
  'id' : string,
  'points_required' : number,
  'name' : string,
  'qr_code_url' : [] | [string],
  'team_id' : [] | [string],
  'description' : [] | [string],
  'updated_at_ms' : bigint,
  'show_qr_code' : boolean,
  'is_default' : boolean,
  'reward_type' : string,
  'created_at_ms' : bigint,
  'logo_url' : [] | [string],
  'sponsor_id' : [] | [string],
  'is_active' : boolean,
  'club_id' : string,
}
export interface HistoryPage {
  'total' : bigint,
  'items' : Array<PointsHistoryEntry>,
}
export interface LeaderboardEntry { 'subject_id' : string, 'points' : number }
export interface Main {
  'addBulkAccessPrincipal' : ActorMethod<
    [Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'approve_redemption' : ActorMethod<
    [string],
    { 'Ok' : RewardRedemption } |
      { 'Err' : string }
  >,
  'award_points' : ActorMethod<
    [
      string,
      Subject,
      string,
      string,
      number,
      string,
      [] | [string],
      [] | [string],
      [] | [number],
    ],
    { 'Ok' : PointsHistoryEntry } |
      { 'Err' : string }
  >,
  'award_points_once' : ActorMethod<
    [
      string,
      Subject,
      string,
      string,
      number,
      string,
      [] | [string],
      [] | [string],
    ],
    { 'Ok' : PointsHistoryEntry } |
      { 'Err' : string }
  >,
  'cancel_redemption' : ActorMethod<
    [string],
    { 'Ok' : RewardRedemption } |
      { 'Err' : string }
  >,
  'create_reward' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      number,
      boolean,
      string,
      [] | [string],
      boolean,
      [] | [string],
      [] | [string],
    ],
    { 'Ok' : ClubReward } |
      { 'Err' : string }
  >,
  /**
   * / Public: remaining cycles (shown in admin settings).
   */
  'cycles_balance' : ActorMethod<[], bigint>,
  'delete_reward' : ActorMethod<[string], { 'Ok' : null } | { 'Err' : string }>,
  'export_state' : ActorMethod<
    [],
    {
        'Ok' : {
          'userClubPoints' : Array<UserClubPoints>,
          'schema' : number,
          'cooldowns' : Array<PointsCooldown>,
          'governor' : Principal,
          'clubRewards' : Array<ClubReward>,
          'redemptions' : Array<RewardRedemption>,
          'roles' : Array<RoleGrant>,
          'childClubPoints' : Array<ChildClubPoints>,
          'pointsHistory' : Array<PointsHistoryEntry>,
        }
      } |
      { 'Err' : string }
  >,
  'fulfill_redemption' : ActorMethod<
    [string],
    { 'Ok' : RewardRedemption } |
      { 'Err' : string }
  >,
  'get_child_points' : ActorMethod<
    [string, string],
    { 'Ok' : number } |
      { 'Err' : string }
  >,
  'get_child_points_all_clubs' : ActorMethod<
    [string],
    { 'Ok' : Array<[string, number]> } |
      { 'Err' : string }
  >,
  'get_child_points_batch' : ActorMethod<
    [string, Array<string>],
    { 'Ok' : Array<[string, number]> } |
      { 'Err' : string }
  >,
  'get_club_points_settings' : ActorMethod<
    [string],
    { 'Ok' : [] | [ClubPointsSettings] } |
      { 'Err' : string }
  >,
  'get_engagement_streak' : ActorMethod<
    [string, string],
    { 'Ok' : number } |
      { 'Err' : string }
  >,
  'get_leaderboard' : ActorMethod<
    [string, { 'User' : null } | { 'Child' : null }, string, bigint],
    { 'Ok' : Array<LeaderboardEntry> } |
      { 'Err' : string }
  >,
  'get_user_points' : ActorMethod<
    [string, string],
    { 'Ok' : number } |
      { 'Err' : string }
  >,
  'get_user_points_all_clubs' : ActorMethod<
    [string],
    { 'Ok' : Array<[string, number]> } |
      { 'Err' : string }
  >,
  'grant_role' : ActorMethod<
    [Principal, string, string, [] | [string]],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'listBulkAccessPrincipals' : ActorMethod<
    [],
    { 'Ok' : Array<Principal> } |
      { 'Err' : string }
  >,
  'list_points_history' : ActorMethod<
    [string, [] | [Subject], bigint, bigint],
    { 'Ok' : HistoryPage } |
      { 'Err' : string }
  >,
  'list_redemptions' : ActorMethod<
    [string, [] | [Subject]],
    { 'Ok' : Array<RewardRedemption> } |
      { 'Err' : string }
  >,
  'list_rewards' : ActorMethod<
    [string, [] | [string], boolean],
    { 'Ok' : Array<ClubReward> } |
      { 'Err' : string }
  >,
  'redeem_reward' : ActorMethod<
    [string, Subject, string, [] | [string]],
    { 'Ok' : RewardRedemption } |
      { 'Err' : string }
  >,
  'removeBulkAccessPrincipal' : ActorMethod<
    [Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'save_club_points_settings' : ActorMethod<
    [string, [] | [string], boolean],
    { 'Ok' : ClubPointsSettings } |
      { 'Err' : string }
  >,
  'transfer_governorship' : ActorMethod<
    [Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'update_reward' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      number,
      boolean,
      boolean,
      string,
      [] | [string],
      [] | [string],
      boolean,
      [] | [string],
      [] | [string],
    ],
    { 'Ok' : ClubReward } |
      { 'Err' : string }
  >,
}
export interface PointsCooldown {
  'id' : string,
  'action_type' : string,
  'awarded_date' : string,
  'points_awarded' : number,
  'user_id' : string,
  'created_at_ms' : bigint,
  'club_id' : string,
  'scope_id' : string,
}
export interface PointsHistoryEntry {
  'id' : string,
  'balance_after' : number,
  'season_id' : [] | [string],
  'description' : string,
  'source_id' : [] | [string],
  'created_by' : [] | [Principal],
  'user_id' : [] | [string],
  'child_id' : [] | [string],
  'created_at_ms' : bigint,
  'source_type' : string,
  'amount' : number,
  'club_id' : string,
}
export interface RewardRedemption {
  'id' : string,
  'status' : string,
  'points_spent' : number,
  'redeemed_at_ms' : [] | [bigint],
  'user_id' : [] | [string],
  'child_id' : [] | [string],
  'verified_at_ms' : [] | [bigint],
  'created_at_ms' : bigint,
  'reward_id' : string,
  'verified_by' : [] | [Principal],
  'club_id' : string,
  'idempotency_key' : [] | [string],
}
export interface RoleGrant {
  'role' : string,
  'user' : Principal,
  'team_id' : [] | [string],
  'club_id' : string,
}
export type Subject = { 'User' : string } |
  { 'Child' : string };
export interface UserClubPoints {
  'updated_at_ms' : bigint,
  'user_id' : string,
  'club_id' : string,
  'points' : number,
}
export interface _SERVICE extends Main {}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];