/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'headers' : IDL.Vec(HeaderField),
    'body' : IDL.Vec(IDL.Nat8),
  });
  const HttpResponse = IDL.Record({
    'status_code' : IDL.Nat16,
    'headers' : IDL.Vec(HeaderField),
    'body' : IDL.Vec(IDL.Nat8),
  });
  const FinalizedBlob = IDL.Record({
    'path' : IDL.Text,
    'content_hash' : IDL.Text,
    'content_length' : IDL.Nat64,
  });
  const Health = IDL.Record({
    'version' : IDL.Text,
    'blob_count' : IDL.Nat64,
    'total_bytes' : IDL.Nat64,
  });
  const Result = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const ResultUploadId = IDL.Variant({ 'Ok' : IDL.Text, 'Err' : IDL.Text });
  const ResultFinalized = IDL.Variant({ 'Ok' : FinalizedBlob, 'Err' : IDL.Text });

  return IDL.Service({
    'begin_upload' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat64, IDL.Nat32],
        [ResultUploadId],
        [],
      ),
    'put_chunk' : IDL.Func(
        [IDL.Text, IDL.Nat32, IDL.Vec(IDL.Nat8)],
        [Result],
        [],
      ),
    'finalize_upload' : IDL.Func([IDL.Text], [ResultFinalized], []),
    'abort_upload' : IDL.Func([IDL.Text], [Result], []),
    'get_content_hash' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'delete_blob' : IDL.Func([IDL.Text], [Result], []),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'health' : IDL.Func([], [Health], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
