[toolchain]
moc = "1.14.0"

[moc]
args = [ "--default-persistent-actors" ]

[canisters.pii_access_control]
main = "src/main.mo"
candid = "pii_access_control.did"

[canisters.pii_access_control.migrations]
chain = "src/backend/migrations"
check-limit = 1

[dependencies]
core = "2.6.1"
ic-vetkeys = "0.6.0"
