/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/insights_domain.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface MainInterface {
    ad_event_summary(since_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<AdEventSummary>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    append_audit_log(action_type: string, table_name: string, target_user_id: string | null, target_user_name: string | null, details: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    client_perf_aggregate(path: string, metric: string | null, since_ms: bigint, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: ClientPerfAggregate;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    club_engagement_active_users(club_id: string, since_ms: bigint, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<EngagementDayPoint>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    club_engagement_benchmarks(club_id: string, since_ms: bigint, until_ms: bigint, prev_since_ms: bigint, prev_until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: EngagementBenchmarks;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    club_engagement_message_volume(club_id: string, since_ms: bigint, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<EngagementDayPoint>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    club_engagement_rsvp_completion_series(club_id: string, since_ms: bigint, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<EngagementDayPoint>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    club_engagement_sponsor_performance(club_id: string, since_ms: bigint, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: {
            clicks: Array<EngagementDayPoint>;
            impressions: Array<EngagementDayPoint>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    club_engagement_total_unique_reach(club_id: string, since_ms: bigint, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    club_engagement_totals(club_id: string, since_ms: bigint, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: EngagementTotals;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    count_photos(club_id: string, since_ms: bigint, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: bigint;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_ad(input: AppAdInput): Promise<{
        __kind__: "Ok";
        Ok: AppAd;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_admin_alert(alert_type: string, details: string): Promise<{
        __kind__: "Ok";
        Ok: AdminAlert;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    delete_ad(id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_ad_setting(location: string): Promise<AppAdSetting | null>;
    get_benchmarks(metric_keys: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: Array<Benchmark>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_sponsor_benchmarks(sponsor_ids: Array<string>, since_period: string, until_period: string): Promise<{
        __kind__: "Ok";
        Ok: Array<SponsorBenchmarkRow>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_sponsor_performance(sponsor_id: string, period: string): Promise<{
        __kind__: "Ok";
        Ok: SponsorPerformance;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    grant_role(principal: Principal, role: string, club_id: string, team_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    is_app_admin(): Promise<boolean>;
    list_active_ads(): Promise<Array<AppAd>>;
    list_ad_settings(): Promise<{
        __kind__: "Ok";
        Ok: Array<AppAdSetting>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_admin_alerts(status: AlertStatus | null): Promise<{
        __kind__: "Ok";
        Ok: Array<AdminAlert>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_ads(): Promise<{
        __kind__: "Ok";
        Ok: Array<AppAd>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_audit_logs(actor_filter: Principal | null, action_type: string | null, table_name: string | null, offset: number, limit: number): Promise<{
        __kind__: "Ok";
        Ok: {
            total: number;
            items: Array<AuditLog>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_feedback(status: FeedbackStatus | null, offset: number, limit: number): Promise<{
        __kind__: "Ok";
        Ok: {
            total: number;
            items: Array<Feedback>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_user_activity(club_id: string | null, since_ms: bigint, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<UserActivityEntry>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    my_feedback(): Promise<Array<Feedback>>;
    perf_aggregate(surface: string, source: string | null, since_ms: bigint, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: PerfAggregate;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    photo_engagement_totals(photo_ids: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: Array<PhotoEngagementTotal>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_active_user(club_id: string, account_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_ad_event(ad_id: string, event_type: string, context: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_client_perf(entries: Array<ClientPerfEntry>): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_message_sent(club_id: string, account_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_perf_sample(surface: string, source: string, duration_ms: number, cache_hit: boolean, platform: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_perf_samples_batch(samples: Array<PerfSampleInput>): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_photo_engagement(photo_id: string, kind: PhotoEngagementKind): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_photo_upload(club_id: string, photo_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_rsvp_completed(club_id: string, account_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_sponsor_click(club_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_sponsor_impression(club_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_sponsor_metric(sponsor_id: string, metric: string, delta: number, account_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_user_activity(user_id: string, club_id: string | null, page_path: string, page_label: string, session_id: string, duration_seconds: number): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_web_vital(metric_name: string, metric_value: number, rating: string, page_path: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    resolve_admin_alert(id: string): Promise<{
        __kind__: "Ok";
        Ok: AdminAlert;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_ad_active(id: string, is_active: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_benchmark(metric_key: string, period: string, value: number, total_members: number | null, dau: number | null, wau: number | null, mau: number | null, posters: number | null, read_rate: number | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    submit_feedback(kind: string, title: string | null, message: string, page_url: string | null): Promise<{
        __kind__: "Ok";
        Ok: Feedback;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    transfer_governorship(new_governor: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    update_ad(id: string, input: AppAdInput): Promise<{
        __kind__: "Ok";
        Ok: AppAd;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    update_feedback_status(id: string, status: FeedbackStatus, admin_notes: string | null): Promise<{
        __kind__: "Ok";
        Ok: Feedback;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    upsert_ad_setting(location: string, is_enabled: boolean, override_sponsors: boolean, show_only_when_no_sponsors: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
}
export interface PerfSampleInput {
    source: string;
    cache_hit: boolean;
    surface: string;
    platform: string;
    duration_ms: number;
}
export interface Benchmark {
    dau?: number;
    mau?: number;
    wau?: number;
    posters?: number;
    value: number;
    period: string;
    read_rate?: number;
    updated_at_ms: bigint;
    total_members?: number;
    metric_key: string;
}
export interface AuditLog {
    id: string;
    target_user_name?: string;
    action_type: string;
    actor_id: Principal;
    created_at_ms: bigint;
    details: string;
    table_name: string;
    target_user_id?: string;
}
export interface AppAdSetting {
    is_enabled: boolean;
    updated_at_ms: bigint;
    override_sponsors: boolean;
    show_only_when_no_sponsors: boolean;
    location: string;
}
export interface AdminAlert {
    id: string;
    status: AlertStatus;
    alert_type: string;
    created_at_ms: bigint;
    details: string;
    resolved_at_ms?: bigint;
    resolved_by?: Principal;
}
export interface SponsorBenchmarkRow {
    ctr: number;
    clicks: number;
    impressions: number;
    sponsor_id: string;
    unique_reach: number;
}
export interface PhotoEngagementTotal {
    views: bigint;
    photo_id: string;
    comments: bigint;
    reactions: bigint;
}
export interface Feedback {
    id: string;
    status: FeedbackStatus;
    title?: string;
    kind: string;
    user: Principal;
    page_url?: string;
    updated_at_ms: bigint;
    created_at_ms: bigint;
    message: string;
    admin_notes?: string;
}
export interface EngagementBenchmarks {
    previous: EngagementTotals;
    current: EngagementTotals;
    club_id: string;
}
export interface PerfAggregate {
    source: string;
    count: number;
    surface: string;
    p50_ms: number;
    p95_ms: number;
    avg_ms: number;
}
export interface ClientPerfAggregate {
    path: string;
    count: number;
    p50_ms: number;
    p95_ms: number;
    avg_ms: number;
}
export interface AppAdInput {
    link_url?: string;
    subtext?: string;
    image_url?: string;
    text_color?: string;
    headline?: string;
    name: string;
    description?: string;
    logo_url?: string;
    cta_label?: string;
    ad_type: string;
    bg_color?: string;
}
export interface EngagementDayPoint {
    day: string;
    value: number;
}
export interface AdEventSummary {
    clicks: number;
    context: string;
    ad_id: string;
    views: number;
}
export interface EngagementTotals {
    messages: number;
    sponsor_clicks: number;
    active_users: number;
    sponsor_impressions: number;
    club_id: string;
    rsvps: number;
}
export interface ClientPerfEntry {
    metric: string;
    principal: Principal;
    at_ms: bigint;
    path: string;
    value_ms: number;
}
export interface AppAd {
    id: string;
    link_url?: string;
    subtext?: string;
    image_url?: string;
    text_color?: string;
    headline?: string;
    name: string;
    description?: string;
    updated_at_ms: bigint;
    created_at_ms: bigint;
    logo_url?: string;
    cta_label?: string;
    is_active: boolean;
    ad_type: string;
    display_order: number;
    bg_color?: string;
}
export interface UserActivityEntry {
    page_path: string;
    started_at_ms: bigint;
    session_id: string;
    duration_seconds: number;
    user_id: string;
    club_id?: string;
    page_label: string;
}
export interface SponsorPerformance {
    metrics: Array<{
        metric: string;
        value: number;
    }>;
    period: string;
    sponsor_id: string;
}
export enum AlertStatus {
    Open = "Open",
    Resolved = "Resolved"
}
export enum FeedbackStatus {
    Open = "Open",
    InProgress = "InProgress",
    Resolved = "Resolved"
}
export enum PhotoEngagementKind {
    View = "View",
    Comment = "Comment",
    Reaction = "Reaction"
}
export interface insights_domainInterface extends MainInterface {
}
import type { AdEventSummary as _AdEventSummary, AdminAlert as _AdminAlert, AlertStatus as _AlertStatus, AppAd as _AppAd, AppAdInput as _AppAdInput, AppAdSetting as _AppAdSetting, AuditLog as _AuditLog, Benchmark as _Benchmark, ClientPerfAggregate as _ClientPerfAggregate, EngagementBenchmarks as _EngagementBenchmarks, EngagementDayPoint as _EngagementDayPoint, EngagementTotals as _EngagementTotals, Feedback as _Feedback, FeedbackStatus as _FeedbackStatus, PerfAggregate as _PerfAggregate, PhotoEngagementKind as _PhotoEngagementKind, PhotoEngagementTotal as _PhotoEngagementTotal, SponsorBenchmarkRow as _SponsorBenchmarkRow, SponsorPerformance as _SponsorPerformance, UserActivityEntry as _UserActivityEntry } from "./declarations/insights_domain.did";
export class Insights_domain implements insights_domainInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async ad_event_summary(arg0: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<AdEventSummary>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.ad_event_summary(arg0);
        return from_candid_variant_n1(result);
    }
    async append_audit_log(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.append_audit_log(arg0, arg1, to_candid_opt_n2(arg2), to_candid_opt_n2(arg3), arg4);
        return from_candid_variant_n3(result);
    }
    async client_perf_aggregate(arg0: string, arg1: string | null, arg2: bigint, arg3: bigint): Promise<{
        __kind__: "Ok";
        Ok: ClientPerfAggregate;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.client_perf_aggregate(arg0, to_candid_opt_n2(arg1), arg2, arg3);
        return from_candid_variant_n4(result);
    }
    async club_engagement_active_users(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<EngagementDayPoint>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.club_engagement_active_users(arg0, arg1, arg2);
        return from_candid_variant_n5(result);
    }
    async club_engagement_benchmarks(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<{
        __kind__: "Ok";
        Ok: EngagementBenchmarks;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.club_engagement_benchmarks(arg0, arg1, arg2, arg3, arg4);
        return from_candid_variant_n6(result);
    }
    async club_engagement_message_volume(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<EngagementDayPoint>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.club_engagement_message_volume(arg0, arg1, arg2);
        return from_candid_variant_n5(result);
    }
    async club_engagement_rsvp_completion_series(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<EngagementDayPoint>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.club_engagement_rsvp_completion_series(arg0, arg1, arg2);
        return from_candid_variant_n5(result);
    }
    async club_engagement_sponsor_performance(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: {
            clicks: Array<EngagementDayPoint>;
            impressions: Array<EngagementDayPoint>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.club_engagement_sponsor_performance(arg0, arg1, arg2);
        return from_candid_variant_n7(result);
    }
    async club_engagement_total_unique_reach(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.club_engagement_total_unique_reach(arg0, arg1, arg2);
        return from_candid_variant_n8(result);
    }
    async club_engagement_totals(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: EngagementTotals;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.club_engagement_totals(arg0, arg1, arg2);
        return from_candid_variant_n9(result);
    }
    async count_photos(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: bigint;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.count_photos(arg0, arg1, arg2);
        return from_candid_variant_n10(result);
    }
    async create_ad(arg0: AppAdInput): Promise<{
        __kind__: "Ok";
        Ok: AppAd;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_ad(to_candid_AppAdInput_n11(arg0));
        return from_candid_variant_n13(result);
    }
    async create_admin_alert(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: AdminAlert;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_admin_alert(arg0, arg1);
        return from_candid_variant_n17(result);
    }
    async delete_ad(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_ad(arg0);
        return from_candid_variant_n3(result);
    }
    async get_ad_setting(arg0: string): Promise<AppAdSetting | null> {
        const result = await this.actor.get_ad_setting(arg0);
        return from_candid_opt_n24(result);
    }
    async get_benchmarks(arg0: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: Array<Benchmark>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_benchmarks(arg0);
        return from_candid_variant_n25(result);
    }
    async get_sponsor_benchmarks(arg0: Array<string>, arg1: string, arg2: string): Promise<{
        __kind__: "Ok";
        Ok: Array<SponsorBenchmarkRow>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_sponsor_benchmarks(arg0, arg1, arg2);
        return from_candid_variant_n31(result);
    }
    async get_sponsor_performance(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: SponsorPerformance;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_sponsor_performance(arg0, arg1);
        return from_candid_variant_n32(result);
    }
    async grant_role(arg0: Principal, arg1: string, arg2: string, arg3: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.grant_role(arg0, arg1, arg2, to_candid_opt_n2(arg3));
        return from_candid_variant_n3(result);
    }
    async is_app_admin(): Promise<boolean> {
        const result = await this.actor.is_app_admin();
        return result;
    }
    async list_active_ads(): Promise<Array<AppAd>> {
        const result = await this.actor.list_active_ads();
        return from_candid_vec_n33(result);
    }
    async list_ad_settings(): Promise<{
        __kind__: "Ok";
        Ok: Array<AppAdSetting>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_ad_settings();
        return from_candid_variant_n34(result);
    }
    async list_admin_alerts(arg0: AlertStatus | null): Promise<{
        __kind__: "Ok";
        Ok: Array<AdminAlert>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_admin_alerts(to_candid_opt_n35(arg0));
        return from_candid_variant_n38(result);
    }
    async list_ads(): Promise<{
        __kind__: "Ok";
        Ok: Array<AppAd>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_ads();
        return from_candid_variant_n40(result);
    }
    async list_audit_logs(arg0: Principal | null, arg1: string | null, arg2: string | null, arg3: number, arg4: number): Promise<{
        __kind__: "Ok";
        Ok: {
            total: number;
            items: Array<AuditLog>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_audit_logs(to_candid_opt_n41(arg0), to_candid_opt_n2(arg1), to_candid_opt_n2(arg2), arg3, arg4);
        return from_candid_variant_n42(result);
    }
    async list_feedback(arg0: FeedbackStatus | null, arg1: number, arg2: number): Promise<{
        __kind__: "Ok";
        Ok: {
            total: number;
            items: Array<Feedback>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_feedback(to_candid_opt_n47(arg0), arg1, arg2);
        return from_candid_variant_n50(result);
    }
    async list_user_activity(arg0: string | null, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<UserActivityEntry>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_user_activity(to_candid_opt_n2(arg0), arg1, arg2);
        return from_candid_variant_n57(result);
    }
    async my_feedback(): Promise<Array<Feedback>> {
        const result = await this.actor.my_feedback();
        return from_candid_vec_n52(result);
    }
    async perf_aggregate(arg0: string, arg1: string | null, arg2: bigint, arg3: bigint): Promise<{
        __kind__: "Ok";
        Ok: PerfAggregate;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.perf_aggregate(arg0, to_candid_opt_n2(arg1), arg2, arg3);
        return from_candid_variant_n61(result);
    }
    async photo_engagement_totals(arg0: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: Array<PhotoEngagementTotal>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.photo_engagement_totals(arg0);
        return from_candid_variant_n62(result);
    }
    async record_active_user(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_active_user(arg0, arg1);
        return from_candid_variant_n3(result);
    }
    async record_ad_event(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_ad_event(arg0, arg1, arg2);
        return from_candid_variant_n3(result);
    }
    async record_client_perf(arg0: Array<ClientPerfEntry>): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_client_perf(arg0);
        return from_candid_variant_n8(result);
    }
    async record_message_sent(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_message_sent(arg0, arg1);
        return from_candid_variant_n3(result);
    }
    async record_perf_sample(arg0: string, arg1: string, arg2: number, arg3: boolean, arg4: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_perf_sample(arg0, arg1, arg2, arg3, arg4);
        return from_candid_variant_n3(result);
    }
    async record_perf_samples_batch(arg0: Array<PerfSampleInput>): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_perf_samples_batch(arg0);
        return from_candid_variant_n8(result);
    }
    async record_photo_engagement(arg0: string, arg1: PhotoEngagementKind): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_photo_engagement(arg0, to_candid_PhotoEngagementKind_n63(arg1));
        return from_candid_variant_n3(result);
    }
    async record_photo_upload(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_photo_upload(arg0, arg1);
        return from_candid_variant_n3(result);
    }
    async record_rsvp_completed(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_rsvp_completed(arg0, arg1);
        return from_candid_variant_n3(result);
    }
    async record_sponsor_click(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_sponsor_click(arg0);
        return from_candid_variant_n3(result);
    }
    async record_sponsor_impression(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_sponsor_impression(arg0);
        return from_candid_variant_n3(result);
    }
    async record_sponsor_metric(arg0: string, arg1: string, arg2: number, arg3: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_sponsor_metric(arg0, arg1, arg2, to_candid_opt_n2(arg3));
        return from_candid_variant_n3(result);
    }
    async record_user_activity(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: string, arg5: number): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_user_activity(arg0, to_candid_opt_n2(arg1), arg2, arg3, arg4, arg5);
        return from_candid_variant_n3(result);
    }
    async record_web_vital(arg0: string, arg1: number, arg2: string, arg3: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_web_vital(arg0, arg1, arg2, arg3);
        return from_candid_variant_n3(result);
    }
    async resolve_admin_alert(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: AdminAlert;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.resolve_admin_alert(arg0);
        return from_candid_variant_n17(result);
    }
    async set_ad_active(arg0: string, arg1: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_ad_active(arg0, arg1);
        return from_candid_variant_n3(result);
    }
    async set_benchmark(arg0: string, arg1: string, arg2: number, arg3: number | null, arg4: number | null, arg5: number | null, arg6: number | null, arg7: number | null, arg8: number | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_benchmark(arg0, arg1, arg2, to_candid_opt_n65(arg3), to_candid_opt_n65(arg4), to_candid_opt_n65(arg5), to_candid_opt_n65(arg6), to_candid_opt_n65(arg7), to_candid_opt_n66(arg8));
        return from_candid_variant_n3(result);
    }
    async submit_feedback(arg0: string, arg1: string | null, arg2: string, arg3: string | null): Promise<{
        __kind__: "Ok";
        Ok: Feedback;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.submit_feedback(arg0, to_candid_opt_n2(arg1), arg2, to_candid_opt_n2(arg3));
        return from_candid_variant_n67(result);
    }
    async transfer_governorship(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.transfer_governorship(arg0);
        return from_candid_variant_n3(result);
    }
    async update_ad(arg0: string, arg1: AppAdInput): Promise<{
        __kind__: "Ok";
        Ok: AppAd;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.update_ad(arg0, to_candid_AppAdInput_n11(arg1));
        return from_candid_variant_n13(result);
    }
    async update_feedback_status(arg0: string, arg1: FeedbackStatus, arg2: string | null): Promise<{
        __kind__: "Ok";
        Ok: Feedback;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.update_feedback_status(arg0, to_candid_FeedbackStatus_n48(arg1), to_candid_opt_n2(arg2));
        return from_candid_variant_n67(result);
    }
    async upsert_ad_setting(arg0: string, arg1: boolean, arg2: boolean, arg3: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.upsert_ad_setting(arg0, arg1, arg2, arg3);
        return from_candid_variant_n3(result);
    }
}
function from_candid_AdminAlert_n18(value: _AdminAlert): AdminAlert {
    return from_candid_record_n19(value);
}
function from_candid_AlertStatus_n20(value: _AlertStatus): AlertStatus {
    return from_candid_variant_n21(value);
}
function from_candid_AppAd_n14(value: _AppAd): AppAd {
    return from_candid_record_n15(value);
}
function from_candid_AuditLog_n45(value: _AuditLog): AuditLog {
    return from_candid_record_n46(value);
}
function from_candid_Benchmark_n27(value: _Benchmark): Benchmark {
    return from_candid_record_n28(value);
}
function from_candid_FeedbackStatus_n55(value: _FeedbackStatus): FeedbackStatus {
    return from_candid_variant_n56(value);
}
function from_candid_Feedback_n53(value: _Feedback): Feedback {
    return from_candid_record_n54(value);
}
function from_candid_UserActivityEntry_n59(value: _UserActivityEntry): UserActivityEntry {
    return from_candid_record_n60(value);
}
function from_candid_opt_n16(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(value: [] | [_AppAdSetting]): AppAdSetting | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(value: {
    id: string;
    link_url: [] | [string];
    subtext: [] | [string];
    image_url: [] | [string];
    text_color: [] | [string];
    headline: [] | [string];
    name: string;
    description: [] | [string];
    updated_at_ms: bigint;
    created_at_ms: bigint;
    logo_url: [] | [string];
    cta_label: [] | [string];
    is_active: boolean;
    ad_type: string;
    display_order: number;
    bg_color: [] | [string];
}): {
    id: string;
    link_url?: string;
    subtext?: string;
    image_url?: string;
    text_color?: string;
    headline?: string;
    name: string;
    description?: string;
    updated_at_ms: bigint;
    created_at_ms: bigint;
    logo_url?: string;
    cta_label?: string;
    is_active: boolean;
    ad_type: string;
    display_order: number;
    bg_color?: string;
} {
    return {
        id: value.id,
        link_url: record_opt_to_undefined(from_candid_opt_n16(value.link_url)),
        subtext: record_opt_to_undefined(from_candid_opt_n16(value.subtext)),
        image_url: record_opt_to_undefined(from_candid_opt_n16(value.image_url)),
        text_color: record_opt_to_undefined(from_candid_opt_n16(value.text_color)),
        headline: record_opt_to_undefined(from_candid_opt_n16(value.headline)),
        name: value.name,
        description: record_opt_to_undefined(from_candid_opt_n16(value.description)),
        updated_at_ms: value.updated_at_ms,
        created_at_ms: value.created_at_ms,
        logo_url: record_opt_to_undefined(from_candid_opt_n16(value.logo_url)),
        cta_label: record_opt_to_undefined(from_candid_opt_n16(value.cta_label)),
        is_active: value.is_active,
        ad_type: value.ad_type,
        display_order: value.display_order,
        bg_color: record_opt_to_undefined(from_candid_opt_n16(value.bg_color))
    };
}
function from_candid_record_n19(value: {
    id: string;
    status: _AlertStatus;
    alert_type: string;
    created_at_ms: bigint;
    details: string;
    resolved_at_ms: [] | [bigint];
    resolved_by: [] | [Principal];
}): {
    id: string;
    status: AlertStatus;
    alert_type: string;
    created_at_ms: bigint;
    details: string;
    resolved_at_ms?: bigint;
    resolved_by?: Principal;
} {
    return {
        id: value.id,
        status: from_candid_AlertStatus_n20(value.status),
        alert_type: value.alert_type,
        created_at_ms: value.created_at_ms,
        details: value.details,
        resolved_at_ms: record_opt_to_undefined(from_candid_opt_n22(value.resolved_at_ms)),
        resolved_by: record_opt_to_undefined(from_candid_opt_n23(value.resolved_by))
    };
}
function from_candid_record_n28(value: {
    dau: [] | [number];
    mau: [] | [number];
    wau: [] | [number];
    posters: [] | [number];
    value: number;
    period: string;
    read_rate: [] | [number];
    updated_at_ms: bigint;
    total_members: [] | [number];
    metric_key: string;
}): {
    dau?: number;
    mau?: number;
    wau?: number;
    posters?: number;
    value: number;
    period: string;
    read_rate?: number;
    updated_at_ms: bigint;
    total_members?: number;
    metric_key: string;
} {
    return {
        dau: record_opt_to_undefined(from_candid_opt_n29(value.dau)),
        mau: record_opt_to_undefined(from_candid_opt_n29(value.mau)),
        wau: record_opt_to_undefined(from_candid_opt_n29(value.wau)),
        posters: record_opt_to_undefined(from_candid_opt_n29(value.posters)),
        value: value.value,
        period: value.period,
        read_rate: record_opt_to_undefined(from_candid_opt_n30(value.read_rate)),
        updated_at_ms: value.updated_at_ms,
        total_members: record_opt_to_undefined(from_candid_opt_n29(value.total_members)),
        metric_key: value.metric_key
    };
}
function from_candid_record_n43(value: {
    total: number;
    items: Array<_AuditLog>;
}): {
    total: number;
    items: Array<AuditLog>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n44(value.items)
    };
}
function from_candid_record_n46(value: {
    id: string;
    target_user_name: [] | [string];
    action_type: string;
    actor_id: Principal;
    created_at_ms: bigint;
    details: string;
    table_name: string;
    target_user_id: [] | [string];
}): {
    id: string;
    target_user_name?: string;
    action_type: string;
    actor_id: Principal;
    created_at_ms: bigint;
    details: string;
    table_name: string;
    target_user_id?: string;
} {
    return {
        id: value.id,
        target_user_name: record_opt_to_undefined(from_candid_opt_n16(value.target_user_name)),
        action_type: value.action_type,
        actor_id: value.actor_id,
        created_at_ms: value.created_at_ms,
        details: value.details,
        table_name: value.table_name,
        target_user_id: record_opt_to_undefined(from_candid_opt_n16(value.target_user_id))
    };
}
function from_candid_record_n51(value: {
    total: number;
    items: Array<_Feedback>;
}): {
    total: number;
    items: Array<Feedback>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n52(value.items)
    };
}
function from_candid_record_n54(value: {
    id: string;
    status: _FeedbackStatus;
    title: [] | [string];
    kind: string;
    user: Principal;
    page_url: [] | [string];
    updated_at_ms: bigint;
    created_at_ms: bigint;
    message: string;
    admin_notes: [] | [string];
}): {
    id: string;
    status: FeedbackStatus;
    title?: string;
    kind: string;
    user: Principal;
    page_url?: string;
    updated_at_ms: bigint;
    created_at_ms: bigint;
    message: string;
    admin_notes?: string;
} {
    return {
        id: value.id,
        status: from_candid_FeedbackStatus_n55(value.status),
        title: record_opt_to_undefined(from_candid_opt_n16(value.title)),
        kind: value.kind,
        user: value.user,
        page_url: record_opt_to_undefined(from_candid_opt_n16(value.page_url)),
        updated_at_ms: value.updated_at_ms,
        created_at_ms: value.created_at_ms,
        message: value.message,
        admin_notes: record_opt_to_undefined(from_candid_opt_n16(value.admin_notes))
    };
}
function from_candid_record_n60(value: {
    page_path: string;
    started_at_ms: bigint;
    session_id: string;
    duration_seconds: number;
    user_id: string;
    club_id: [] | [string];
    page_label: string;
}): {
    page_path: string;
    started_at_ms: bigint;
    session_id: string;
    duration_seconds: number;
    user_id: string;
    club_id?: string;
    page_label: string;
} {
    return {
        page_path: value.page_path,
        started_at_ms: value.started_at_ms,
        session_id: value.session_id,
        duration_seconds: value.duration_seconds,
        user_id: value.user_id,
        club_id: record_opt_to_undefined(from_candid_opt_n16(value.club_id)),
        page_label: value.page_label
    };
}
function from_candid_variant_n1(value: {
    Ok: Array<_AdEventSummary>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<AdEventSummary>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n10(value: {
    Ok: bigint;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n13(value: {
    Ok: _AppAd;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: AppAd;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_AppAd_n14(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n17(value: {
    Ok: _AdminAlert;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: AdminAlert;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_AdminAlert_n18(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n21(value: {
    Open: null;
} | {
    Resolved: null;
}): AlertStatus {
    return "Open" in value ? AlertStatus.Open : "Resolved" in value ? AlertStatus.Resolved : value;
}
function from_candid_variant_n25(value: {
    Ok: Array<_Benchmark>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<Benchmark>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n26(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n3(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n31(value: {
    Ok: Array<_SponsorBenchmarkRow>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<SponsorBenchmarkRow>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n32(value: {
    Ok: _SponsorPerformance;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: SponsorPerformance;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n34(value: {
    Ok: Array<_AppAdSetting>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<AppAdSetting>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n38(value: {
    Ok: Array<_AdminAlert>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<AdminAlert>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n39(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n4(value: {
    Ok: _ClientPerfAggregate;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ClientPerfAggregate;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n40(value: {
    Ok: Array<_AppAd>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<AppAd>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n33(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n42(value: {
    Ok: {
        total: number;
        items: Array<_AuditLog>;
    };
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: {
        total: number;
        items: Array<AuditLog>;
    };
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_record_n43(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n5(value: {
    Ok: Array<_EngagementDayPoint>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<EngagementDayPoint>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n50(value: {
    Ok: {
        total: number;
        items: Array<_Feedback>;
    };
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: {
        total: number;
        items: Array<Feedback>;
    };
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_record_n51(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n56(value: {
    Open: null;
} | {
    InProgress: null;
} | {
    Resolved: null;
}): FeedbackStatus {
    return "Open" in value ? FeedbackStatus.Open : "InProgress" in value ? FeedbackStatus.InProgress : "Resolved" in value ? FeedbackStatus.Resolved : value;
}
function from_candid_variant_n57(value: {
    Ok: Array<_UserActivityEntry>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<UserActivityEntry>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n58(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n6(value: {
    Ok: _EngagementBenchmarks;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: EngagementBenchmarks;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n61(value: {
    Ok: _PerfAggregate;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: PerfAggregate;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n62(value: {
    Ok: Array<_PhotoEngagementTotal>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<PhotoEngagementTotal>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n67(value: {
    Ok: _Feedback;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Feedback;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Feedback_n53(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n7(value: {
    Ok: {
        clicks: Array<_EngagementDayPoint>;
        impressions: Array<_EngagementDayPoint>;
    };
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: {
        clicks: Array<EngagementDayPoint>;
        impressions: Array<EngagementDayPoint>;
    };
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n8(value: {
    Ok: number;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: number;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n9(value: {
    Ok: _EngagementTotals;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: EngagementTotals;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n26(value: Array<_Benchmark>): Array<Benchmark> {
    return value.map((x)=>from_candid_Benchmark_n27(x));
}
function from_candid_vec_n33(value: Array<_AppAd>): Array<AppAd> {
    return value.map((x)=>from_candid_AppAd_n14(x));
}
function from_candid_vec_n39(value: Array<_AdminAlert>): Array<AdminAlert> {
    return value.map((x)=>from_candid_AdminAlert_n18(x));
}
function from_candid_vec_n44(value: Array<_AuditLog>): Array<AuditLog> {
    return value.map((x)=>from_candid_AuditLog_n45(x));
}
function from_candid_vec_n52(value: Array<_Feedback>): Array<Feedback> {
    return value.map((x)=>from_candid_Feedback_n53(x));
}
function from_candid_vec_n58(value: Array<_UserActivityEntry>): Array<UserActivityEntry> {
    return value.map((x)=>from_candid_UserActivityEntry_n59(x));
}
function to_candid_AlertStatus_n36(value: AlertStatus): _AlertStatus {
    return to_candid_variant_n37(value);
}
function to_candid_AppAdInput_n11(value: AppAdInput): _AppAdInput {
    return to_candid_record_n12(value);
}
function to_candid_FeedbackStatus_n48(value: FeedbackStatus): _FeedbackStatus {
    return to_candid_variant_n49(value);
}
function to_candid_PhotoEngagementKind_n63(value: PhotoEngagementKind): _PhotoEngagementKind {
    return to_candid_variant_n64(value);
}
function to_candid_opt_n2(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n35(value: AlertStatus | null): [] | [_AlertStatus] {
    return value === null ? candid_none() : candid_some(to_candid_AlertStatus_n36(value));
}
function to_candid_opt_n41(value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n47(value: FeedbackStatus | null): [] | [_FeedbackStatus] {
    return value === null ? candid_none() : candid_some(to_candid_FeedbackStatus_n48(value));
}
function to_candid_opt_n65(value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n66(value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(value: {
    link_url?: string;
    subtext?: string;
    image_url?: string;
    text_color?: string;
    headline?: string;
    name: string;
    description?: string;
    logo_url?: string;
    cta_label?: string;
    ad_type: string;
    bg_color?: string;
}): {
    link_url: [] | [string];
    subtext: [] | [string];
    image_url: [] | [string];
    text_color: [] | [string];
    headline: [] | [string];
    name: string;
    description: [] | [string];
    logo_url: [] | [string];
    cta_label: [] | [string];
    ad_type: string;
    bg_color: [] | [string];
} {
    return {
        link_url: value.link_url ? candid_some(value.link_url) : candid_none(),
        subtext: value.subtext ? candid_some(value.subtext) : candid_none(),
        image_url: value.image_url ? candid_some(value.image_url) : candid_none(),
        text_color: value.text_color ? candid_some(value.text_color) : candid_none(),
        headline: value.headline ? candid_some(value.headline) : candid_none(),
        name: value.name,
        description: value.description ? candid_some(value.description) : candid_none(),
        logo_url: value.logo_url ? candid_some(value.logo_url) : candid_none(),
        cta_label: value.cta_label ? candid_some(value.cta_label) : candid_none(),
        ad_type: value.ad_type,
        bg_color: value.bg_color ? candid_some(value.bg_color) : candid_none()
    };
}
function to_candid_variant_n37(value: AlertStatus): {
    Open: null;
} | {
    Resolved: null;
} {
    return value == AlertStatus.Open ? {
        Open: null
    } : value == AlertStatus.Resolved ? {
        Resolved: null
    } : value;
}
function to_candid_variant_n49(value: FeedbackStatus): {
    Open: null;
} | {
    InProgress: null;
} | {
    Resolved: null;
} {
    return value == FeedbackStatus.Open ? {
        Open: null
    } : value == FeedbackStatus.InProgress ? {
        InProgress: null
    } : value == FeedbackStatus.Resolved ? {
        Resolved: null
    } : value;
}
function to_candid_variant_n64(value: PhotoEngagementKind): {
    View: null;
} | {
    Comment: null;
} | {
    Reaction: null;
} {
    return value == PhotoEngagementKind.View ? {
        View: null
    } : value == PhotoEngagementKind.Comment ? {
        Comment: null
    } : value == PhotoEngagementKind.Reaction ? {
        Reaction: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Insights_domain {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Insights_domain(actor);
}
