import Principal "mo:core/Principal";
module {
  type RoleGrant = { user : Principal; role : Text; club : ?Text; team : ?Text };
  type Team = { id : Text; club : Text };
  type Child = { id : Text; teams : [Text]; parent : ?Principal; club_id : ?Text };
  type Guardian = { child : Text; user : Principal };
  type Exclusion = { club : Text; user : Principal };
  type Acl = { teams : [Team]; guardians : [Guardian]; clubs : [Text]; children : [Child]; exclusions : [Exclusion]; roles : [RoleGrant] };
  type Draft = { url : Text; title : Text; icon : Text; is_active : Bool; open_mode : Text; subtitle : ?Text };
  type Link = { id : Text; sort_order : Nat32; created_at_ms : Nat64; draft : Draft; club_id : Text };
  type Listing = { links : [Link]; revision : Nat64 };
  type ClubProfile = { id : Text; secondary_color : ?Text; name : Text; slug : Text; description : ?Text; created_at_ms : Nat64; logo_url : ?Text; is_active : Bool; primary_color : ?Text; deleted_at_ms : ?Nat64; playhq_tenant : ?Text; playhq_org_id : ?Text };
  type ClubSettings = {
    contact_email : ?Text; membership_open : Bool; announcement : ?Text; public_directory : Bool; club_id : Text;
    media_sponsors_enabled : Bool; media_header_sponsors_enabled : Bool; events_sponsor_strip_enabled : Bool; chat_thread_ads_enabled : Bool;
    theme_primary_color : ?Text; theme_secondary_color : ?Text; theme_accent_color : ?Text;
    header_logo_enabled : Bool; header_club_name_enabled : Bool; invite_email_style : ?Text; club_switcher_hint : ?Text;
    theme_enabled : Bool; logo_only_mode : Bool;
    theme_dark_primary_color : ?Text; theme_dark_secondary_color : ?Text; theme_dark_accent_color : ?Text;
  };
  type ClubSponsor = { id : Text; website_url : ?Text; name : Text; tier : Text; sort_order : Nat32; logo_url : ?Text; is_active : Bool; club_id : Text; description : ?Text; is_team_only : Bool; exposure_percentage : ?Nat8 };
  type TeamSponsorAllocation = { sponsor_id : Text; team_id : Text };
  type ClubTeam = { id : Text; name : Text; division : ?Text; gender : ?Text; is_active : Bool; club_id : Text; age_group : ?Text; description : ?Text; logo_url : ?Text; team_type : ?Text; deleted_at_ms : ?Nat64; is_shell : Bool; shell_claim_token : ?Text; shell_claimed_at_ms : ?Nat64; shell_claimed_by : ?Principal; shell_contact_email : ?Text; shell_contact_name : ?Text; shell_invited_by : ?Principal; archived : Bool; playhq_team_id : ?Text; playhq_competition_id : ?Text; playhq_auto_create_events : Bool };
  type ClubTerm = { id : Text; club_id : Text; name : Text; start_date : Text; end_date : Text; is_active : Bool; status : Text; created_at_ms : Nat64 };
  type NewsPost = { id : Text; club_id : Text; title : Text; body : Text; status : Text; created_by : Principal; created_at_ms : Nat64; updated_at_ms : Nat64; revision : Nat64 };
  type ParentInvite = { id : Text; club_id : Text; team_id : ?Text; child_id : Text; invited_by : Principal; created_at_ms : Nat64; expires_at_ms : Nat64; accepted_by : ?Principal };
  type RoleRequest = { id : Text; account_id : Text; user : Principal; club : Text; role : Text; team : ?Text; status : Text; created_at_ms : Nat64; decided_at_ms : ?Nat64; decided_by : ?Principal };
  type TeamInvite = { id : Text; club_id : Text; team_id : Text; email : Text; role : Text; invited_by : Principal; created_at_ms : Nat64; expires_at_ms : Nat64; accepted_by : ?Principal; revoked : Bool };
  type TeamInviteLink = { id : Text; club_id : Text; team_id : Text; role : Text; token : Text; created_by : Principal; created_at_ms : Nat64; rotated_at_ms : ?Nat64; revoked : Bool };
  type PendingInvite = { id : Text; kind : Text; club_id : Text; team_id : ?Text; child_id : ?Text; email : Text; role : ?Text; invited_by : Principal; created_at_ms : Nat64; status : Text; resent_at_ms : ?Nat64; accepted_at_ms : ?Nat64; accepted_by : ?Principal };
  type TeamCreationRequest = { id : Text; club_id : Text; name : Text; division : ?Text; age_group : ?Text; requested_by : Principal; status : Text; created_at_ms : Nat64; decided_at_ms : ?Nat64; decided_by : ?Principal; team_id : ?Text };
  type TeamPlayerPosition = { team_id : Text; member_id : Text; position : Text };
  type TeamCaptain = { team_id : Text; user : Principal };
  type ClubJoinRequest = { id : Text; club_id : Text; user : Principal; status : Text; created_at_ms : Nat64; decided_at_ms : ?Nat64; decided_by : ?Principal };
  type Account = { id : Text; legacy_subject : Principal; version : Nat64; principals : [Principal] };
  type AccountExclusion = { account_id : Text; club : Text };
  type AccountRole = { account_id : Text; club : ?Text; role : Text; team : ?Text };
  type Challenge = { id : Nat64; account_id : Text; issuer : Principal; target : Principal; accepted : Bool; expires_at_ns : Nat64; expected_version : Nat64 };
  type Family = { account_id : Text; child_id : Text };
  type Mutation = { link : ?Link; revision : Nat64 };
  type RemovedMember = { club : Text; user : Principal; removed_at_ms : Nat64; removed_by : Principal };
  type MemberPayment = { id : Text; club_id : Text; user_id : Text; child_id : ?Text; payment_period : Text; payment_type : Text; amount : Float; notes : ?Text; marked_by : Principal; created_at_ms : Nat64 };
  type Season = { id : Text; club_id : Text; name : Text; status : Text; start_date : Text; end_date : Text; created_at_ms : Nat64; updated_at_ms : Nat64 };
  type SeasonTeamSummary = { season_id : Text; club_id : Text; team_id : Text; team_name : Text; events_count : Nat32; avg_attendance_pct : Float; roster_size : Nat32; updated_at_ms : Nat64 };
  type SeasonPlayerStat = { season_id : Text; club_id : Text; team_id : Text; club_player_id : Text; player_name : Text; events_total : Nat32; events_attended : Nat32; attendance_pct : Float; games_played : Nat32; updated_at_ms : Nat64 };
  type ClubSubscription = {
    club_id : Text; is_pro : Bool; is_pro_football : Bool;
    admin_pro_override : Bool; admin_pro_football_override : Bool;
    expires_at_ms : ?Nat64; plan : Text; team_limit : ?Nat32;
    trial_ends_at_ms : ?Nat64; is_trial : Bool;
    cancelled_at_ms : ?Nat64; activated_at_ms : ?Nat64;
  };
  type OldActor = {
    var governor : Principal; var acl : Acl; var aclVersion : Nat64;
    var profiles : [ClubProfile]; var settings : [ClubSettings]; var teams : [ClubTeam]; var sponsors : [ClubSponsor];
    var clubListings : [(Text, Listing)]; var frozenClubs : [(Text, Nat64)];
    var accounts : [Account]; var accountExclusions : [AccountExclusion]; var accountFamilies : [Family]; var accountChallenges : [Challenge]; var accountRoles : [AccountRole]; var nextChallengeId : Nat64;
    var mutationLog : [(Text, Text, Mutation)];
    var newsPosts : [NewsPost]; var parentInvites : [ParentInvite]; var roleRequests : [RoleRequest]; var teamInvites : [TeamInvite];
    var teamInviteLinks : [TeamInviteLink];
    var pendingInvites : [PendingInvite];
    var teamCreationRequests : [TeamCreationRequest];
    var teamPlayerPositions : [TeamPlayerPosition];
    var teamCaptains : [TeamCaptain];
    var clubJoinRequests : [ClubJoinRequest];
    var themePrefs : [(Principal, Text)];
    var clubTerms : [ClubTerm];
    var removedMembers : [RemovedMember];
    var memberPayments : [MemberPayment];
    var teamSponsorAllocations : [TeamSponsorAllocation];
    var seasons : [Season];
    var seasonTeamSummaries : [SeasonTeamSummary];
    var seasonPlayerStats : [SeasonPlayerStat];
    var notificationQueueCanister : ?Principal;
    var clubSubscriptions : [ClubSubscription];
  };
  type NewActor = {
    var governor : Principal; var acl : Acl; var aclVersion : Nat64;
    var profiles : [ClubProfile]; var settings : [ClubSettings]; var teams : [ClubTeam]; var sponsors : [ClubSponsor];
    var clubListings : [(Text, Listing)]; var frozenClubs : [(Text, Nat64)];
    var accounts : [Account]; var accountExclusions : [AccountExclusion]; var accountFamilies : [Family]; var accountChallenges : [Challenge]; var accountRoles : [AccountRole]; var nextChallengeId : Nat64;
    var mutationLog : [(Text, Text, Mutation)];
    var newsPosts : [NewsPost]; var parentInvites : [ParentInvite]; var roleRequests : [RoleRequest]; var teamInvites : [TeamInvite];
    var teamInviteLinks : [TeamInviteLink];
    var pendingInvites : [PendingInvite];
    var teamCreationRequests : [TeamCreationRequest];
    var teamPlayerPositions : [TeamPlayerPosition];
    var teamCaptains : [TeamCaptain];
    var clubJoinRequests : [ClubJoinRequest];
    var themePrefs : [(Principal, Text)];
    var clubTerms : [ClubTerm];
    var removedMembers : [RemovedMember];
    var memberPayments : [MemberPayment];
    var teamSponsorAllocations : [TeamSponsorAllocation];
    var seasons : [Season];
    var seasonTeamSummaries : [SeasonTeamSummary];
    var seasonPlayerStats : [SeasonPlayerStat];
    var notificationQueueCanister : ?Principal;
    var clubSubscriptions : [ClubSubscription];
    var appConfig : [(Text, Text)];
  };
  public func migration(old : OldActor) : NewActor {
    {
      var governor = old.governor;
      var acl = old.acl;
      var aclVersion = old.aclVersion;
      var profiles = old.profiles;
      var settings = old.settings;
      var teams = old.teams;
      var sponsors = old.sponsors;
      var clubListings = old.clubListings;
      var frozenClubs = old.frozenClubs;
      var accounts = old.accounts;
      var accountExclusions = old.accountExclusions;
      var accountFamilies = old.accountFamilies;
      var accountChallenges = old.accountChallenges;
      var accountRoles = old.accountRoles;
      var nextChallengeId = old.nextChallengeId;
      var mutationLog = old.mutationLog;
      var newsPosts = old.newsPosts;
      var parentInvites = old.parentInvites;
      var roleRequests = old.roleRequests;
      var teamInvites = old.teamInvites;
      var teamInviteLinks = old.teamInviteLinks;
      var pendingInvites = old.pendingInvites;
      var teamCreationRequests = old.teamCreationRequests;
      var teamPlayerPositions = old.teamPlayerPositions;
      var teamCaptains = old.teamCaptains;
      var clubJoinRequests = old.clubJoinRequests;
      var themePrefs = old.themePrefs;
      var clubTerms = old.clubTerms;
      var removedMembers = old.removedMembers;
      var memberPayments = old.memberPayments;
      var teamSponsorAllocations = old.teamSponsorAllocations;
      var seasons = old.seasons;
      var seasonTeamSummaries = old.seasonTeamSummaries;
      var seasonPlayerStats = old.seasonPlayerStats;
      var notificationQueueCanister = old.notificationQueueCanister;
      var clubSubscriptions = old.clubSubscriptions;
      var appConfig = [];
    }
  };
};
