/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAlert {
  'id' : string,
  'status' : AlertStatus,
  'alert_type' : string,
  'created_at_ms' : bigint,
  'details' : string,
  'resolved_at_ms' : [] | [bigint],
  'resolved_by' : [] | [Principal],
}
export type AlertStatus = { 'Open' : null } |
  { 'Resolved' : null };
export interface AuditLog {
  'id' : string,
  'target_user_name' : [] | [string],
  'action_type' : string,
  'actor_id' : Principal,
  'created_at_ms' : bigint,
  'details' : string,
  'table_name' : string,
  'target_user_id' : [] | [string],
}
export interface Benchmark {
  'value' : number,
  'period' : string,
  'updated_at_ms' : bigint,
  'metric_key' : string,
}
export interface ClientPerfAggregate {
  'path' : string,
  'count' : number,
  'p50_ms' : number,
  'p95_ms' : number,
  'avg_ms' : number,
}
export interface ClientPerfEntry {
  'metric' : string,
  'principal' : Principal,
  'at_ms' : bigint,
  'path' : string,
  'value_ms' : number,
}
export interface EngagementBenchmarks {
  'previous' : EngagementTotals,
  'current' : EngagementTotals,
  'club_id' : string,
}
export interface EngagementDayPoint { 'day' : string, 'value' : number }
export interface EngagementTotals {
  'messages' : number,
  'sponsor_clicks' : number,
  'active_users' : number,
  'sponsor_impressions' : number,
  'club_id' : string,
  'rsvps' : number,
}
export interface Feedback {
  'id' : string,
  'status' : FeedbackStatus,
  'title' : [] | [string],
  'kind' : string,
  'user' : Principal,
  'page_url' : [] | [string],
  'updated_at_ms' : bigint,
  'created_at_ms' : bigint,
  'message' : string,
  'admin_notes' : [] | [string],
}
export type FeedbackStatus = { 'Open' : null } |
  { 'InProgress' : null } |
  { 'Resolved' : null };
export interface PerfAggregate {
  'source' : string,
  'count' : number,
  'surface' : string,
  'p50_ms' : number,
  'p95_ms' : number,
  'avg_ms' : number,
}
export interface PerfSampleInput {
  'source' : string,
  'cache_hit' : boolean,
  'surface' : string,
  'platform' : string,
  'duration_ms' : number,
}
export interface SponsorPerformance {
  'metrics' : Array<{ 'metric' : string, 'value' : number }>,
  'period' : string,
  'sponsor_id' : string,
}
export interface _SERVICE {
  'append_audit_log' : ActorMethod<
    [string, string, [] | [string], [] | [string], string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'client_perf_aggregate' : ActorMethod<
    [string, [] | [string], bigint, bigint],
    { 'Ok' : ClientPerfAggregate } |
      { 'Err' : string }
  >,
  'club_engagement_active_users' : ActorMethod<
    [string, bigint, bigint],
    { 'Ok' : Array<EngagementDayPoint> } |
      { 'Err' : string }
  >,
  'club_engagement_benchmarks' : ActorMethod<
    [string, bigint, bigint, bigint, bigint],
    { 'Ok' : EngagementBenchmarks } |
      { 'Err' : string }
  >,
  'club_engagement_message_volume' : ActorMethod<
    [string, bigint, bigint],
    { 'Ok' : Array<EngagementDayPoint> } |
      { 'Err' : string }
  >,
  'club_engagement_rsvp_completion_series' : ActorMethod<
    [string, bigint, bigint],
    { 'Ok' : Array<EngagementDayPoint> } |
      { 'Err' : string }
  >,
  'club_engagement_sponsor_performance' : ActorMethod<
    [string, bigint, bigint],
    {
        'Ok' : {
          'clicks' : Array<EngagementDayPoint>,
          'impressions' : Array<EngagementDayPoint>,
        }
      } |
      { 'Err' : string }
  >,
  'club_engagement_total_unique_reach' : ActorMethod<
    [string, bigint, bigint],
    { 'Ok' : number } |
      { 'Err' : string }
  >,
  'club_engagement_totals' : ActorMethod<
    [string, bigint, bigint],
    { 'Ok' : EngagementTotals } |
      { 'Err' : string }
  >,
  'create_admin_alert' : ActorMethod<
    [string, string],
    { 'Ok' : AdminAlert } |
      { 'Err' : string }
  >,
  'get_benchmarks' : ActorMethod<
    [Array<string>],
    { 'Ok' : Array<Benchmark> } |
      { 'Err' : string }
  >,
  'get_sponsor_performance' : ActorMethod<
    [string, string],
    { 'Ok' : SponsorPerformance } |
      { 'Err' : string }
  >,
  'grant_role' : ActorMethod<
    [Principal, string, string, [] | [string]],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'initialize' : ActorMethod<[], { 'Ok' : null } | { 'Err' : string }>,
  'list_admin_alerts' : ActorMethod<
    [[] | [AlertStatus]],
    { 'Ok' : Array<AdminAlert> } |
      { 'Err' : string }
  >,
  'list_audit_logs' : ActorMethod<
    [[] | [Principal], [] | [string], [] | [string], number, number],
    { 'Ok' : { 'total' : number, 'items' : Array<AuditLog> } } |
      { 'Err' : string }
  >,
  'list_feedback' : ActorMethod<
    [[] | [FeedbackStatus], number, number],
    { 'Ok' : { 'total' : number, 'items' : Array<Feedback> } } |
      { 'Err' : string }
  >,
  'my_feedback' : ActorMethod<[], Array<Feedback>>,
  'perf_aggregate' : ActorMethod<
    [string, [] | [string], bigint, bigint],
    { 'Ok' : PerfAggregate } |
      { 'Err' : string }
  >,
  'record_active_user' : ActorMethod<
    [string, string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'record_client_perf' : ActorMethod<
    [Array<ClientPerfEntry>],
    { 'Ok' : number } |
      { 'Err' : string }
  >,
  'record_message_sent' : ActorMethod<
    [string, string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'record_perf_sample' : ActorMethod<
    [string, string, number, boolean, string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'record_perf_samples_batch' : ActorMethod<
    [Array<PerfSampleInput>],
    { 'Ok' : number } |
      { 'Err' : string }
  >,
  'record_rsvp_completed' : ActorMethod<
    [string, string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'record_sponsor_click' : ActorMethod<
    [string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'record_sponsor_impression' : ActorMethod<
    [string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'record_sponsor_metric' : ActorMethod<
    [string, string, number],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'record_web_vital' : ActorMethod<
    [string, number, string, string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'resolve_admin_alert' : ActorMethod<
    [string],
    { 'Ok' : AdminAlert } |
      { 'Err' : string }
  >,
  'set_benchmark' : ActorMethod<
    [string, string, number],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'submit_feedback' : ActorMethod<
    [string, [] | [string], string, [] | [string]],
    { 'Ok' : Feedback } |
      { 'Err' : string }
  >,
  'update_feedback_status' : ActorMethod<
    [string, FeedbackStatus, [] | [string]],
    { 'Ok' : Feedback } |
      { 'Err' : string }
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];