/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FinalizedBlob {
  'path' : string,
  'content_hash' : string,
  'content_length' : bigint,
}
export type HeaderField = [string, string];
export interface Health {
  'total_bytes' : bigint,
  'version' : string,
  'blob_count' : bigint,
}
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<HeaderField>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<HeaderField>,
  'status_code' : number,
}
export type Result = { 'Ok' : null } |
  { 'Err' : string };
export type ResultFinalized = { 'Ok' : FinalizedBlob } |
  { 'Err' : string };
export type ResultUploadId = { 'Ok' : string } |
  { 'Err' : string };
export interface _SERVICE {
  'abort_upload' : ActorMethod<[string], Result>,
  'begin_upload' : ActorMethod<
    [string, string, bigint, number],
    ResultUploadId
  >,
  'delete_blob' : ActorMethod<[string], Result>,
  'finalize_upload' : ActorMethod<[string], ResultFinalized>,
  'get_content_hash' : ActorMethod<[string], [] | [string]>,
  'health' : ActorMethod<[], Health>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'put_chunk' : ActorMethod<[string, number, Uint8Array], Result>,
  'set_club_domain_canister' : ActorMethod<[Principal], Result>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];