/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/migration_coordinator.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface MainInterface {
    abort(id: bigint): Promise<Migration>;
    begin(domain: string, source: Principal, destination: Principal, schemaVersion: bigint, checksum: string): Promise<Migration>;
    commit(id: bigint): Promise<Migration>;
    markExported(id: bigint, recordCount: bigint, checksum: string): Promise<Migration>;
    markImported(id: bigint, recordCount: bigint, checksum: string): Promise<Migration>;
    orchestrateExport(id: bigint): Promise<Migration>;
    orchestrateVerify(id: bigint): Promise<Migration>;
    status(): Promise<[Migration | null, Array<Migration>]>;
    transfer_governorship(new_governor: Principal): Promise<void>;
    verify(id: bigint, recordCount: bigint, checksum: string): Promise<Migration>;
}
export interface Migration {
    id: bigint;
    destination: Principal;
    domain: string;
    source: Principal;
    checksum: string;
    schemaVersion: bigint;
    phase: Phase;
    recordCount: bigint;
}
export enum Phase {
    exported = "exported",
    verified = "verified",
    aborted = "aborted",
    imported = "imported",
    started = "started",
    committed = "committed"
}
export interface migration_coordinatorInterface extends MainInterface {
}
import type { Migration as _Migration, Phase as _Phase } from "./declarations/migration_coordinator.did";
export class Migration_coordinator implements migration_coordinatorInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async abort(arg0: bigint): Promise<Migration> {
        const result = await this.actor.abort(arg0);
        return from_candid_Migration_n1(result);
    }
    async begin(arg0: string, arg1: Principal, arg2: Principal, arg3: bigint, arg4: string): Promise<Migration> {
        const result = await this.actor.begin(arg0, arg1, arg2, arg3, arg4);
        return from_candid_Migration_n1(result);
    }
    async commit(arg0: bigint): Promise<Migration> {
        const result = await this.actor.commit(arg0);
        return from_candid_Migration_n1(result);
    }
    async markExported(arg0: bigint, arg1: bigint, arg2: string): Promise<Migration> {
        const result = await this.actor.markExported(arg0, arg1, arg2);
        return from_candid_Migration_n1(result);
    }
    async markImported(arg0: bigint, arg1: bigint, arg2: string): Promise<Migration> {
        const result = await this.actor.markImported(arg0, arg1, arg2);
        return from_candid_Migration_n1(result);
    }
    async orchestrateExport(arg0: bigint): Promise<Migration> {
        const result = await this.actor.orchestrateExport(arg0);
        return from_candid_Migration_n1(result);
    }
    async orchestrateVerify(arg0: bigint): Promise<Migration> {
        const result = await this.actor.orchestrateVerify(arg0);
        return from_candid_Migration_n1(result);
    }
    async status(): Promise<[Migration | null, Array<Migration>]> {
        const result = await this.actor.status();
        return [
            from_candid_opt_n5(result[0]),
            from_candid_vec_n6(result[1])
        ];
    }
    async transfer_governorship(arg0: Principal): Promise<void> {
        const result = await this.actor.transfer_governorship(arg0);
        return result;
    }
    async verify(arg0: bigint, arg1: bigint, arg2: string): Promise<Migration> {
        const result = await this.actor.verify(arg0, arg1, arg2);
        return from_candid_Migration_n1(result);
    }
}
function from_candid_Migration_n1(value: _Migration): Migration {
    return from_candid_record_n2(value);
}
function from_candid_Phase_n3(value: _Phase): Phase {
    return from_candid_variant_n4(value);
}
function from_candid_opt_n5(value: [] | [_Migration]): Migration | null {
    return value.length === 0 ? null : from_candid_Migration_n1(value[0]);
}
function from_candid_record_n2(value: {
    id: bigint;
    destination: Principal;
    domain: string;
    source: Principal;
    checksum: string;
    schemaVersion: bigint;
    phase: _Phase;
    recordCount: bigint;
}): {
    id: bigint;
    destination: Principal;
    domain: string;
    source: Principal;
    checksum: string;
    schemaVersion: bigint;
    phase: Phase;
    recordCount: bigint;
} {
    return {
        id: value.id,
        destination: value.destination,
        domain: value.domain,
        source: value.source,
        checksum: value.checksum,
        schemaVersion: value.schemaVersion,
        phase: from_candid_Phase_n3(value.phase),
        recordCount: value.recordCount
    };
}
function from_candid_variant_n4(value: {
    exported: null;
} | {
    verified: null;
} | {
    aborted: null;
} | {
    imported: null;
} | {
    started: null;
} | {
    committed: null;
}): Phase {
    return "exported" in value ? Phase.exported : "verified" in value ? Phase.verified : "aborted" in value ? Phase.aborted : "imported" in value ? Phase.imported : "started" in value ? Phase.started : "committed" in value ? Phase.committed : value;
}
function from_candid_vec_n6(value: Array<_Migration>): Array<Migration> {
    return value.map((x)=>from_candid_Migration_n1(x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Migration_coordinator {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Migration_coordinator(actor);
}
