/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/vault_domain.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface VaultFolder {
    id: string;
    mini_league_id?: string;
    club: string;
    name: string;
    color?: string;
    team?: string;
    restricted_roles: Array<string>;
    sort_order: number;
    description?: string;
    created_by: Principal;
    created_at_ms: bigint;
    parent_id?: string;
    deleted_by?: Principal;
    deleted_at_ms?: bigint;
}
export interface VaultFile {
    id: string;
    mini_league_id?: string;
    club: string;
    mime: string;
    name: string;
    size: bigint;
    team?: string;
    file_url: string;
    created_at_ms: bigint;
    blob_ref?: BlobRef;
    deleted_by?: Principal;
    folder_id: string;
    is_external_link: boolean;
    deleted_at_ms?: bigint;
    uploaded_by: Principal;
}
export interface MainInterface {
    create_folder(id: string, club: string, team: string | null, parent_id: string | null, name: string, restricted_roles: Array<string>, mini_league_id: string | null, sort_order: number, description: string | null, color: string | null): Promise<{
        __kind__: "Ok";
        Ok: VaultFolder;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    /**
     * / Public: remaining cycles (shown in admin settings).
     */
    cycles_balance(): Promise<bigint>;
    delete_file_permanent(id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    delete_folder(id: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFolder;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_file(id: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFile | null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_folder(id: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFolder | null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    grant_role(user: Principal, role: string, club_id: string | null, team_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_club_files(club: string, team: string | null, mini_league_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFile>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_club_files_with_folder(club: string, team: string | null, mini_league_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFileWithFolder>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_files(folder_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFile>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_files_with_folder(folder_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFileWithFolder>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_folders(club: string, team: string | null, mini_league_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFolder>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_trashed_files(club: string): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFile>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_trashed_files_with_folder(club: string): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFileWithFolder>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    move_file(id: string, folder_id: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFile;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    register_file(id: string, folder_id: string, club: string, team: string | null, name: string, file_url: string, size: bigint, mime: string, is_external_link: boolean, blob_ref: BlobRef | null, mini_league_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: VaultFile;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    rename_file(id: string, name: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFile;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    restore_file(id: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFile;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_club_domain_canister(canister: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    transfer_governorship(new_governor: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    trash_file(id: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFile;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    update_folder(id: string, name: string, restricted_roles: Array<string>, sort_order: number, description: string | null, color: string | null): Promise<{
        __kind__: "Ok";
        Ok: VaultFolder;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
}
export interface BlobRef {
    path: string;
    content_hash: string;
    canister: string;
}
export interface VaultFileWithFolder {
    folder_name?: string;
    folder_path: Array<string>;
    file: VaultFile;
}
export interface vault_domainInterface extends MainInterface {
}
import type { BlobRef as _BlobRef, VaultFile as _VaultFile, VaultFileWithFolder as _VaultFileWithFolder, VaultFolder as _VaultFolder } from "./declarations/vault_domain.did";
export class Vault_domain implements vault_domainInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async create_folder(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string, arg5: Array<string>, arg6: string | null, arg7: number, arg8: string | null, arg9: string | null): Promise<{
        __kind__: "Ok";
        Ok: VaultFolder;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_folder(arg0, arg1, to_candid_opt_n1(arg2), to_candid_opt_n1(arg3), arg4, arg5, to_candid_opt_n1(arg6), arg7, to_candid_opt_n1(arg8), to_candid_opt_n1(arg9));
        return from_candid_variant_n2(result);
    }
    async cycles_balance(): Promise<bigint> {
        const result = await this.actor.cycles_balance();
        return result;
    }
    async delete_file_permanent(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_file_permanent(arg0);
        return from_candid_variant_n8(result);
    }
    async delete_folder(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFolder;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_folder(arg0);
        return from_candid_variant_n2(result);
    }
    async get_file(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFile | null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_file(arg0);
        return from_candid_variant_n9(result);
    }
    async get_folder(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFolder | null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_folder(arg0);
        return from_candid_variant_n14(result);
    }
    async grant_role(arg0: Principal, arg1: string, arg2: string | null, arg3: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.grant_role(arg0, arg1, to_candid_opt_n1(arg2), to_candid_opt_n1(arg3));
        return from_candid_variant_n8(result);
    }
    async list_club_files(arg0: string, arg1: string | null, arg2: string | null): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFile>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_club_files(arg0, to_candid_opt_n1(arg1), to_candid_opt_n1(arg2));
        return from_candid_variant_n16(result);
    }
    async list_club_files_with_folder(arg0: string, arg1: string | null, arg2: string | null): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFileWithFolder>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_club_files_with_folder(arg0, to_candid_opt_n1(arg1), to_candid_opt_n1(arg2));
        return from_candid_variant_n18(result);
    }
    async list_files(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFile>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_files(arg0);
        return from_candid_variant_n16(result);
    }
    async list_files_with_folder(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFileWithFolder>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_files_with_folder(arg0);
        return from_candid_variant_n18(result);
    }
    async list_folders(arg0: string, arg1: string | null, arg2: string | null): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFolder>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_folders(arg0, to_candid_opt_n1(arg1), to_candid_opt_n1(arg2));
        return from_candid_variant_n22(result);
    }
    async list_trashed_files(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFile>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_trashed_files(arg0);
        return from_candid_variant_n16(result);
    }
    async list_trashed_files_with_folder(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<VaultFileWithFolder>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_trashed_files_with_folder(arg0);
        return from_candid_variant_n18(result);
    }
    async move_file(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFile;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.move_file(arg0, arg1);
        return from_candid_variant_n24(result);
    }
    async register_file(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: string, arg6: bigint, arg7: string, arg8: boolean, arg9: BlobRef | null, arg10: string | null): Promise<{
        __kind__: "Ok";
        Ok: VaultFile;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.register_file(arg0, arg1, arg2, to_candid_opt_n1(arg3), arg4, arg5, arg6, arg7, arg8, to_candid_opt_n25(arg9), to_candid_opt_n1(arg10));
        return from_candid_variant_n24(result);
    }
    async rename_file(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFile;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.rename_file(arg0, arg1);
        return from_candid_variant_n24(result);
    }
    async restore_file(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFile;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.restore_file(arg0);
        return from_candid_variant_n24(result);
    }
    async set_club_domain_canister(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_club_domain_canister(arg0);
        return from_candid_variant_n8(result);
    }
    async transfer_governorship(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.transfer_governorship(arg0);
        return from_candid_variant_n8(result);
    }
    async trash_file(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: VaultFile;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.trash_file(arg0);
        return from_candid_variant_n24(result);
    }
    async update_folder(arg0: string, arg1: string, arg2: Array<string>, arg3: number, arg4: string | null, arg5: string | null): Promise<{
        __kind__: "Ok";
        Ok: VaultFolder;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.update_folder(arg0, arg1, arg2, arg3, to_candid_opt_n1(arg4), to_candid_opt_n1(arg5));
        return from_candid_variant_n2(result);
    }
}
function from_candid_VaultFileWithFolder_n20(value: _VaultFileWithFolder): VaultFileWithFolder {
    return from_candid_record_n21(value);
}
function from_candid_VaultFile_n11(value: _VaultFile): VaultFile {
    return from_candid_record_n12(value);
}
function from_candid_VaultFolder_n3(value: _VaultFolder): VaultFolder {
    return from_candid_record_n4(value);
}
function from_candid_opt_n10(value: [] | [_VaultFile]): VaultFile | null {
    return value.length === 0 ? null : from_candid_VaultFile_n11(value[0]);
}
function from_candid_opt_n13(value: [] | [_BlobRef]): BlobRef | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(value: [] | [_VaultFolder]): VaultFolder | null {
    return value.length === 0 ? null : from_candid_VaultFolder_n3(value[0]);
}
function from_candid_opt_n5(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(value: {
    id: string;
    mini_league_id: [] | [string];
    club: string;
    mime: string;
    name: string;
    size: bigint;
    team: [] | [string];
    file_url: string;
    created_at_ms: bigint;
    blob_ref: [] | [_BlobRef];
    deleted_by: [] | [Principal];
    folder_id: string;
    is_external_link: boolean;
    deleted_at_ms: [] | [bigint];
    uploaded_by: Principal;
}): {
    id: string;
    mini_league_id?: string;
    club: string;
    mime: string;
    name: string;
    size: bigint;
    team?: string;
    file_url: string;
    created_at_ms: bigint;
    blob_ref?: BlobRef;
    deleted_by?: Principal;
    folder_id: string;
    is_external_link: boolean;
    deleted_at_ms?: bigint;
    uploaded_by: Principal;
} {
    return {
        id: value.id,
        mini_league_id: record_opt_to_undefined(from_candid_opt_n5(value.mini_league_id)),
        club: value.club,
        mime: value.mime,
        name: value.name,
        size: value.size,
        team: record_opt_to_undefined(from_candid_opt_n5(value.team)),
        file_url: value.file_url,
        created_at_ms: value.created_at_ms,
        blob_ref: record_opt_to_undefined(from_candid_opt_n13(value.blob_ref)),
        deleted_by: record_opt_to_undefined(from_candid_opt_n6(value.deleted_by)),
        folder_id: value.folder_id,
        is_external_link: value.is_external_link,
        deleted_at_ms: record_opt_to_undefined(from_candid_opt_n7(value.deleted_at_ms)),
        uploaded_by: value.uploaded_by
    };
}
function from_candid_record_n21(value: {
    folder_name: [] | [string];
    folder_path: Array<string>;
    file: _VaultFile;
}): {
    folder_name?: string;
    folder_path: Array<string>;
    file: VaultFile;
} {
    return {
        folder_name: record_opt_to_undefined(from_candid_opt_n5(value.folder_name)),
        folder_path: value.folder_path,
        file: from_candid_VaultFile_n11(value.file)
    };
}
function from_candid_record_n4(value: {
    id: string;
    mini_league_id: [] | [string];
    club: string;
    name: string;
    color: [] | [string];
    team: [] | [string];
    restricted_roles: Array<string>;
    sort_order: number;
    description: [] | [string];
    created_by: Principal;
    created_at_ms: bigint;
    parent_id: [] | [string];
    deleted_by: [] | [Principal];
    deleted_at_ms: [] | [bigint];
}): {
    id: string;
    mini_league_id?: string;
    club: string;
    name: string;
    color?: string;
    team?: string;
    restricted_roles: Array<string>;
    sort_order: number;
    description?: string;
    created_by: Principal;
    created_at_ms: bigint;
    parent_id?: string;
    deleted_by?: Principal;
    deleted_at_ms?: bigint;
} {
    return {
        id: value.id,
        mini_league_id: record_opt_to_undefined(from_candid_opt_n5(value.mini_league_id)),
        club: value.club,
        name: value.name,
        color: record_opt_to_undefined(from_candid_opt_n5(value.color)),
        team: record_opt_to_undefined(from_candid_opt_n5(value.team)),
        restricted_roles: value.restricted_roles,
        sort_order: value.sort_order,
        description: record_opt_to_undefined(from_candid_opt_n5(value.description)),
        created_by: value.created_by,
        created_at_ms: value.created_at_ms,
        parent_id: record_opt_to_undefined(from_candid_opt_n5(value.parent_id)),
        deleted_by: record_opt_to_undefined(from_candid_opt_n6(value.deleted_by)),
        deleted_at_ms: record_opt_to_undefined(from_candid_opt_n7(value.deleted_at_ms))
    };
}
function from_candid_variant_n14(value: {
    Ok: [] | [_VaultFolder];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: VaultFolder | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n15(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n16(value: {
    Ok: Array<_VaultFile>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<VaultFile>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n17(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n18(value: {
    Ok: Array<_VaultFileWithFolder>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<VaultFileWithFolder>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n19(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: _VaultFolder;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: VaultFolder;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_VaultFolder_n3(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n22(value: {
    Ok: Array<_VaultFolder>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<VaultFolder>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n23(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n24(value: {
    Ok: _VaultFile;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: VaultFile;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_VaultFile_n11(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n8(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n9(value: {
    Ok: [] | [_VaultFile];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: VaultFile | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n10(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n17(value: Array<_VaultFile>): Array<VaultFile> {
    return value.map((x)=>from_candid_VaultFile_n11(x));
}
function from_candid_vec_n19(value: Array<_VaultFileWithFolder>): Array<VaultFileWithFolder> {
    return value.map((x)=>from_candid_VaultFileWithFolder_n20(x));
}
function from_candid_vec_n23(value: Array<_VaultFolder>): Array<VaultFolder> {
    return value.map((x)=>from_candid_VaultFolder_n3(x));
}
function to_candid_opt_n1(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(value: BlobRef | null): [] | [_BlobRef] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Vault_domain {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Vault_domain(actor);
}
