[dependencies]
core = "2.6.1"
sha2 = "0.2.5"

[toolchain]
moc = "1.16.1"

[package]
name = "media_blob_store"
version = "0.1.0"

[canisters.media_blob_store]
main = "src/main.mo"
candid = "media_blob_store.did"

[canisters.media_blob_store.migrations]
chain = "src/backend/migrations"
check-limit = 1
