[toolchain]
moc = "1.16.1"

[moc]
args = [ "--default-persistent-actors" ]

[dependencies]
core = "2.6.1"

[canisters.insights_domain]
main = "src/main.mo"
candid = "insights_domain.did"

[canisters.insights_domain.migrations]
chain = "src/backend/migrations"
check-limit = 1
