/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Notification {
  'id' : string,
  'status' : Status,
  'body' : string,
  'club' : string,
  'next_attempt_ms' : bigint,
  'kind' : string,
  'read' : boolean,
  'user' : string,
  'attempts' : number,
  'created_at_ms' : bigint,
  'related_id' : [] | [string],
  'idempotency_key' : string,
}
export type Result = { 'Ok' : Notification } |
  { 'Err' : string };
export type ResultNat16 = { 'Ok' : number } |
  { 'Err' : string };
export type Results = { 'Ok' : Array<Notification> } |
  { 'Err' : string };
export type Status = { 'Failed' : null } |
  { 'Delivered' : null } |
  { 'Processing' : null } |
  { 'Pending' : null };
export interface _SERVICE {
  'acknowledge' : ActorMethod<[string, string], Result>,
  'claim' : ActorMethod<[bigint, number], Results>,
  'clear_inbox' : ActorMethod<[string, [] | [string]], ResultNat16>,
  'delete_notification' : ActorMethod<
    [string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'enqueue' : ActorMethod<
    [string, string, string, string, string, string],
    Result
  >,
  'fail' : ActorMethod<[string, string, [] | [bigint]], Result>,
  'fan_out' : ActorMethod<
    [Array<string>, string, string, string, string, [] | [string]],
    ResultNat16
  >,
  'get_notification' : ActorMethod<[string], [] | [Notification]>,
  'grant_worker' : ActorMethod<
    [Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'initialize' : ActorMethod<[], { 'Ok' : null } | { 'Err' : string }>,
  'list_inbox' : ActorMethod<[string, [] | [string], number], Results>,
  'mark_all_read' : ActorMethod<[string, [] | [string]], ResultNat16>,
  'mark_read' : ActorMethod<[string], Result>,
  'recover' : ActorMethod<[], ResultNat16>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];