/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/events_domain.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface EventSeries {
    id: string;
    title: string;
    creator: Principal;
    deleted: boolean;
    until_ms: bigint;
    first_starts_at_ms: bigint;
    team_id?: string;
    description: string;
    frequency: string;
    first_ends_at_ms: bigint;
    revision: bigint;
    club_id: string;
    location?: string;
    event_type: string;
}
export interface EventView {
    viewed_at_ms: bigint;
    event_id: string;
    viewer: Principal;
}
export interface EventGroupPlayer {
    account_id: string;
    group_id: string;
}
export interface LineupSnapshot {
    updated_by: Principal;
    formation?: string;
    ball_x?: number;
    ball_y?: number;
    team_id?: string;
    updated_at_ms: bigint;
    team_size: number;
    players: Array<LineupPlayer>;
    event_id: string;
    revision: bigint;
}
export type RsvpSubject = {
    __kind__: "account";
    account: string;
} | {
    __kind__: "mini_league_player";
    mini_league_player: string;
};
export interface EventGuest {
    id: string;
    added_by: Principal;
    guest_name: string;
    created_at_ms: bigint;
    event_id: string;
}
export interface TeamTrainingPause {
    id: string;
    team_id: string;
    created_by: Principal;
    starts_at_ms: bigint;
    created_at_ms: bigint;
    ends_at_ms: bigint;
    club_id: string;
    reason: string;
}
export interface PushReachability {
    user: Principal;
    updated_at_ms: bigint;
    reachable: boolean;
}
export interface Rsvp {
    account_id: string;
    source: string;
    updated_at_ms: bigint;
    child_id?: string;
    state: string;
    notes: string;
    event_id: string;
    has_paid?: boolean;
}
export interface RoleGrant {
    role: string;
    user: Principal;
    team_id?: string;
    club_id: string;
}
export interface Duty {
    account_id: string;
    duty: string;
    completed: boolean;
    event_id: string;
}
export interface RsvpWithChild {
    child?: Child;
    rsvp: Rsvp;
}
export interface RosterEntry {
    account_id: string;
    child_id?: string;
    event_id: string;
}
export interface Recurrence {
    until_ms: bigint;
    frequency: string;
    event_id: string;
}
export interface Child {
    id: string;
    name: string;
    parent_id?: string;
}
export interface EventRoster {
    guests: Array<EventGuest>;
    rsvps: Array<RsvpWithChild>;
}
export interface ChildGuardian {
    is_primary: boolean;
    child_id: string;
    guardian_id: string;
}
export interface EventGroup {
    id: string;
    name: string;
    created_at_ms: bigint;
    event_id: string;
}
export interface ReminderLog {
    id: string;
    sent_at_ms: bigint;
    recipient: string;
    event_id: string;
    channel: string;
}
export interface Attendance {
    account_id: string;
    present: boolean;
    note: string;
    event_id: string;
}
export interface Event {
    id: string;
    title: string;
    creator: Principal;
    deleted: boolean;
    cancelled: boolean;
    series_id?: string;
    team_id?: string;
    description: string;
    starts_at_ms: bigint;
    ends_at_ms: bigint;
    revision: bigint;
    club_id: string;
    location?: string;
    event_type: string;
}
export interface LineupPlayer {
    x?: number;
    y?: number;
    member: string;
    slot: string;
    number?: number;
    bench: boolean;
}
export interface LineupEntry {
    member: string;
    slot: string;
    team_id?: string;
    event_id: string;
}
export interface EventGroupDuty {
    account_id?: string;
    duty: string;
    group_id: string;
}
export interface OpenDuty {
    id: string;
    claimed_by?: string;
    duty: string;
    created_at_ms: bigint;
    event_id: string;
}
export interface MiniLeagueRsvp {
    subject: RsvpSubject;
    updated_at_ms: bigint;
    state: string;
    event_id: string;
}
export interface EventAttendance {
    status: string;
    marked_by: Principal;
    subject_kind: string;
    marked_at_ms: bigint;
    subject_id: string;
    notes: string;
    event_id: string;
}
export interface AttendanceInput {
    status: string;
    subject_kind: string;
    subject_id: string;
    notes: string;
}
export interface CoachNote {
    updated_by: Principal;
    note: string;
    updated_at_ms: bigint;
    event_id: string;
}
export interface events_domainInterface {
    addBulkAccessPrincipal(principal: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    add_event_guest(event_id: string, guest_name: string): Promise<{
        __kind__: "Ok";
        Ok: EventGuest;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    add_group_player(group_id: string, account_id: string): Promise<{
        __kind__: "Ok";
        Ok: EventGroupPlayer;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    add_lineup(event_id: string, member: string, slot: string, team_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: LineupEntry;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    add_series_occurrence(series_id: string, starts_at_ms: bigint, ends_at_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    admin_link_guardian(child_id: string, guardian_id: string, is_primary: boolean): Promise<{
        __kind__: "Ok";
        Ok: ChildGuardian;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    admin_update_rsvp_status(event_id: string, account_id: string, child_id: string | null, status: string): Promise<{
        __kind__: "Ok";
        Ok: Rsvp;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    admin_upsert_child(id: string, name: string, parent_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: Child;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    admin_upsert_rsvp(event_id: string, account_id: string, child_id: string | null, status: string, notes: string): Promise<{
        __kind__: "Ok";
        Ok: Rsvp;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    child_is_in_event_audience(child_id: string, event_id: string): Promise<{
        __kind__: "Ok";
        Ok: boolean;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    claim_open_duty(id: string, account_id: string): Promise<{
        __kind__: "Ok";
        Ok: OpenDuty;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    complete_duty(event_id: string, account_id: string): Promise<{
        __kind__: "Ok";
        Ok: Duty;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_event(club_id: string, team_id: string | null, title: string, description: string, event_type: string, location: string | null, starts_at_ms: bigint, ends_at_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_event_group(event_id: string, name: string): Promise<{
        __kind__: "Ok";
        Ok: EventGroup;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_open_duty(event_id: string, duty: string): Promise<{
        __kind__: "Ok";
        Ok: OpenDuty;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_recurring_series(club_id: string, team_id: string | null, title: string, description: string, event_type: string, location: string | null, frequency: string, first_starts_at_ms: bigint, first_ends_at_ms: bigint, occurrences: number | null, until_ms: bigint | null): Promise<{
        __kind__: "Ok";
        Ok: {
            series: EventSeries;
            events: Array<Event>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_series(club_id: string, team_id: string | null, title: string, description: string, event_type: string, location: string | null, frequency: string, first_starts_at_ms: bigint, first_ends_at_ms: bigint, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: {
            series: EventSeries;
            events: Array<Event>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_team_training_pause(club_id: string, team_id: string, starts_at_ms: bigint, ends_at_ms: bigint, reason: string): Promise<{
        __kind__: "Ok";
        Ok: TeamTrainingPause;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    delete_event(id: string): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    delete_event_group(group_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    delete_series(id: string, from_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    delete_team_training_pause(id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    detach_occurrence(event_id: string): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    event_roster(event_id: string): Promise<{
        __kind__: "Ok";
        Ok: EventRoster;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    export_state(): Promise<{
        __kind__: "Ok";
        Ok: {
            lineups: Array<LineupEntry>;
            eventGuests: Array<EventGuest>;
            miniLeagueRsvps: Array<MiniLeagueRsvp>;
            teamTrainingPauses: Array<TeamTrainingPause>;
            eventAttendance: Array<EventAttendance>;
            schema: number;
            pushReachability: Array<PushReachability>;
            eventGroupPlayers: Array<EventGroupPlayer>;
            coachNotes: Array<CoachNote>;
            series: Array<EventSeries>;
            eventGroups: Array<EventGroup>;
            children: Array<Child>;
            recurrences: Array<Recurrence>;
            reminderLogs: Array<ReminderLog>;
            attendance: Array<Attendance>;
            events: Array<Event>;
            lineupSnapshots: Array<LineupSnapshot>;
            duties: Array<Duty>;
            governor: Principal;
            eventViews: Array<EventView>;
            roster: Array<RosterEntry>;
            eventGroupDuties: Array<EventGroupDuty>;
            childGuardians: Array<ChildGuardian>;
            roles: Array<RoleGrant>;
            rsvps: Array<Rsvp>;
            openDuties: Array<OpenDuty>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_attendance(event_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<EventAttendance>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_coach_note(event_id: string): Promise<{
        __kind__: "Ok";
        Ok: CoachNote | null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_event_roster(event_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<RosterEntry>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_event_view_count(event_id: string): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_lineup_snapshot(event_id: string, team_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: LineupSnapshot | null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_push_reachable(principal: Principal): Promise<{
        __kind__: "Ok";
        Ok: boolean | null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    grant_role(principal: Principal, role: string, club_id: string, team_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    initialize(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    is_guardian_of(principal: Principal, child_id: string): Promise<boolean>;
    is_paused(club_id: string, team_id: string, at_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: boolean;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    is_team_member(principal: Principal, club_id: string, team_id: string): Promise<boolean>;
    listBulkAccessPrincipals(): Promise<{
        __kind__: "Ok";
        Ok: Array<Principal>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_event_groups(event_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<EventGroup>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_events(club_id: string | null, team_id: string | null): Promise<Array<Event>>;
    list_group_duties(group_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<EventGroupDuty>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_group_players(group_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<EventGroupPlayer>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_mini_league_rsvps(event_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<MiniLeagueRsvp>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_open_duties(event_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<OpenDuty>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_reminders(event_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<ReminderLog>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_series(club_id: string | null, team_id: string | null): Promise<Array<EventSeries>>;
    list_team_training_pauses(club_id: string, team_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<TeamTrainingPause>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    mark_attendance(event_id: string, records: Array<AttendanceInput>): Promise<{
        __kind__: "Ok";
        Ok: Array<EventAttendance>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    move_group_player(from_group_id: string, to_group_id: string, account_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    my_attendance(event_id: string | null): Promise<Array<EventAttendance>>;
    my_child_rsvps(event_id: string | null, club_id: string | null): Promise<Array<RsvpWithChild>>;
    my_rsvps(): Promise<Array<Rsvp>>;
    record_event_view(event_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    record_reminder_sent(event_id: string, channel: string, recipient: string): Promise<{
        __kind__: "Ok";
        Ok: ReminderLog;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    removeBulkAccessPrincipal(principal: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    remove_duty(event_id: string, account_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    remove_event_guest(id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    remove_group_duty(group_id: string, duty: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    remove_group_player(group_id: string, account_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    rename_event_group(group_id: string, name: string): Promise<{
        __kind__: "Ok";
        Ok: EventGroup;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    save_lineup_snapshot(event_id: string, team_id: string | null, formation: string | null, team_size: number, ball_x: number | null, ball_y: number | null, players: Array<LineupPlayer>): Promise<{
        __kind__: "Ok";
        Ok: LineupSnapshot;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_attendance(event_id: string, account_id: string, present: boolean, note: string): Promise<{
        __kind__: "Ok";
        Ok: Attendance;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_coach_note(event_id: string, note: string): Promise<{
        __kind__: "Ok";
        Ok: CoachNote;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_duty(event_id: string, account_id: string, duty: string): Promise<{
        __kind__: "Ok";
        Ok: Duty;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_event_cancelled(id: string, cancelled: boolean): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_group_duty(group_id: string, duty: string, account_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: EventGroupDuty;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_mini_league_rsvp(event_id: string, subject: RsvpSubject, state: string): Promise<{
        __kind__: "Ok";
        Ok: MiniLeagueRsvp;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_push_reachable(reachable: boolean): Promise<{
        __kind__: "Ok";
        Ok: PushReachability;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_recurrence(event_id: string, frequency: string, until_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Recurrence;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_roster(event_id: string, account_id: string, child_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: RosterEntry;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_rsvp(event_id: string, account_id: string, state: string): Promise<{
        __kind__: "Ok";
        Ok: Rsvp;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    soft_delete_series(id: string): Promise<{
        __kind__: "Ok";
        Ok: EventSeries;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    swap_group_players(group_a: string, account_a: string, group_b: string, account_b: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    unclaim_open_duty(id: string): Promise<{
        __kind__: "Ok";
        Ok: OpenDuty;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    uncomplete_duty(event_id: string, account_id: string): Promise<{
        __kind__: "Ok";
        Ok: Duty;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    update_event(id: string, title: string, description: string, event_type: string, location: string | null, starts_at_ms: bigint, ends_at_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    update_series(id: string, title: string, description: string, event_type: string, location: string | null, from_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: EventSeries;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
}
import type { Attendance as _Attendance, Child as _Child, ChildGuardian as _ChildGuardian, CoachNote as _CoachNote, Duty as _Duty, Event as _Event, EventAttendance as _EventAttendance, EventGroup as _EventGroup, EventGroupDuty as _EventGroupDuty, EventGroupPlayer as _EventGroupPlayer, EventGuest as _EventGuest, EventRoster as _EventRoster, EventSeries as _EventSeries, EventView as _EventView, LineupEntry as _LineupEntry, LineupPlayer as _LineupPlayer, LineupSnapshot as _LineupSnapshot, MiniLeagueRsvp as _MiniLeagueRsvp, OpenDuty as _OpenDuty, PushReachability as _PushReachability, Recurrence as _Recurrence, ReminderLog as _ReminderLog, RoleGrant as _RoleGrant, RosterEntry as _RosterEntry, Rsvp as _Rsvp, RsvpSubject as _RsvpSubject, RsvpWithChild as _RsvpWithChild, TeamTrainingPause as _TeamTrainingPause } from "./declarations/events_domain.did";
export class Events_domain implements events_domainInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async addBulkAccessPrincipal(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.addBulkAccessPrincipal(arg0);
        return from_candid_variant_n1(result);
    }
    async add_event_guest(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: EventGuest;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.add_event_guest(arg0, arg1);
        return from_candid_variant_n2(result);
    }
    async add_group_player(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: EventGroupPlayer;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.add_group_player(arg0, arg1);
        return from_candid_variant_n3(result);
    }
    async add_lineup(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<{
        __kind__: "Ok";
        Ok: LineupEntry;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.add_lineup(arg0, arg1, arg2, to_candid_opt_n4(arg3));
        return from_candid_variant_n5(result);
    }
    async add_series_occurrence(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.add_series_occurrence(arg0, arg1, arg2);
        return from_candid_variant_n9(result);
    }
    async admin_link_guardian(arg0: string, arg1: string, arg2: boolean): Promise<{
        __kind__: "Ok";
        Ok: ChildGuardian;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.admin_link_guardian(arg0, arg1, arg2);
        return from_candid_variant_n12(result);
    }
    async admin_update_rsvp_status(arg0: string, arg1: string, arg2: string | null, arg3: string): Promise<{
        __kind__: "Ok";
        Ok: Rsvp;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.admin_update_rsvp_status(arg0, arg1, to_candid_opt_n4(arg2), arg3);
        return from_candid_variant_n13(result);
    }
    async admin_upsert_child(arg0: string, arg1: string, arg2: string | null): Promise<{
        __kind__: "Ok";
        Ok: Child;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.admin_upsert_child(arg0, arg1, to_candid_opt_n4(arg2));
        return from_candid_variant_n17(result);
    }
    async admin_upsert_rsvp(arg0: string, arg1: string, arg2: string | null, arg3: string, arg4: string): Promise<{
        __kind__: "Ok";
        Ok: Rsvp;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.admin_upsert_rsvp(arg0, arg1, to_candid_opt_n4(arg2), arg3, arg4);
        return from_candid_variant_n13(result);
    }
    async child_is_in_event_audience(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: boolean;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.child_is_in_event_audience(arg0, arg1);
        return from_candid_variant_n20(result);
    }
    async claim_open_duty(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: OpenDuty;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.claim_open_duty(arg0, arg1);
        return from_candid_variant_n21(result);
    }
    async complete_duty(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: Duty;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.complete_duty(arg0, arg1);
        return from_candid_variant_n24(result);
    }
    async create_event(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: string, arg5: string | null, arg6: bigint, arg7: bigint): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_event(arg0, to_candid_opt_n4(arg1), arg2, arg3, arg4, to_candid_opt_n4(arg5), arg6, arg7);
        return from_candid_variant_n9(result);
    }
    async create_event_group(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: EventGroup;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_event_group(arg0, arg1);
        return from_candid_variant_n25(result);
    }
    async create_open_duty(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: OpenDuty;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_open_duty(arg0, arg1);
        return from_candid_variant_n21(result);
    }
    async create_recurring_series(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: string, arg5: string | null, arg6: string, arg7: bigint, arg8: bigint, arg9: number | null, arg10: bigint | null): Promise<{
        __kind__: "Ok";
        Ok: {
            series: EventSeries;
            events: Array<Event>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_recurring_series(arg0, to_candid_opt_n4(arg1), arg2, arg3, arg4, to_candid_opt_n4(arg5), arg6, arg7, arg8, to_candid_opt_n26(arg9), to_candid_opt_n27(arg10));
        return from_candid_variant_n28(result);
    }
    async create_series(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: string, arg5: string | null, arg6: string, arg7: bigint, arg8: bigint, arg9: bigint): Promise<{
        __kind__: "Ok";
        Ok: {
            series: EventSeries;
            events: Array<Event>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_series(arg0, to_candid_opt_n4(arg1), arg2, arg3, arg4, to_candid_opt_n4(arg5), arg6, arg7, arg8, arg9);
        return from_candid_variant_n28(result);
    }
    async create_team_training_pause(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string): Promise<{
        __kind__: "Ok";
        Ok: TeamTrainingPause;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_team_training_pause(arg0, arg1, arg2, arg3, arg4);
        return from_candid_variant_n33(result);
    }
    async delete_event(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_event(arg0);
        return from_candid_variant_n9(result);
    }
    async delete_event_group(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_event_group(arg0);
        return from_candid_variant_n1(result);
    }
    async delete_series(arg0: string, arg1: bigint): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_series(arg0, arg1);
        return from_candid_variant_n34(result);
    }
    async delete_team_training_pause(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_team_training_pause(arg0);
        return from_candid_variant_n1(result);
    }
    async detach_occurrence(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.detach_occurrence(arg0);
        return from_candid_variant_n9(result);
    }
    async event_roster(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: EventRoster;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.event_roster(arg0);
        return from_candid_variant_n35(result);
    }
    async export_state(): Promise<{
        __kind__: "Ok";
        Ok: {
            lineups: Array<LineupEntry>;
            eventGuests: Array<EventGuest>;
            miniLeagueRsvps: Array<MiniLeagueRsvp>;
            teamTrainingPauses: Array<TeamTrainingPause>;
            eventAttendance: Array<EventAttendance>;
            schema: number;
            pushReachability: Array<PushReachability>;
            eventGroupPlayers: Array<EventGroupPlayer>;
            coachNotes: Array<CoachNote>;
            series: Array<EventSeries>;
            eventGroups: Array<EventGroup>;
            children: Array<Child>;
            recurrences: Array<Recurrence>;
            reminderLogs: Array<ReminderLog>;
            attendance: Array<Attendance>;
            events: Array<Event>;
            lineupSnapshots: Array<LineupSnapshot>;
            duties: Array<Duty>;
            governor: Principal;
            eventViews: Array<EventView>;
            roster: Array<RosterEntry>;
            eventGroupDuties: Array<EventGroupDuty>;
            childGuardians: Array<ChildGuardian>;
            roles: Array<RoleGrant>;
            rsvps: Array<Rsvp>;
            openDuties: Array<OpenDuty>;
        };
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.export_state();
        return from_candid_variant_n42(result);
    }
    async get_attendance(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<EventAttendance>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_attendance(arg0);
        return from_candid_variant_n71(result);
    }
    async get_coach_note(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: CoachNote | null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_coach_note(arg0);
        return from_candid_variant_n72(result);
    }
    async get_event_roster(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<RosterEntry>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_event_roster(arg0);
        return from_candid_variant_n74(result);
    }
    async get_event_view_count(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_event_view_count(arg0);
        return from_candid_variant_n34(result);
    }
    async get_lineup_snapshot(arg0: string, arg1: string | null): Promise<{
        __kind__: "Ok";
        Ok: LineupSnapshot | null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_lineup_snapshot(arg0, to_candid_opt_n4(arg1));
        return from_candid_variant_n75(result);
    }
    async get_push_reachable(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: boolean | null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_push_reachable(arg0);
        return from_candid_variant_n77(result);
    }
    async grant_role(arg0: Principal, arg1: string, arg2: string, arg3: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.grant_role(arg0, arg1, arg2, to_candid_opt_n4(arg3));
        return from_candid_variant_n1(result);
    }
    async initialize(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.initialize();
        return from_candid_variant_n1(result);
    }
    async is_guardian_of(arg0: Principal, arg1: string): Promise<boolean> {
        const result = await this.actor.is_guardian_of(arg0, arg1);
        return result;
    }
    async is_paused(arg0: string, arg1: string, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: boolean;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.is_paused(arg0, arg1, arg2);
        return from_candid_variant_n20(result);
    }
    async is_team_member(arg0: Principal, arg1: string, arg2: string): Promise<boolean> {
        const result = await this.actor.is_team_member(arg0, arg1, arg2);
        return result;
    }
    async listBulkAccessPrincipals(): Promise<{
        __kind__: "Ok";
        Ok: Array<Principal>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.listBulkAccessPrincipals();
        return from_candid_variant_n78(result);
    }
    async list_event_groups(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<EventGroup>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_event_groups(arg0);
        return from_candid_variant_n79(result);
    }
    async list_events(arg0: string | null, arg1: string | null): Promise<Array<Event>> {
        const result = await this.actor.list_events(to_candid_opt_n4(arg0), to_candid_opt_n4(arg1));
        return from_candid_vec_n32(result);
    }
    async list_group_duties(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<EventGroupDuty>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_group_duties(arg0);
        return from_candid_variant_n80(result);
    }
    async list_group_players(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<EventGroupPlayer>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_group_players(arg0);
        return from_candid_variant_n81(result);
    }
    async list_mini_league_rsvps(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<MiniLeagueRsvp>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_mini_league_rsvps(arg0);
        return from_candid_variant_n82(result);
    }
    async list_open_duties(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<OpenDuty>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_open_duties(arg0);
        return from_candid_variant_n83(result);
    }
    async list_reminders(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<ReminderLog>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_reminders(arg0);
        return from_candid_variant_n84(result);
    }
    async list_series(arg0: string | null, arg1: string | null): Promise<Array<EventSeries>> {
        const result = await this.actor.list_series(to_candid_opt_n4(arg0), to_candid_opt_n4(arg1));
        return from_candid_vec_n50(result);
    }
    async list_team_training_pauses(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: Array<TeamTrainingPause>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_team_training_pauses(arg0, arg1);
        return from_candid_variant_n85(result);
    }
    async mark_attendance(arg0: string, arg1: Array<AttendanceInput>): Promise<{
        __kind__: "Ok";
        Ok: Array<EventAttendance>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.mark_attendance(arg0, arg1);
        return from_candid_variant_n71(result);
    }
    async move_group_player(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.move_group_player(arg0, arg1, arg2);
        return from_candid_variant_n1(result);
    }
    async my_attendance(arg0: string | null): Promise<Array<EventAttendance>> {
        const result = await this.actor.my_attendance(to_candid_opt_n4(arg0));
        return result;
    }
    async my_child_rsvps(arg0: string | null, arg1: string | null): Promise<Array<RsvpWithChild>> {
        const result = await this.actor.my_child_rsvps(to_candid_opt_n4(arg0), to_candid_opt_n4(arg1));
        return from_candid_vec_n38(result);
    }
    async my_rsvps(): Promise<Array<Rsvp>> {
        const result = await this.actor.my_rsvps();
        return from_candid_vec_n69(result);
    }
    async record_event_view(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_event_view(arg0);
        return from_candid_variant_n1(result);
    }
    async record_reminder_sent(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "Ok";
        Ok: ReminderLog;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.record_reminder_sent(arg0, arg1, arg2);
        return from_candid_variant_n86(result);
    }
    async removeBulkAccessPrincipal(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.removeBulkAccessPrincipal(arg0);
        return from_candid_variant_n1(result);
    }
    async remove_duty(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.remove_duty(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async remove_event_guest(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.remove_event_guest(arg0);
        return from_candid_variant_n1(result);
    }
    async remove_group_duty(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.remove_group_duty(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async remove_group_player(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.remove_group_player(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async rename_event_group(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: EventGroup;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.rename_event_group(arg0, arg1);
        return from_candid_variant_n25(result);
    }
    async save_lineup_snapshot(arg0: string, arg1: string | null, arg2: string | null, arg3: number, arg4: number | null, arg5: number | null, arg6: Array<LineupPlayer>): Promise<{
        __kind__: "Ok";
        Ok: LineupSnapshot;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.save_lineup_snapshot(arg0, to_candid_opt_n4(arg1), to_candid_opt_n4(arg2), arg3, to_candid_opt_n87(arg4), to_candid_opt_n87(arg5), to_candid_vec_n88(arg6));
        return from_candid_variant_n91(result);
    }
    async set_attendance(arg0: string, arg1: string, arg2: boolean, arg3: string): Promise<{
        __kind__: "Ok";
        Ok: Attendance;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_attendance(arg0, arg1, arg2, arg3);
        return from_candid_variant_n92(result);
    }
    async set_coach_note(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: CoachNote;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_coach_note(arg0, arg1);
        return from_candid_variant_n93(result);
    }
    async set_duty(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "Ok";
        Ok: Duty;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_duty(arg0, arg1, arg2);
        return from_candid_variant_n24(result);
    }
    async set_event_cancelled(arg0: string, arg1: boolean): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_event_cancelled(arg0, arg1);
        return from_candid_variant_n9(result);
    }
    async set_group_duty(arg0: string, arg1: string, arg2: string | null): Promise<{
        __kind__: "Ok";
        Ok: EventGroupDuty;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_group_duty(arg0, arg1, to_candid_opt_n4(arg2));
        return from_candid_variant_n94(result);
    }
    async set_mini_league_rsvp(arg0: string, arg1: RsvpSubject, arg2: string): Promise<{
        __kind__: "Ok";
        Ok: MiniLeagueRsvp;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_mini_league_rsvp(arg0, to_candid_RsvpSubject_n95(arg1), arg2);
        return from_candid_variant_n97(result);
    }
    async set_push_reachable(arg0: boolean): Promise<{
        __kind__: "Ok";
        Ok: PushReachability;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_push_reachable(arg0);
        return from_candid_variant_n98(result);
    }
    async set_recurrence(arg0: string, arg1: string, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: Recurrence;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_recurrence(arg0, arg1, arg2);
        return from_candid_variant_n99(result);
    }
    async set_roster(arg0: string, arg1: string, arg2: string | null): Promise<{
        __kind__: "Ok";
        Ok: RosterEntry;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_roster(arg0, arg1, to_candid_opt_n4(arg2));
        return from_candid_variant_n100(result);
    }
    async set_rsvp(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "Ok";
        Ok: Rsvp;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_rsvp(arg0, arg1, arg2);
        return from_candid_variant_n13(result);
    }
    async soft_delete_series(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: EventSeries;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.soft_delete_series(arg0);
        return from_candid_variant_n101(result);
    }
    async swap_group_players(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.swap_group_players(arg0, arg1, arg2, arg3);
        return from_candid_variant_n1(result);
    }
    async unclaim_open_duty(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: OpenDuty;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.unclaim_open_duty(arg0);
        return from_candid_variant_n21(result);
    }
    async uncomplete_duty(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: Duty;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.uncomplete_duty(arg0, arg1);
        return from_candid_variant_n24(result);
    }
    async update_event(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: bigint, arg6: bigint): Promise<{
        __kind__: "Ok";
        Ok: Event;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.update_event(arg0, arg1, arg2, arg3, to_candid_opt_n4(arg4), arg5, arg6);
        return from_candid_variant_n9(result);
    }
    async update_series(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: bigint): Promise<{
        __kind__: "Ok";
        Ok: EventSeries;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.update_series(arg0, arg1, arg2, arg3, to_candid_opt_n4(arg4), arg5);
        return from_candid_variant_n101(result);
    }
}
function from_candid_Child_n18(value: _Child): Child {
    return from_candid_record_n19(value);
}
function from_candid_EventGroupDuty_n64(value: _EventGroupDuty): EventGroupDuty {
    return from_candid_record_n65(value);
}
function from_candid_EventRoster_n36(value: _EventRoster): EventRoster {
    return from_candid_record_n37(value);
}
function from_candid_EventSeries_n30(value: _EventSeries): EventSeries {
    return from_candid_record_n31(value);
}
function from_candid_Event_n10(value: _Event): Event {
    return from_candid_record_n11(value);
}
function from_candid_LineupEntry_n6(value: _LineupEntry): LineupEntry {
    return from_candid_record_n7(value);
}
function from_candid_LineupPlayer_n57(value: _LineupPlayer): LineupPlayer {
    return from_candid_record_n58(value);
}
function from_candid_LineupSnapshot_n53(value: _LineupSnapshot): LineupSnapshot {
    return from_candid_record_n54(value);
}
function from_candid_MiniLeagueRsvp_n46(value: _MiniLeagueRsvp): MiniLeagueRsvp {
    return from_candid_record_n47(value);
}
function from_candid_OpenDuty_n22(value: _OpenDuty): OpenDuty {
    return from_candid_record_n23(value);
}
function from_candid_RoleGrant_n67(value: _RoleGrant): RoleGrant {
    return from_candid_record_n68(value);
}
function from_candid_RosterEntry_n61(value: _RosterEntry): RosterEntry {
    return from_candid_record_n62(value);
}
function from_candid_RsvpSubject_n48(value: _RsvpSubject): RsvpSubject {
    return from_candid_variant_n49(value);
}
function from_candid_RsvpWithChild_n39(value: _RsvpWithChild): RsvpWithChild {
    return from_candid_record_n40(value);
}
function from_candid_Rsvp_n14(value: _Rsvp): Rsvp {
    return from_candid_record_n15(value);
}
function from_candid_opt_n16(value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(value: [] | [_Child]): Child | null {
    return value.length === 0 ? null : from_candid_Child_n18(value[0]);
}
function from_candid_opt_n55(value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n73(value: [] | [_CoachNote]): CoachNote | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n76(value: [] | [_LineupSnapshot]): LineupSnapshot | null {
    return value.length === 0 ? null : from_candid_LineupSnapshot_n53(value[0]);
}
function from_candid_opt_n8(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(value: {
    id: string;
    title: string;
    creator: Principal;
    deleted: boolean;
    cancelled: boolean;
    series_id: [] | [string];
    team_id: [] | [string];
    description: string;
    starts_at_ms: bigint;
    ends_at_ms: bigint;
    revision: bigint;
    club_id: string;
    location: [] | [string];
    event_type: string;
}): {
    id: string;
    title: string;
    creator: Principal;
    deleted: boolean;
    cancelled: boolean;
    series_id?: string;
    team_id?: string;
    description: string;
    starts_at_ms: bigint;
    ends_at_ms: bigint;
    revision: bigint;
    club_id: string;
    location?: string;
    event_type: string;
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        deleted: value.deleted,
        cancelled: value.cancelled,
        series_id: record_opt_to_undefined(from_candid_opt_n8(value.series_id)),
        team_id: record_opt_to_undefined(from_candid_opt_n8(value.team_id)),
        description: value.description,
        starts_at_ms: value.starts_at_ms,
        ends_at_ms: value.ends_at_ms,
        revision: value.revision,
        club_id: value.club_id,
        location: record_opt_to_undefined(from_candid_opt_n8(value.location)),
        event_type: value.event_type
    };
}
function from_candid_record_n15(value: {
    account_id: string;
    source: string;
    updated_at_ms: bigint;
    child_id: [] | [string];
    state: string;
    notes: string;
    event_id: string;
    has_paid: [] | [boolean];
}): {
    account_id: string;
    source: string;
    updated_at_ms: bigint;
    child_id?: string;
    state: string;
    notes: string;
    event_id: string;
    has_paid?: boolean;
} {
    return {
        account_id: value.account_id,
        source: value.source,
        updated_at_ms: value.updated_at_ms,
        child_id: record_opt_to_undefined(from_candid_opt_n8(value.child_id)),
        state: value.state,
        notes: value.notes,
        event_id: value.event_id,
        has_paid: record_opt_to_undefined(from_candid_opt_n16(value.has_paid))
    };
}
function from_candid_record_n19(value: {
    id: string;
    name: string;
    parent_id: [] | [string];
}): {
    id: string;
    name: string;
    parent_id?: string;
} {
    return {
        id: value.id,
        name: value.name,
        parent_id: record_opt_to_undefined(from_candid_opt_n8(value.parent_id))
    };
}
function from_candid_record_n23(value: {
    id: string;
    claimed_by: [] | [string];
    duty: string;
    created_at_ms: bigint;
    event_id: string;
}): {
    id: string;
    claimed_by?: string;
    duty: string;
    created_at_ms: bigint;
    event_id: string;
} {
    return {
        id: value.id,
        claimed_by: record_opt_to_undefined(from_candid_opt_n8(value.claimed_by)),
        duty: value.duty,
        created_at_ms: value.created_at_ms,
        event_id: value.event_id
    };
}
function from_candid_record_n29(value: {
    series: _EventSeries;
    events: Array<_Event>;
}): {
    series: EventSeries;
    events: Array<Event>;
} {
    return {
        series: from_candid_EventSeries_n30(value.series),
        events: from_candid_vec_n32(value.events)
    };
}
function from_candid_record_n31(value: {
    id: string;
    title: string;
    creator: Principal;
    deleted: boolean;
    until_ms: bigint;
    first_starts_at_ms: bigint;
    team_id: [] | [string];
    description: string;
    frequency: string;
    first_ends_at_ms: bigint;
    revision: bigint;
    club_id: string;
    location: [] | [string];
    event_type: string;
}): {
    id: string;
    title: string;
    creator: Principal;
    deleted: boolean;
    until_ms: bigint;
    first_starts_at_ms: bigint;
    team_id?: string;
    description: string;
    frequency: string;
    first_ends_at_ms: bigint;
    revision: bigint;
    club_id: string;
    location?: string;
    event_type: string;
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        deleted: value.deleted,
        until_ms: value.until_ms,
        first_starts_at_ms: value.first_starts_at_ms,
        team_id: record_opt_to_undefined(from_candid_opt_n8(value.team_id)),
        description: value.description,
        frequency: value.frequency,
        first_ends_at_ms: value.first_ends_at_ms,
        revision: value.revision,
        club_id: value.club_id,
        location: record_opt_to_undefined(from_candid_opt_n8(value.location)),
        event_type: value.event_type
    };
}
function from_candid_record_n37(value: {
    guests: Array<_EventGuest>;
    rsvps: Array<_RsvpWithChild>;
}): {
    guests: Array<EventGuest>;
    rsvps: Array<RsvpWithChild>;
} {
    return {
        guests: value.guests,
        rsvps: from_candid_vec_n38(value.rsvps)
    };
}
function from_candid_record_n40(value: {
    child: [] | [_Child];
    rsvp: _Rsvp;
}): {
    child?: Child;
    rsvp: Rsvp;
} {
    return {
        child: record_opt_to_undefined(from_candid_opt_n41(value.child)),
        rsvp: from_candid_Rsvp_n14(value.rsvp)
    };
}
function from_candid_record_n43(value: {
    lineups: Array<_LineupEntry>;
    eventGuests: Array<_EventGuest>;
    miniLeagueRsvps: Array<_MiniLeagueRsvp>;
    teamTrainingPauses: Array<_TeamTrainingPause>;
    eventAttendance: Array<_EventAttendance>;
    schema: number;
    pushReachability: Array<_PushReachability>;
    eventGroupPlayers: Array<_EventGroupPlayer>;
    coachNotes: Array<_CoachNote>;
    series: Array<_EventSeries>;
    eventGroups: Array<_EventGroup>;
    children: Array<_Child>;
    recurrences: Array<_Recurrence>;
    reminderLogs: Array<_ReminderLog>;
    attendance: Array<_Attendance>;
    events: Array<_Event>;
    lineupSnapshots: Array<_LineupSnapshot>;
    duties: Array<_Duty>;
    governor: Principal;
    eventViews: Array<_EventView>;
    roster: Array<_RosterEntry>;
    eventGroupDuties: Array<_EventGroupDuty>;
    childGuardians: Array<_ChildGuardian>;
    roles: Array<_RoleGrant>;
    rsvps: Array<_Rsvp>;
    openDuties: Array<_OpenDuty>;
}): {
    lineups: Array<LineupEntry>;
    eventGuests: Array<EventGuest>;
    miniLeagueRsvps: Array<MiniLeagueRsvp>;
    teamTrainingPauses: Array<TeamTrainingPause>;
    eventAttendance: Array<EventAttendance>;
    schema: number;
    pushReachability: Array<PushReachability>;
    eventGroupPlayers: Array<EventGroupPlayer>;
    coachNotes: Array<CoachNote>;
    series: Array<EventSeries>;
    eventGroups: Array<EventGroup>;
    children: Array<Child>;
    recurrences: Array<Recurrence>;
    reminderLogs: Array<ReminderLog>;
    attendance: Array<Attendance>;
    events: Array<Event>;
    lineupSnapshots: Array<LineupSnapshot>;
    duties: Array<Duty>;
    governor: Principal;
    eventViews: Array<EventView>;
    roster: Array<RosterEntry>;
    eventGroupDuties: Array<EventGroupDuty>;
    childGuardians: Array<ChildGuardian>;
    roles: Array<RoleGrant>;
    rsvps: Array<Rsvp>;
    openDuties: Array<OpenDuty>;
} {
    return {
        lineups: from_candid_vec_n44(value.lineups),
        eventGuests: value.eventGuests,
        miniLeagueRsvps: from_candid_vec_n45(value.miniLeagueRsvps),
        teamTrainingPauses: value.teamTrainingPauses,
        eventAttendance: value.eventAttendance,
        schema: value.schema,
        pushReachability: value.pushReachability,
        eventGroupPlayers: value.eventGroupPlayers,
        coachNotes: value.coachNotes,
        series: from_candid_vec_n50(value.series),
        eventGroups: value.eventGroups,
        children: from_candid_vec_n51(value.children),
        recurrences: value.recurrences,
        reminderLogs: value.reminderLogs,
        attendance: value.attendance,
        events: from_candid_vec_n32(value.events),
        lineupSnapshots: from_candid_vec_n52(value.lineupSnapshots),
        duties: value.duties,
        governor: value.governor,
        eventViews: value.eventViews,
        roster: from_candid_vec_n60(value.roster),
        eventGroupDuties: from_candid_vec_n63(value.eventGroupDuties),
        childGuardians: value.childGuardians,
        roles: from_candid_vec_n66(value.roles),
        rsvps: from_candid_vec_n69(value.rsvps),
        openDuties: from_candid_vec_n70(value.openDuties)
    };
}
function from_candid_record_n47(value: {
    subject: _RsvpSubject;
    updated_at_ms: bigint;
    state: string;
    event_id: string;
}): {
    subject: RsvpSubject;
    updated_at_ms: bigint;
    state: string;
    event_id: string;
} {
    return {
        subject: from_candid_RsvpSubject_n48(value.subject),
        updated_at_ms: value.updated_at_ms,
        state: value.state,
        event_id: value.event_id
    };
}
function from_candid_record_n54(value: {
    updated_by: Principal;
    formation: [] | [string];
    ball_x: [] | [number];
    ball_y: [] | [number];
    team_id: [] | [string];
    updated_at_ms: bigint;
    team_size: number;
    players: Array<_LineupPlayer>;
    event_id: string;
    revision: bigint;
}): {
    updated_by: Principal;
    formation?: string;
    ball_x?: number;
    ball_y?: number;
    team_id?: string;
    updated_at_ms: bigint;
    team_size: number;
    players: Array<LineupPlayer>;
    event_id: string;
    revision: bigint;
} {
    return {
        updated_by: value.updated_by,
        formation: record_opt_to_undefined(from_candid_opt_n8(value.formation)),
        ball_x: record_opt_to_undefined(from_candid_opt_n55(value.ball_x)),
        ball_y: record_opt_to_undefined(from_candid_opt_n55(value.ball_y)),
        team_id: record_opt_to_undefined(from_candid_opt_n8(value.team_id)),
        updated_at_ms: value.updated_at_ms,
        team_size: value.team_size,
        players: from_candid_vec_n56(value.players),
        event_id: value.event_id,
        revision: value.revision
    };
}
function from_candid_record_n58(value: {
    x: [] | [number];
    y: [] | [number];
    member: string;
    slot: string;
    number: [] | [number];
    bench: boolean;
}): {
    x?: number;
    y?: number;
    member: string;
    slot: string;
    number?: number;
    bench: boolean;
} {
    return {
        x: record_opt_to_undefined(from_candid_opt_n55(value.x)),
        y: record_opt_to_undefined(from_candid_opt_n55(value.y)),
        member: value.member,
        slot: value.slot,
        number: record_opt_to_undefined(from_candid_opt_n59(value.number)),
        bench: value.bench
    };
}
function from_candid_record_n62(value: {
    account_id: string;
    child_id: [] | [string];
    event_id: string;
}): {
    account_id: string;
    child_id?: string;
    event_id: string;
} {
    return {
        account_id: value.account_id,
        child_id: record_opt_to_undefined(from_candid_opt_n8(value.child_id)),
        event_id: value.event_id
    };
}
function from_candid_record_n65(value: {
    account_id: [] | [string];
    duty: string;
    group_id: string;
}): {
    account_id?: string;
    duty: string;
    group_id: string;
} {
    return {
        account_id: record_opt_to_undefined(from_candid_opt_n8(value.account_id)),
        duty: value.duty,
        group_id: value.group_id
    };
}
function from_candid_record_n68(value: {
    role: string;
    user: Principal;
    team_id: [] | [string];
    club_id: string;
}): {
    role: string;
    user: Principal;
    team_id?: string;
    club_id: string;
} {
    return {
        role: value.role,
        user: value.user,
        team_id: record_opt_to_undefined(from_candid_opt_n8(value.team_id)),
        club_id: value.club_id
    };
}
function from_candid_record_n7(value: {
    member: string;
    slot: string;
    team_id: [] | [string];
    event_id: string;
}): {
    member: string;
    slot: string;
    team_id?: string;
    event_id: string;
} {
    return {
        member: value.member,
        slot: value.slot,
        team_id: record_opt_to_undefined(from_candid_opt_n8(value.team_id)),
        event_id: value.event_id
    };
}
function from_candid_variant_n1(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n100(value: {
    Ok: _RosterEntry;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: RosterEntry;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_RosterEntry_n61(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n101(value: {
    Ok: _EventSeries;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: EventSeries;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_EventSeries_n30(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n12(value: {
    Ok: _ChildGuardian;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ChildGuardian;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n13(value: {
    Ok: _Rsvp;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Rsvp;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Rsvp_n14(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n17(value: {
    Ok: _Child;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Child;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Child_n18(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: _EventGuest;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: EventGuest;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n20(value: {
    Ok: boolean;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: boolean;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n21(value: {
    Ok: _OpenDuty;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: OpenDuty;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_OpenDuty_n22(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n24(value: {
    Ok: _Duty;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Duty;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n25(value: {
    Ok: _EventGroup;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: EventGroup;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n28(value: {
    Ok: {
        series: _EventSeries;
        events: Array<_Event>;
    };
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: {
        series: EventSeries;
        events: Array<Event>;
    };
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_record_n29(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n3(value: {
    Ok: _EventGroupPlayer;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: EventGroupPlayer;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n33(value: {
    Ok: _TeamTrainingPause;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: TeamTrainingPause;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n34(value: {
    Ok: number;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: number;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n35(value: {
    Ok: _EventRoster;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: EventRoster;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_EventRoster_n36(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n42(value: {
    Ok: {
        lineups: Array<_LineupEntry>;
        eventGuests: Array<_EventGuest>;
        miniLeagueRsvps: Array<_MiniLeagueRsvp>;
        teamTrainingPauses: Array<_TeamTrainingPause>;
        eventAttendance: Array<_EventAttendance>;
        schema: number;
        pushReachability: Array<_PushReachability>;
        eventGroupPlayers: Array<_EventGroupPlayer>;
        coachNotes: Array<_CoachNote>;
        series: Array<_EventSeries>;
        eventGroups: Array<_EventGroup>;
        children: Array<_Child>;
        recurrences: Array<_Recurrence>;
        reminderLogs: Array<_ReminderLog>;
        attendance: Array<_Attendance>;
        events: Array<_Event>;
        lineupSnapshots: Array<_LineupSnapshot>;
        duties: Array<_Duty>;
        governor: Principal;
        eventViews: Array<_EventView>;
        roster: Array<_RosterEntry>;
        eventGroupDuties: Array<_EventGroupDuty>;
        childGuardians: Array<_ChildGuardian>;
        roles: Array<_RoleGrant>;
        rsvps: Array<_Rsvp>;
        openDuties: Array<_OpenDuty>;
    };
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: {
        lineups: Array<LineupEntry>;
        eventGuests: Array<EventGuest>;
        miniLeagueRsvps: Array<MiniLeagueRsvp>;
        teamTrainingPauses: Array<TeamTrainingPause>;
        eventAttendance: Array<EventAttendance>;
        schema: number;
        pushReachability: Array<PushReachability>;
        eventGroupPlayers: Array<EventGroupPlayer>;
        coachNotes: Array<CoachNote>;
        series: Array<EventSeries>;
        eventGroups: Array<EventGroup>;
        children: Array<Child>;
        recurrences: Array<Recurrence>;
        reminderLogs: Array<ReminderLog>;
        attendance: Array<Attendance>;
        events: Array<Event>;
        lineupSnapshots: Array<LineupSnapshot>;
        duties: Array<Duty>;
        governor: Principal;
        eventViews: Array<EventView>;
        roster: Array<RosterEntry>;
        eventGroupDuties: Array<EventGroupDuty>;
        childGuardians: Array<ChildGuardian>;
        roles: Array<RoleGrant>;
        rsvps: Array<Rsvp>;
        openDuties: Array<OpenDuty>;
    };
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_record_n43(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n49(value: {
    account: string;
} | {
    mini_league_player: string;
}): {
    __kind__: "account";
    account: string;
} | {
    __kind__: "mini_league_player";
    mini_league_player: string;
} {
    return "account" in value ? {
        __kind__: "account",
        account: value.account
    } : "mini_league_player" in value ? {
        __kind__: "mini_league_player",
        mini_league_player: value.mini_league_player
    } : value;
}
function from_candid_variant_n5(value: {
    Ok: _LineupEntry;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: LineupEntry;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_LineupEntry_n6(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n71(value: {
    Ok: Array<_EventAttendance>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<EventAttendance>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n72(value: {
    Ok: [] | [_CoachNote];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: CoachNote | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n73(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n74(value: {
    Ok: Array<_RosterEntry>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<RosterEntry>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n60(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n75(value: {
    Ok: [] | [_LineupSnapshot];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: LineupSnapshot | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n76(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n77(value: {
    Ok: [] | [boolean];
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: boolean | null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_opt_n16(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n78(value: {
    Ok: Array<Principal>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<Principal>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n79(value: {
    Ok: Array<_EventGroup>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<EventGroup>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n80(value: {
    Ok: Array<_EventGroupDuty>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<EventGroupDuty>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n63(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n81(value: {
    Ok: Array<_EventGroupPlayer>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<EventGroupPlayer>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n82(value: {
    Ok: Array<_MiniLeagueRsvp>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<MiniLeagueRsvp>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n45(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n83(value: {
    Ok: Array<_OpenDuty>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<OpenDuty>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n70(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n84(value: {
    Ok: Array<_ReminderLog>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<ReminderLog>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n85(value: {
    Ok: Array<_TeamTrainingPause>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<TeamTrainingPause>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n86(value: {
    Ok: _ReminderLog;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ReminderLog;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n9(value: {
    Ok: _Event;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Event;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Event_n10(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n91(value: {
    Ok: _LineupSnapshot;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: LineupSnapshot;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_LineupSnapshot_n53(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n92(value: {
    Ok: _Attendance;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Attendance;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n93(value: {
    Ok: _CoachNote;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: CoachNote;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n94(value: {
    Ok: _EventGroupDuty;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: EventGroupDuty;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_EventGroupDuty_n64(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n97(value: {
    Ok: _MiniLeagueRsvp;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: MiniLeagueRsvp;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_MiniLeagueRsvp_n46(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n98(value: {
    Ok: _PushReachability;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: PushReachability;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n99(value: {
    Ok: _Recurrence;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Recurrence;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n32(value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n10(x));
}
function from_candid_vec_n38(value: Array<_RsvpWithChild>): Array<RsvpWithChild> {
    return value.map((x)=>from_candid_RsvpWithChild_n39(x));
}
function from_candid_vec_n44(value: Array<_LineupEntry>): Array<LineupEntry> {
    return value.map((x)=>from_candid_LineupEntry_n6(x));
}
function from_candid_vec_n45(value: Array<_MiniLeagueRsvp>): Array<MiniLeagueRsvp> {
    return value.map((x)=>from_candid_MiniLeagueRsvp_n46(x));
}
function from_candid_vec_n50(value: Array<_EventSeries>): Array<EventSeries> {
    return value.map((x)=>from_candid_EventSeries_n30(x));
}
function from_candid_vec_n51(value: Array<_Child>): Array<Child> {
    return value.map((x)=>from_candid_Child_n18(x));
}
function from_candid_vec_n52(value: Array<_LineupSnapshot>): Array<LineupSnapshot> {
    return value.map((x)=>from_candid_LineupSnapshot_n53(x));
}
function from_candid_vec_n56(value: Array<_LineupPlayer>): Array<LineupPlayer> {
    return value.map((x)=>from_candid_LineupPlayer_n57(x));
}
function from_candid_vec_n60(value: Array<_RosterEntry>): Array<RosterEntry> {
    return value.map((x)=>from_candid_RosterEntry_n61(x));
}
function from_candid_vec_n63(value: Array<_EventGroupDuty>): Array<EventGroupDuty> {
    return value.map((x)=>from_candid_EventGroupDuty_n64(x));
}
function from_candid_vec_n66(value: Array<_RoleGrant>): Array<RoleGrant> {
    return value.map((x)=>from_candid_RoleGrant_n67(x));
}
function from_candid_vec_n69(value: Array<_Rsvp>): Array<Rsvp> {
    return value.map((x)=>from_candid_Rsvp_n14(x));
}
function from_candid_vec_n70(value: Array<_OpenDuty>): Array<OpenDuty> {
    return value.map((x)=>from_candid_OpenDuty_n22(x));
}
function to_candid_LineupPlayer_n89(value: LineupPlayer): _LineupPlayer {
    return to_candid_record_n90(value);
}
function to_candid_RsvpSubject_n95(value: RsvpSubject): _RsvpSubject {
    return to_candid_variant_n96(value);
}
function to_candid_opt_n26(value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n27(value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n87(value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n90(value: {
    x?: number;
    y?: number;
    member: string;
    slot: string;
    number?: number;
    bench: boolean;
}): {
    x: [] | [number];
    y: [] | [number];
    member: string;
    slot: string;
    number: [] | [number];
    bench: boolean;
} {
    return {
        x: value.x ? candid_some(value.x) : candid_none(),
        y: value.y ? candid_some(value.y) : candid_none(),
        member: value.member,
        slot: value.slot,
        number: value.number ? candid_some(value.number) : candid_none(),
        bench: value.bench
    };
}
function to_candid_variant_n96(value: {
    __kind__: "account";
    account: string;
} | {
    __kind__: "mini_league_player";
    mini_league_player: string;
}): {
    account: string;
} | {
    mini_league_player: string;
} {
    return value.__kind__ === "account" ? {
        account: value.account
    } : value.__kind__ === "mini_league_player" ? {
        mini_league_player: value.mini_league_player
    } : value;
}
function to_candid_vec_n88(value: Array<LineupPlayer>): Array<_LineupPlayer> {
    return value.map((x)=>to_candid_LineupPlayer_n89(x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Events_domain {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Events_domain(actor);
}
