import Array "mo:core/Array";
import Principal "mo:core/Principal";
module {
  type RoleGrant = { user : Principal; role : Text; club_id : Text; team_id : ?Text };
  type Event = { id : Text; club_id : Text; team_id : ?Text; title : Text; description : Text; event_type : Text; location : ?Text; cancelled : Bool; creator : Principal; starts_at_ms : Nat64; ends_at_ms : Nat64; series_id : ?Text; revision : Nat64; deleted : Bool };
  type Rsvp = { event_id : Text; account_id : Text; child_id : ?Text; state : Text; notes : Text; has_paid : ?Bool; source : Text; updated_at_ms : Nat64 };
  type Attendance = { event_id : Text; account_id : Text; present : Bool; note : Text };
  type LineupEntry = { event_id : Text; member : Text; slot : Text; team_id : ?Text };
  type LineupPlayer = { member : Text; slot : Text; number : ?Nat16; x : ?Float; y : ?Float; bench : Bool };
  type LineupSnapshot = { event_id : Text; team_id : ?Text; formation : ?Text; team_size : Nat16; ball_x : ?Float; ball_y : ?Float; players : [LineupPlayer]; updated_by : Principal; updated_at_ms : Nat64; revision : Nat64 };
  type Duty = { event_id : Text; account_id : Text; duty : Text; completed : Bool };
  type RosterEntry = { event_id : Text; account_id : Text; child_id : ?Text };
  type Recurrence = { event_id : Text; frequency : Text; until_ms : Nat64 };
  type EventSeries = { id : Text; club_id : Text; team_id : ?Text; title : Text; description : Text; event_type : Text; location : ?Text; frequency : Text; first_starts_at_ms : Nat64; first_ends_at_ms : Nat64; until_ms : Nat64; creator : Principal; revision : Nat64; deleted : Bool };
  type EventAttendance = { event_id : Text; subject_id : Text; subject_kind : Text; status : Text; marked_by : Principal; marked_at_ms : Nat64; notes : Text };
  type EventGuest = { id : Text; event_id : Text; guest_name : Text; added_by : Principal; created_at_ms : Nat64 };
  type Child = { id : Text; name : Text; parent_id : ?Text };
  type ChildGuardian = { child_id : Text; guardian_id : Text; is_primary : Bool };
  type CoachNote = { event_id : Text; note : Text; updated_by : Principal; updated_at_ms : Nat64 };
  type EventView = { event_id : Text; viewer : Principal; viewed_at_ms : Nat64 };
  type ReminderLog = { id : Text; event_id : Text; channel : Text; recipient : Text; sent_at_ms : Nat64 };
  type PushReachability = { user : Principal; reachable : Bool; updated_at_ms : Nat64 };
  type EventGroup = { id : Text; event_id : Text; name : Text; created_at_ms : Nat64; team_letter : ?Text; colour : ?Text; ability_band : ?Text; pitch_name : ?Text };
  type EventGroupPlayer = { group_id : Text; account_id : Text; team_letter : ?Text };
  type EventGroupDuty = { group_id : Text; duty : Text; account_id : ?Text };
  type TeamTrainingPause = { id : Text; club_id : Text; team_id : Text; starts_at_ms : Nat64; ends_at_ms : Nat64; reason : Text; created_by : Principal; created_at_ms : Nat64 };
  type OpenDuty = { id : Text; event_id : Text; duty : Text; claimed_by : ?Text; created_at_ms : Nat64 };
  type RsvpSubject = { #account : Text; #mini_league_player : Text };
  type MiniLeagueRsvp = { event_id : Text; subject : RsvpSubject; state : Text; updated_at_ms : Nat64 };
  type AssociationEvent = { id : Text; association_id : Text; title : Text; description : Text; location : ?Text; starts_at_ms : Nat64; ends_at_ms : Nat64; created_by : Principal; created_at_ms : Nat64; child_event_ids : [Text]; deleted : Bool };

  type OldActor = {
    var governor : Principal;
    var roles : [RoleGrant];
    var events : [Event];
    var rsvps : [Rsvp];
    var attendance : [Attendance];
    var lineups : [LineupEntry];
    var lineupSnapshots : [LineupSnapshot];
    var duties : [Duty];
    var roster : [RosterEntry];
    var recurrences : [Recurrence];
    var series : [EventSeries];
    var eventAttendance : [EventAttendance];
    var eventGuests : [EventGuest];
    var children : [Child];
    var childGuardians : [ChildGuardian];
    var bulkAccessPrincipals : [Principal];
    var coachNotes : [CoachNote];
    var eventViews : [EventView];
    var reminderLogs : [ReminderLog];
    var pushReachability : [PushReachability];
    var eventGroups : [EventGroup];
    var eventGroupPlayers : [EventGroupPlayer];
    var eventGroupDuties : [EventGroupDuty];
    var teamTrainingPauses : [TeamTrainingPause];
    var openDuties : [OpenDuty];
    var miniLeagueRsvps : [MiniLeagueRsvp];
  };
  type NewActor = {
    var governor : Principal;
    var roles : [RoleGrant];
    var events : [Event];
    var rsvps : [Rsvp];
    var attendance : [Attendance];
    var lineups : [LineupEntry];
    var lineupSnapshots : [LineupSnapshot];
    var duties : [Duty];
    var roster : [RosterEntry];
    var recurrences : [Recurrence];
    var series : [EventSeries];
    var eventAttendance : [EventAttendance];
    var eventGuests : [EventGuest];
    var children : [Child];
    var childGuardians : [ChildGuardian];
    var bulkAccessPrincipals : [Principal];
    var coachNotes : [CoachNote];
    var eventViews : [EventView];
    var reminderLogs : [ReminderLog];
    var pushReachability : [PushReachability];
    var eventGroups : [EventGroup];
    var eventGroupPlayers : [EventGroupPlayer];
    var eventGroupDuties : [EventGroupDuty];
    var teamTrainingPauses : [TeamTrainingPause];
    var openDuties : [OpenDuty];
    var miniLeagueRsvps : [MiniLeagueRsvp];
    var associationEvents : [AssociationEvent];
  };
  // Phase 3 of the NEEDS-CANISTER completion plan: adds the empty
  // associationEvents store (association-scoped event fan-out parents).
  // All existing state is preserved verbatim.
  public func migration(old : OldActor) : NewActor {
    {
      var governor = old.governor;
      var roles = old.roles;
      var events = old.events;
      var rsvps = old.rsvps;
      var attendance = old.attendance;
      var lineups = old.lineups;
      var lineupSnapshots = old.lineupSnapshots;
      var duties = old.duties;
      var roster = old.roster;
      var recurrences = old.recurrences;
      var series = old.series;
      var eventAttendance = old.eventAttendance;
      var eventGuests = old.eventGuests;
      var children = old.children;
      var childGuardians = old.childGuardians;
      var bulkAccessPrincipals = old.bulkAccessPrincipals;
      var coachNotes = old.coachNotes;
      var eventViews = old.eventViews;
      var reminderLogs = old.reminderLogs;
      var pushReachability = old.pushReachability;
      var eventGroups = old.eventGroups;
      var eventGroupPlayers = old.eventGroupPlayers;
      var eventGroupDuties = old.eventGroupDuties;
      var teamTrainingPauses = old.teamTrainingPauses;
      var openDuties = old.openDuties;
      var miniLeagueRsvps = old.miniLeagueRsvps;
      var associationEvents = [];
    }
  };
};
