/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/vault_domain.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface VaultFile {
    id: string;
    club: string;
    mime: string;
    name: string;
    size: bigint;
    team?: string;
    file_url: string;
    created_at_ms: bigint;
    blob_ref?: BlobRef;
    folder_id: string;
    is_external_link: boolean;
    deleted_at_ms?: bigint;
    uploaded_by: Principal;
}
export type FolderResult = {
    __kind__: "Ok";
    Ok: VaultFolder;
} | {
    __kind__: "Err";
    Err: string;
};
export type FoldersResult = {
    __kind__: "Ok";
    Ok: Array<VaultFolder>;
} | {
    __kind__: "Err";
    Err: string;
};
export interface VaultFolder {
    id: string;
    club: string;
    name: string;
    team?: string;
    restricted_roles: Array<string>;
    created_by: Principal;
    created_at_ms: bigint;
    parent_id?: string;
    deleted_at_ms?: bigint;
}
export interface BlobRef {
    path: string;
    content_hash: string;
    canister: string;
}
export type FileResult = {
    __kind__: "Ok";
    Ok: VaultFile;
} | {
    __kind__: "Err";
    Err: string;
};
export type FilesResult = {
    __kind__: "Ok";
    Ok: Array<VaultFile>;
} | {
    __kind__: "Err";
    Err: string;
};
export interface vault_domainInterface {
    create_folder(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string, arg5: Array<string>): Promise<FolderResult>;
    delete_folder(arg0: string): Promise<FolderResult>;
    grant_role(arg0: Principal, arg1: string, arg2: string | null, arg3: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    initialize(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_club_files(arg0: string, arg1: string | null): Promise<FilesResult>;
    list_files(arg0: string): Promise<FilesResult>;
    list_folders(arg0: string, arg1: string | null): Promise<FoldersResult>;
    list_trashed_files(arg0: string): Promise<FilesResult>;
    register_file(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: string, arg6: bigint, arg7: string, arg8: boolean, arg9: BlobRef | null): Promise<FileResult>;
    restore_file(arg0: string): Promise<FileResult>;
    trash_file(arg0: string): Promise<FileResult>;
    update_folder(arg0: string, arg1: string, arg2: Array<string>): Promise<FolderResult>;
}
import type { BlobRef as _BlobRef, FileResult as _FileResult, FilesResult as _FilesResult, FolderResult as _FolderResult, FoldersResult as _FoldersResult, VaultFile as _VaultFile, VaultFolder as _VaultFolder } from "./declarations/vault_domain.did";
export class Vault_domain implements vault_domainInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async create_folder(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string, arg5: Array<string>): Promise<FolderResult> {
        const result = await this.actor.create_folder(arg0, arg1, to_candid_opt_n1(arg2), to_candid_opt_n1(arg3), arg4, arg5);
        return from_candid_FolderResult_n2(result);
    }
    async delete_folder(arg0: string): Promise<FolderResult> {
        const result = await this.actor.delete_folder(arg0);
        return from_candid_FolderResult_n2(result);
    }
    async grant_role(arg0: Principal, arg1: string, arg2: string | null, arg3: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.grant_role(arg0, arg1, to_candid_opt_n1(arg2), to_candid_opt_n1(arg3));
        return from_candid_variant_n8(result);
    }
    async initialize(): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.initialize();
        return from_candid_variant_n8(result);
    }
    async list_club_files(arg0: string, arg1: string | null): Promise<FilesResult> {
        const result = await this.actor.list_club_files(arg0, to_candid_opt_n1(arg1));
        return from_candid_FilesResult_n9(result);
    }
    async list_files(arg0: string): Promise<FilesResult> {
        const result = await this.actor.list_files(arg0);
        return from_candid_FilesResult_n9(result);
    }
    async list_folders(arg0: string, arg1: string | null): Promise<FoldersResult> {
        const result = await this.actor.list_folders(arg0, to_candid_opt_n1(arg1));
        return from_candid_FoldersResult_n15(result);
    }
    async list_trashed_files(arg0: string): Promise<FilesResult> {
        const result = await this.actor.list_trashed_files(arg0);
        return from_candid_FilesResult_n9(result);
    }
    async register_file(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: string, arg6: bigint, arg7: string, arg8: boolean, arg9: BlobRef | null): Promise<FileResult> {
        const result = await this.actor.register_file(arg0, arg1, arg2, to_candid_opt_n1(arg3), arg4, arg5, arg6, arg7, arg8, to_candid_opt_n18(arg9));
        return from_candid_FileResult_n19(result);
    }
    async restore_file(arg0: string): Promise<FileResult> {
        const result = await this.actor.restore_file(arg0);
        return from_candid_FileResult_n19(result);
    }
    async trash_file(arg0: string): Promise<FileResult> {
        const result = await this.actor.trash_file(arg0);
        return from_candid_FileResult_n19(result);
    }
    async update_folder(arg0: string, arg1: string, arg2: Array<string>): Promise<FolderResult> {
        const result = await this.actor.update_folder(arg0, arg1, arg2);
        return from_candid_FolderResult_n2(result);
    }
}
function from_candid_FileResult_n19(value: _FileResult): FileResult {
    return from_candid_variant_n20(value);
}
function from_candid_FilesResult_n9(value: _FilesResult): FilesResult {
    return from_candid_variant_n10(value);
}
function from_candid_FolderResult_n2(value: _FolderResult): FolderResult {
    return from_candid_variant_n3(value);
}
function from_candid_FoldersResult_n15(value: _FoldersResult): FoldersResult {
    return from_candid_variant_n16(value);
}
function from_candid_VaultFile_n12(value: _VaultFile): VaultFile {
    return from_candid_record_n13(value);
}
function from_candid_VaultFolder_n4(value: _VaultFolder): VaultFolder {
    return from_candid_record_n5(value);
}
function from_candid_opt_n14(value: [] | [_BlobRef]): BlobRef | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(value: {
    id: string;
    club: string;
    mime: string;
    name: string;
    size: bigint;
    team: [] | [string];
    file_url: string;
    created_at_ms: bigint;
    blob_ref: [] | [_BlobRef];
    folder_id: string;
    is_external_link: boolean;
    deleted_at_ms: [] | [bigint];
    uploaded_by: Principal;
}): {
    id: string;
    club: string;
    mime: string;
    name: string;
    size: bigint;
    team?: string;
    file_url: string;
    created_at_ms: bigint;
    blob_ref?: BlobRef;
    folder_id: string;
    is_external_link: boolean;
    deleted_at_ms?: bigint;
    uploaded_by: Principal;
} {
    return {
        id: value.id,
        club: value.club,
        mime: value.mime,
        name: value.name,
        size: value.size,
        team: record_opt_to_undefined(from_candid_opt_n6(value.team)),
        file_url: value.file_url,
        created_at_ms: value.created_at_ms,
        blob_ref: record_opt_to_undefined(from_candid_opt_n14(value.blob_ref)),
        folder_id: value.folder_id,
        is_external_link: value.is_external_link,
        deleted_at_ms: record_opt_to_undefined(from_candid_opt_n7(value.deleted_at_ms)),
        uploaded_by: value.uploaded_by
    };
}
function from_candid_record_n5(value: {
    id: string;
    club: string;
    name: string;
    team: [] | [string];
    restricted_roles: Array<string>;
    created_by: Principal;
    created_at_ms: bigint;
    parent_id: [] | [string];
    deleted_at_ms: [] | [bigint];
}): {
    id: string;
    club: string;
    name: string;
    team?: string;
    restricted_roles: Array<string>;
    created_by: Principal;
    created_at_ms: bigint;
    parent_id?: string;
    deleted_at_ms?: bigint;
} {
    return {
        id: value.id,
        club: value.club,
        name: value.name,
        team: record_opt_to_undefined(from_candid_opt_n6(value.team)),
        restricted_roles: value.restricted_roles,
        created_by: value.created_by,
        created_at_ms: value.created_at_ms,
        parent_id: record_opt_to_undefined(from_candid_opt_n6(value.parent_id)),
        deleted_at_ms: record_opt_to_undefined(from_candid_opt_n7(value.deleted_at_ms))
    };
}
function from_candid_variant_n10(value: {
    Ok: Array<_VaultFile>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<VaultFile>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n11(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n16(value: {
    Ok: Array<_VaultFolder>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<VaultFolder>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n17(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n20(value: {
    Ok: _VaultFile;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: VaultFile;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_VaultFile_n12(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n3(value: {
    Ok: _VaultFolder;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: VaultFolder;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_VaultFolder_n4(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n8(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n11(value: Array<_VaultFile>): Array<VaultFile> {
    return value.map((x)=>from_candid_VaultFile_n12(x));
}
function from_candid_vec_n17(value: Array<_VaultFolder>): Array<VaultFolder> {
    return value.map((x)=>from_candid_VaultFolder_n4(x));
}
function to_candid_opt_n1(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n18(value: BlobRef | null): [] | [_BlobRef] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Vault_domain {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Vault_domain(actor);
}
