/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const VaultFolder = IDL.Record({
    'id' : IDL.Text,
    'club' : IDL.Text,
    'name' : IDL.Text,
    'team' : IDL.Opt(IDL.Text),
    'restricted_roles' : IDL.Vec(IDL.Text),
    'created_by' : IDL.Principal,
    'created_at_ms' : IDL.Nat64,
    'parent_id' : IDL.Opt(IDL.Text),
    'deleted_at_ms' : IDL.Opt(IDL.Nat64),
  });
  const FolderResult = IDL.Variant({ 'Ok' : VaultFolder, 'Err' : IDL.Text });
  const BlobRef = IDL.Record({
    'path' : IDL.Text,
    'content_hash' : IDL.Text,
    'canister' : IDL.Text,
  });
  const VaultFile = IDL.Record({
    'id' : IDL.Text,
    'club' : IDL.Text,
    'mime' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Nat64,
    'team' : IDL.Opt(IDL.Text),
    'file_url' : IDL.Text,
    'created_at_ms' : IDL.Nat64,
    'blob_ref' : IDL.Opt(BlobRef),
    'folder_id' : IDL.Text,
    'is_external_link' : IDL.Bool,
    'deleted_at_ms' : IDL.Opt(IDL.Nat64),
    'uploaded_by' : IDL.Principal,
  });
  const FilesResult = IDL.Variant({
    'Ok' : IDL.Vec(VaultFile),
    'Err' : IDL.Text,
  });
  const FoldersResult = IDL.Variant({
    'Ok' : IDL.Vec(VaultFolder),
    'Err' : IDL.Text,
  });
  const FileResult = IDL.Variant({ 'Ok' : VaultFile, 'Err' : IDL.Text });
  
  return IDL.Service({
    'create_folder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [FolderResult],
        [],
      ),
    'delete_folder' : IDL.Func([IDL.Text], [FolderResult], []),
    'grant_role' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'initialize' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'list_club_files' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [FilesResult],
        ['query'],
      ),
    'list_files' : IDL.Func([IDL.Text], [FilesResult], ['query']),
    'list_folders' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [FoldersResult],
        ['query'],
      ),
    'list_trashed_files' : IDL.Func([IDL.Text], [FilesResult], ['query']),
    'register_file' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Nat64,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(BlobRef),
        ],
        [FileResult],
        [],
      ),
    'restore_file' : IDL.Func([IDL.Text], [FileResult], []),
    'trash_file' : IDL.Func([IDL.Text], [FileResult], []),
    'update_folder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [FolderResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };