/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/messaging_domain.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface OnlineUser {
    last_seen_ms: bigint;
    user: Principal;
    platform?: string;
}
export interface RecentConversation {
    last_message_sequence: bigint;
    conversation_id: string;
    kind: string;
    last_message_at_ms?: bigint;
}
export interface WebsocketMessage {
    sequence_num: bigint;
    content: Uint8Array;
    client_key: ClientKey;
    timestamp: bigint;
    is_service_message: boolean;
}
export interface Conversation {
    id: string;
    participants: Array<Principal>;
    team_id?: string;
    next_sequence: bigint;
    club_id: string;
}
export type CanisterWsGetMessagesResult = {
    __kind__: "Ok";
    Ok: CanisterOutputCertifiedMessages;
} | {
    __kind__: "Err";
    Err: string;
};
export interface UnreadSummary {
    conversation_id: string;
    kind: string;
    count: bigint;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface ReactionSummary {
    count: number;
    emoji: string;
}
export interface PollResults {
    poll: Poll;
    total_votes: number;
    counts: Uint32Array;
}
export interface CanisterWsMessageArguments {
    msg: WebsocketMessage;
}
export interface ClubUnreadSummary {
    count: bigint;
    club_id: string;
}
export interface CanisterWsCloseArguments {
    client_key: ClientKey;
}
export interface CanisterOutputCertifiedMessages {
    messages: Array<CanisterOutputMessage>;
    cert: Uint8Array;
    tree: Uint8Array;
    is_end_of_queue: boolean;
}
export interface Poll {
    id: string;
    closed: boolean;
    creator: Principal;
    question: string;
    conversation_id: string;
    created_at_ms: bigint;
    message_id?: string;
    options: Array<string>;
}
export interface RoleGrant {
    role: string;
    user: Principal;
    team_id?: string;
    club_id?: string;
}
export interface TypingUser {
    name: string;
    user: Principal;
}
export interface MutePreference {
    muted: boolean;
    conversation_id: string;
    user: Principal;
}
export interface Receipt {
    conversation_id: string;
    read: boolean;
    user: Principal;
    message_id: string;
}
export interface ClubDmSettings {
    ai_catch_up_enabled: boolean;
    allowed_roles: Array<string>;
    force_disable_previews: boolean;
    attachments_disabled: boolean;
    club_id: string;
    dm_disabled: boolean;
}
export interface LinkPreview {
    title?: string;
    description?: string;
    site_name?: string;
    image?: string;
}
export interface GroupSummary {
    conversation_id: string;
    kind: string;
    name: string;
    team_id?: string;
    description?: string;
    is_member: boolean;
    member_count: number;
    club_id?: string;
    avatar?: string;
}
export interface MessageWithReactions {
    message: Message;
    reactions: Array<ReactionSummary>;
}
export type CanisterWsMessageResult = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
};
export interface GroupMetadata {
    deleted: boolean;
    members: Array<Principal>;
    conversation_id: string;
    kind: string;
    name: string;
    team_id?: string;
    description?: string;
    created_at_ms: bigint;
    admin_only_posting: boolean;
    deleted_by?: Principal;
    club_id?: string;
    deleted_at_ms?: bigint;
    avatar?: string;
}
export type GatewayPrincipal = Principal;
export interface AttachmentMetadata {
    id: string;
    url?: string;
    conversation_id: string;
    kind: string;
    size_bytes?: bigint;
    created_at_ms: bigint;
    uploader: Principal;
    message_id?: string;
    ref_id: string;
}
export interface State {
    forwardRecords: Array<ForwardRecord>;
    joinRequests: Array<JoinRequest>;
    scheduledMessages: Array<ScheduledMessage>;
    messages: Array<Message>;
    schema: number;
    mutePreferences: Array<MutePreference>;
    dmAttachmentsDisabled: Array<Principal>;
    clubDmSettings: Array<ClubDmSettings>;
    groupRoles: Array<GroupRole>;
    unread: Array<Unread>;
    typingPings: Array<TypingPing>;
    groupMetadata: Array<GroupMetadata>;
    clubMemberships: Array<ClubMembership>;
    pollVotes: Array<PollVote>;
    governor: Principal;
    conversations: Array<Conversation>;
    pinnedMessages: Array<PinnedMessage>;
    polls: Array<Poll>;
    attachmentMetadata: Array<AttachmentMetadata>;
    dmLinks: Array<DmLink>;
    userMessagingSettings: Array<UserMessagingSettings>;
    receipts: Array<Receipt>;
    reactions: Array<Reaction>;
    roles: Array<RoleGrant>;
    competitionAdmins: Array<CompetitionAdmin>;
}
export interface PollVote {
    poll_id: string;
    user: Principal;
    option_index: number;
}
export interface BroadcastResult {
    skipped: Array<string>;
    delivered: number;
}
export interface PinnedMessage {
    id: string;
    pinned_by: Principal;
    conversation_id: string;
    created_at_ms: bigint;
    message_id: string;
}
export interface GroupRole {
    conversation_id: string;
    role: string;
    user: Principal;
}
export interface MainInterface {
    addBulkAccessPrincipal(principal: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    add_group_members(conversation_id: string, members: Array<Principal>): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    approve_join_request(conversation_id: string, user: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    block_user(user: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    broadcast_announcement(club_id: string, team_ids: Array<string>, include_club_chat: boolean, body: string, idempotency_key: string): Promise<{
        __kind__: "Ok";
        Ok: BroadcastResult;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    can_dm_user(other: Principal): Promise<boolean>;
    close_poll(poll_id: string): Promise<{
        __kind__: "Ok";
        Ok: Poll;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_conversation(club_id: string, team_id: string | null, participants: Array<Principal>): Promise<{
        __kind__: "Ok";
        Ok: Conversation;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_group_with_roles(club_id: string, team_id: string | null, name: string, kind: string, role_entries: Array<[Principal, string]>): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    create_poll(conversation_id: string, message_id: string | null, question: string, options: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: Poll;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    delete_club_data(club_id: string): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    delete_message(message_id: string): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    delete_poll(poll_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    delete_team_data(team_id: string): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    dm_attachments_disabled(user: Principal): Promise<boolean>;
    enable_ai_catch_up_for_all_members(club_id: string): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    ensure_broadcast_conversation(): Promise<{
        __kind__: "Ok";
        Ok: Conversation;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    ensure_club_admin_conversation(club_id: string): Promise<{
        __kind__: "Ok";
        Ok: Conversation;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    ensure_conversation(club_id: string, team_id: string | null, participants: Array<Principal>): Promise<{
        __kind__: "Ok";
        Ok: Conversation;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    export_state(): Promise<{
        __kind__: "Ok";
        Ok: State;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    fetch_link_preview(url: string): Promise<{
        __kind__: "Ok";
        Ok: LinkPreview;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    forward_message(message_id: string, to_conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    generate_chat_recap(conversation_id: string, since_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: string;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_club_dm_settings(club_id: string): Promise<ClubDmSettings>;
    get_group_metadata(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_minimum_app_versions(): Promise<{
        __kind__: "Ok";
        Ok: Array<[string, string]>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_mute_preference(conversation_id: string): Promise<boolean>;
    get_or_create_dm(other: Principal): Promise<{
        __kind__: "Ok";
        Ok: Conversation;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_poll_results(poll_id: string): Promise<{
        __kind__: "Ok";
        Ok: PollResults;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    get_user_messaging_settings(): Promise<UserMessagingSettings>;
    grant_competition_admin(conversation_id: string, user: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    grant_role(principal: Principal, role: string, club_id: string | null, team_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    has_blocked(user: Principal): Promise<boolean>;
    is_competition_admin(conversation_id: string): Promise<boolean>;
    leave_group(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    listBulkAccessPrincipals(): Promise<{
        __kind__: "Ok";
        Ok: Array<Principal>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_all_online_users(): Promise<{
        __kind__: "Ok";
        Ok: Array<OnlineUser>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_blocked_users(): Promise<Array<Principal>>;
    list_club_dm_settings(): Promise<{
        __kind__: "Ok";
        Ok: Array<ClubDmSettings>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_deleted_groups(): Promise<{
        __kind__: "Ok";
        Ok: Array<GroupMetadata>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_dm_attachments_disabled(): Promise<{
        __kind__: "Ok";
        Ok: Array<Principal>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_groups_by_club(club_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<GroupSummary>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_groups_by_team(team_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<GroupSummary>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_join_requests(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<JoinRequest>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_latest_messages_page(conversation_id: string, before: bigint | null, limit: number): Promise<{
        __kind__: "Ok";
        Ok: MessagePage;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_messages(conversation_id: string, after: bigint | null): Promise<Array<Message>>;
    list_messages_page(conversation_id: string, after: bigint | null, limit: number): Promise<{
        __kind__: "Ok";
        Ok: MessagePage;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_pinned_messages(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<PinnedMessage>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_reactions(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<Reaction>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_read_receipts(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<Receipt>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    list_typing(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: Array<TypingUser>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    mark_read(conversation_id: string, message_id: string): Promise<{
        __kind__: "Ok";
        Ok: Receipt;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    messages_since(conversation_id: string, since_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<MessageWithReactions>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    my_unread_counts(): Promise<Array<UnreadSummary>>;
    online_count(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: bigint;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    pin_message(conversation_id: string, message_id: string): Promise<{
        __kind__: "Ok";
        Ok: PinnedMessage;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    presence_heartbeat(platform: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    purge_group(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    recapTransform(arg0: {
        context: Uint8Array;
        response: HttpRequestResult;
    }): Promise<HttpRequestResult>;
    recent_conversations(principal: Principal, limit: number): Promise<{
        __kind__: "Ok";
        Ok: Array<RecentConversation>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    register_attachment_metadata(conversation_id: string, message_id: string | null, kind: string, ref_id: string, url: string | null, size_bytes: bigint | null): Promise<{
        __kind__: "Ok";
        Ok: AttachmentMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    register_scheduled_message(conversation_id: string, body: string, scheduled_at_ms: bigint): Promise<{
        __kind__: "Ok";
        Ok: ScheduledMessage;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    reject_join_request(conversation_id: string, user: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    removeBulkAccessPrincipal(principal: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    remove_group_member(conversation_id: string, member: Principal): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    replay_scheduled_message(id: string): Promise<{
        __kind__: "Ok";
        Ok: ScheduledMessage;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    request_join_group(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    restore_group(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    send_message(conversation_id: string, body: string, idempotency_key: string, attachment: Attachment | null, reply_to_id: string | null): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    send_system_message(to_user: Principal, body: string, idempotency_key: string): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    send_welcome_message(body: string): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_club_ai_catch_up(club_id: string, ai_catch_up_enabled: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_club_dm_allowed_roles(club_id: string, allowed_roles: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_club_dm_settings(club_id: string, dm_disabled: boolean, attachments_disabled: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_club_domain_canister(id: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_club_message_privacy(club_id: string, force_disable_previews: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_dm_attachments_disabled(user: Principal, disabled: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_minimum_app_versions(versions: Array<[string, string]>): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_mute_preference(conversation_id: string, muted: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_notification_queue_canister(id: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_recap_config(config: RecapConfig | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_typing(conversation_id: string, is_typing: boolean, name: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    set_user_messaging_settings(hide_message_preview: boolean, ai_catchup_enabled: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    soft_delete_group(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    toggle_reaction(message_id: string, emoji: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    transfer_governorship(new_governor: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    unblock_user(user: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    unpin_message(conversation_id: string, message_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    unread_count(conversation_id: string): Promise<{
        __kind__: "Ok";
        Ok: Unread;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    unread_count_by_club(principal: Principal): Promise<{
        __kind__: "Ok";
        Ok: Array<ClubUnreadSummary>;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    update_group(conversation_id: string, name: string | null, avatar: string | null, description: string | null, admin_only_posting: boolean | null): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    update_message(message_id: string, body: string): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    upsert_club_membership(user: Principal, club_id: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    upsert_group_metadata(conversation_id: string, name: string, kind: string, club_id: string | null, team_id: string | null, members: Array<Principal>): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    vote_poll(poll_id: string, option_index: number): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    ws_close(args: CanisterWsCloseArguments): Promise<CanisterWsCloseResult>;
    ws_get_messages(args: CanisterWsGetMessagesArguments): Promise<CanisterWsGetMessagesResult>;
    ws_message(args: CanisterWsMessageArguments, msg_type: WsAppMessage | null): Promise<CanisterWsMessageResult>;
    ws_open(args: CanisterWsOpenArguments): Promise<CanisterWsOpenResult>;
}
export interface ClubMembership {
    user: Principal;
    club_id: string;
}
export type WsAppMessage = {
    __kind__: "chat_poke";
    chat_poke: {
        conversation_id: string;
        sequence: bigint;
    };
};
export interface ClientKey {
    client_principal: ClientPrincipal;
    client_nonce: bigint;
}
export type CanisterWsCloseResult = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
};
export interface CompetitionAdmin {
    conversation_id: string;
    user: Principal;
}
export interface CanisterWsOpenArguments {
    gateway_principal: GatewayPrincipal;
    client_nonce: bigint;
}
export interface UserMessagingSettings {
    ai_catchup_enabled: boolean;
    user: Principal;
    hide_message_preview: boolean;
}
export type CanisterWsOpenResult = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
};
export interface ForwardRecord {
    to_conversation_id: string;
    original_sender: Principal;
    message_id: string;
    from_conversation_id: string;
    from_message_id: string;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface Unread {
    conversation_id: string;
    count: bigint;
    user: Principal;
    last_read_sequence: bigint;
}
export interface ScheduledMessage {
    id: string;
    replayed_message_id?: string;
    conversation_id: string;
    body: string;
    sender: Principal;
    scheduled_at_ms: bigint;
    replayed_at_ms?: bigint;
}
export interface CanisterOutputMessage {
    key: string;
    content: Uint8Array;
    client_key: ClientKey;
}
export interface DmLink {
    a: Principal;
    b: Principal;
    conversation_id: string;
}
export interface TypingPing {
    conversation_id: string;
    name: string;
    user: Principal;
    last_typed_ms: bigint;
}
export interface CanisterWsGetMessagesArguments {
    nonce: bigint;
}
export interface Message {
    id: string;
    conversation_id: string;
    body: string;
    reply_to_id?: string;
    sender: Principal;
    created_at_ms: bigint;
    edited_at_ms?: bigint;
    attachment?: Attachment;
    sequence: bigint;
    idempotency_key: string;
}
export interface Attachment {
    url?: string;
    kind: string;
    ref_id: string;
}
export interface MessagePage {
    messages: Array<Message>;
    latest_sequence: bigint;
    next_sequence?: bigint;
}
export type ClientPrincipal = Principal;
export interface RecapConfig {
    model: string;
    api_key: string;
    endpoint_url: string;
}
export interface JoinRequest {
    status: string;
    conversation_id: string;
    user: Principal;
    created_at_ms: bigint;
}
export interface Reaction {
    user: Principal;
    emoji: string;
    message_id: string;
}
export interface messaging_domainInterface extends MainInterface {
}
import type { Attachment as _Attachment, AttachmentMetadata as _AttachmentMetadata, BroadcastResult as _BroadcastResult, CanisterOutputCertifiedMessages as _CanisterOutputCertifiedMessages, CanisterWsCloseResult as _CanisterWsCloseResult, CanisterWsGetMessagesResult as _CanisterWsGetMessagesResult, CanisterWsMessageResult as _CanisterWsMessageResult, CanisterWsOpenResult as _CanisterWsOpenResult, ClubDmSettings as _ClubDmSettings, ClubMembership as _ClubMembership, ClubUnreadSummary as _ClubUnreadSummary, CompetitionAdmin as _CompetitionAdmin, Conversation as _Conversation, DmLink as _DmLink, ForwardRecord as _ForwardRecord, GroupMetadata as _GroupMetadata, GroupRole as _GroupRole, GroupSummary as _GroupSummary, JoinRequest as _JoinRequest, LinkPreview as _LinkPreview, Message as _Message, MessagePage as _MessagePage, MessageWithReactions as _MessageWithReactions, MutePreference as _MutePreference, OnlineUser as _OnlineUser, PinnedMessage as _PinnedMessage, Poll as _Poll, PollResults as _PollResults, PollVote as _PollVote, Reaction as _Reaction, ReactionSummary as _ReactionSummary, RecapConfig as _RecapConfig, Receipt as _Receipt, RecentConversation as _RecentConversation, RoleGrant as _RoleGrant, ScheduledMessage as _ScheduledMessage, State as _State, TypingPing as _TypingPing, TypingUser as _TypingUser, Unread as _Unread, UserMessagingSettings as _UserMessagingSettings, WsAppMessage as _WsAppMessage } from "./declarations/messaging_domain.did";
export class Messaging_domain implements messaging_domainInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async addBulkAccessPrincipal(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.addBulkAccessPrincipal(arg0);
        return from_candid_variant_n1(result);
    }
    async add_group_members(arg0: string, arg1: Array<Principal>): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.add_group_members(arg0, arg1);
        return from_candid_variant_n2(result);
    }
    async approve_join_request(arg0: string, arg1: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.approve_join_request(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async block_user(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.block_user(arg0);
        return from_candid_variant_n1(result);
    }
    async broadcast_announcement(arg0: string, arg1: Array<string>, arg2: boolean, arg3: string, arg4: string): Promise<{
        __kind__: "Ok";
        Ok: BroadcastResult;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.broadcast_announcement(arg0, arg1, arg2, arg3, arg4);
        return from_candid_variant_n8(result);
    }
    async can_dm_user(arg0: Principal): Promise<boolean> {
        const result = await this.actor.can_dm_user(arg0);
        return result;
    }
    async close_poll(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Poll;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.close_poll(arg0);
        return from_candid_variant_n9(result);
    }
    async create_conversation(arg0: string, arg1: string | null, arg2: Array<Principal>): Promise<{
        __kind__: "Ok";
        Ok: Conversation;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_conversation(arg0, to_candid_opt_n12(arg1), arg2);
        return from_candid_variant_n13(result);
    }
    async create_group_with_roles(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: Array<[Principal, string]>): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_group_with_roles(arg0, to_candid_opt_n12(arg1), arg2, arg3, arg4);
        return from_candid_variant_n2(result);
    }
    async create_poll(arg0: string, arg1: string | null, arg2: string, arg3: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: Poll;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.create_poll(arg0, to_candid_opt_n12(arg1), arg2, arg3);
        return from_candid_variant_n9(result);
    }
    async delete_club_data(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_club_data(arg0);
        return from_candid_variant_n16(result);
    }
    async delete_message(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_message(arg0);
        return from_candid_variant_n17(result);
    }
    async delete_poll(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_poll(arg0);
        return from_candid_variant_n1(result);
    }
    async delete_team_data(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.delete_team_data(arg0);
        return from_candid_variant_n16(result);
    }
    async dm_attachments_disabled(arg0: Principal): Promise<boolean> {
        const result = await this.actor.dm_attachments_disabled(arg0);
        return result;
    }
    async enable_ai_catch_up_for_all_members(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: number;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.enable_ai_catch_up_for_all_members(arg0);
        return from_candid_variant_n16(result);
    }
    async ensure_broadcast_conversation(): Promise<{
        __kind__: "Ok";
        Ok: Conversation;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.ensure_broadcast_conversation();
        return from_candid_variant_n13(result);
    }
    async ensure_club_admin_conversation(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Conversation;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.ensure_club_admin_conversation(arg0);
        return from_candid_variant_n13(result);
    }
    async ensure_conversation(arg0: string, arg1: string | null, arg2: Array<Principal>): Promise<{
        __kind__: "Ok";
        Ok: Conversation;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.ensure_conversation(arg0, to_candid_opt_n12(arg1), arg2);
        return from_candid_variant_n13(result);
    }
    async export_state(): Promise<{
        __kind__: "Ok";
        Ok: State;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.export_state();
        return from_candid_variant_n23(result);
    }
    async fetch_link_preview(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: LinkPreview;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.fetch_link_preview(arg0);
        return from_candid_variant_n39(result);
    }
    async forward_message(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.forward_message(arg0, arg1);
        return from_candid_variant_n17(result);
    }
    async generate_chat_recap(arg0: string, arg1: bigint): Promise<{
        __kind__: "Ok";
        Ok: string;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.generate_chat_recap(arg0, arg1);
        return from_candid_variant_n42(result);
    }
    async get_club_dm_settings(arg0: string): Promise<ClubDmSettings> {
        const result = await this.actor.get_club_dm_settings(arg0);
        return result;
    }
    async get_group_metadata(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_group_metadata(arg0);
        return from_candid_variant_n2(result);
    }
    async get_minimum_app_versions(): Promise<{
        __kind__: "Ok";
        Ok: Array<[string, string]>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_minimum_app_versions();
        return from_candid_variant_n43(result);
    }
    async get_mute_preference(arg0: string): Promise<boolean> {
        const result = await this.actor.get_mute_preference(arg0);
        return result;
    }
    async get_or_create_dm(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: Conversation;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_or_create_dm(arg0);
        return from_candid_variant_n13(result);
    }
    async get_poll_results(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: PollResults;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.get_poll_results(arg0);
        return from_candid_variant_n44(result);
    }
    async get_user_messaging_settings(): Promise<UserMessagingSettings> {
        const result = await this.actor.get_user_messaging_settings();
        return result;
    }
    async grant_competition_admin(arg0: string, arg1: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.grant_competition_admin(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async grant_role(arg0: Principal, arg1: string, arg2: string | null, arg3: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.grant_role(arg0, arg1, to_candid_opt_n12(arg2), to_candid_opt_n12(arg3));
        return from_candid_variant_n1(result);
    }
    async has_blocked(arg0: Principal): Promise<boolean> {
        const result = await this.actor.has_blocked(arg0);
        return result;
    }
    async is_competition_admin(arg0: string): Promise<boolean> {
        const result = await this.actor.is_competition_admin(arg0);
        return result;
    }
    async leave_group(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.leave_group(arg0);
        return from_candid_variant_n2(result);
    }
    async listBulkAccessPrincipals(): Promise<{
        __kind__: "Ok";
        Ok: Array<Principal>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.listBulkAccessPrincipals();
        return from_candid_variant_n47(result);
    }
    async list_all_online_users(): Promise<{
        __kind__: "Ok";
        Ok: Array<OnlineUser>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_all_online_users();
        return from_candid_variant_n48(result);
    }
    async list_blocked_users(): Promise<Array<Principal>> {
        const result = await this.actor.list_blocked_users();
        return result;
    }
    async list_club_dm_settings(): Promise<{
        __kind__: "Ok";
        Ok: Array<ClubDmSettings>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_club_dm_settings();
        return from_candid_variant_n52(result);
    }
    async list_deleted_groups(): Promise<{
        __kind__: "Ok";
        Ok: Array<GroupMetadata>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_deleted_groups();
        return from_candid_variant_n53(result);
    }
    async list_dm_attachments_disabled(): Promise<{
        __kind__: "Ok";
        Ok: Array<Principal>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_dm_attachments_disabled();
        return from_candid_variant_n47(result);
    }
    async list_groups_by_club(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<GroupSummary>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_groups_by_club(arg0);
        return from_candid_variant_n54(result);
    }
    async list_groups_by_team(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<GroupSummary>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_groups_by_team(arg0);
        return from_candid_variant_n54(result);
    }
    async list_join_requests(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<JoinRequest>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_join_requests(arg0);
        return from_candid_variant_n58(result);
    }
    async list_latest_messages_page(arg0: string, arg1: bigint | null, arg2: number): Promise<{
        __kind__: "Ok";
        Ok: MessagePage;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_latest_messages_page(arg0, to_candid_opt_n59(arg1), arg2);
        return from_candid_variant_n60(result);
    }
    async list_messages(arg0: string, arg1: bigint | null): Promise<Array<Message>> {
        const result = await this.actor.list_messages(arg0, to_candid_opt_n59(arg1));
        return from_candid_vec_n29(result);
    }
    async list_messages_page(arg0: string, arg1: bigint | null, arg2: number): Promise<{
        __kind__: "Ok";
        Ok: MessagePage;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_messages_page(arg0, to_candid_opt_n59(arg1), arg2);
        return from_candid_variant_n60(result);
    }
    async list_pinned_messages(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<PinnedMessage>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_pinned_messages(arg0);
        return from_candid_variant_n63(result);
    }
    async list_reactions(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<Reaction>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_reactions(arg0);
        return from_candid_variant_n64(result);
    }
    async list_read_receipts(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<Receipt>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_read_receipts(arg0);
        return from_candid_variant_n65(result);
    }
    async list_typing(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Array<TypingUser>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.list_typing(arg0);
        return from_candid_variant_n66(result);
    }
    async mark_read(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: Receipt;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.mark_read(arg0, arg1);
        return from_candid_variant_n67(result);
    }
    async messages_since(arg0: string, arg1: bigint): Promise<{
        __kind__: "Ok";
        Ok: Array<MessageWithReactions>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.messages_since(arg0, arg1);
        return from_candid_variant_n68(result);
    }
    async my_unread_counts(): Promise<Array<UnreadSummary>> {
        const result = await this.actor.my_unread_counts();
        return result;
    }
    async online_count(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: bigint;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.online_count(arg0);
        return from_candid_variant_n72(result);
    }
    async pin_message(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: PinnedMessage;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.pin_message(arg0, arg1);
        return from_candid_variant_n73(result);
    }
    async presence_heartbeat(arg0: string | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.presence_heartbeat(to_candid_opt_n12(arg0));
        return from_candid_variant_n1(result);
    }
    async purge_group(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.purge_group(arg0);
        return from_candid_variant_n1(result);
    }
    async recapTransform(arg0: {
        context: Uint8Array;
        response: HttpRequestResult;
    }): Promise<HttpRequestResult> {
        const result = await this.actor.recapTransform(arg0);
        return result;
    }
    async recent_conversations(arg0: Principal, arg1: number): Promise<{
        __kind__: "Ok";
        Ok: Array<RecentConversation>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.recent_conversations(arg0, arg1);
        return from_candid_variant_n74(result);
    }
    async register_attachment_metadata(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: string | null, arg5: bigint | null): Promise<{
        __kind__: "Ok";
        Ok: AttachmentMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.register_attachment_metadata(arg0, to_candid_opt_n12(arg1), arg2, arg3, to_candid_opt_n12(arg4), to_candid_opt_n59(arg5));
        return from_candid_variant_n78(result);
    }
    async register_scheduled_message(arg0: string, arg1: string, arg2: bigint): Promise<{
        __kind__: "Ok";
        Ok: ScheduledMessage;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.register_scheduled_message(arg0, arg1, arg2);
        return from_candid_variant_n79(result);
    }
    async reject_join_request(arg0: string, arg1: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.reject_join_request(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async removeBulkAccessPrincipal(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.removeBulkAccessPrincipal(arg0);
        return from_candid_variant_n1(result);
    }
    async remove_group_member(arg0: string, arg1: Principal): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.remove_group_member(arg0, arg1);
        return from_candid_variant_n2(result);
    }
    async replay_scheduled_message(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: ScheduledMessage;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.replay_scheduled_message(arg0);
        return from_candid_variant_n79(result);
    }
    async request_join_group(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.request_join_group(arg0);
        return from_candid_variant_n1(result);
    }
    async restore_group(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.restore_group(arg0);
        return from_candid_variant_n1(result);
    }
    async send_message(arg0: string, arg1: string, arg2: string, arg3: Attachment | null, arg4: string | null): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.send_message(arg0, arg1, arg2, to_candid_opt_n80(arg3), to_candid_opt_n12(arg4));
        return from_candid_variant_n17(result);
    }
    async send_system_message(arg0: Principal, arg1: string, arg2: string): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.send_system_message(arg0, arg1, arg2);
        return from_candid_variant_n17(result);
    }
    async send_welcome_message(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.send_welcome_message(arg0);
        return from_candid_variant_n17(result);
    }
    async set_club_ai_catch_up(arg0: string, arg1: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_club_ai_catch_up(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async set_club_dm_allowed_roles(arg0: string, arg1: Array<string>): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_club_dm_allowed_roles(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async set_club_dm_settings(arg0: string, arg1: boolean, arg2: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_club_dm_settings(arg0, arg1, arg2);
        return from_candid_variant_n1(result);
    }
    async set_club_domain_canister(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_club_domain_canister(arg0);
        return from_candid_variant_n1(result);
    }
    async set_club_message_privacy(arg0: string, arg1: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_club_message_privacy(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async set_dm_attachments_disabled(arg0: Principal, arg1: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_dm_attachments_disabled(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async set_minimum_app_versions(arg0: Array<[string, string]>): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_minimum_app_versions(arg0);
        return from_candid_variant_n1(result);
    }
    async set_mute_preference(arg0: string, arg1: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_mute_preference(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async set_notification_queue_canister(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_notification_queue_canister(arg0);
        return from_candid_variant_n1(result);
    }
    async set_recap_config(arg0: RecapConfig | null): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_recap_config(to_candid_opt_n83(arg0));
        return from_candid_variant_n1(result);
    }
    async set_typing(arg0: string, arg1: boolean, arg2: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_typing(arg0, arg1, arg2);
        return from_candid_variant_n1(result);
    }
    async set_user_messaging_settings(arg0: boolean, arg1: boolean): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.set_user_messaging_settings(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async soft_delete_group(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.soft_delete_group(arg0);
        return from_candid_variant_n1(result);
    }
    async toggle_reaction(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.toggle_reaction(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async transfer_governorship(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.transfer_governorship(arg0);
        return from_candid_variant_n1(result);
    }
    async unblock_user(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.unblock_user(arg0);
        return from_candid_variant_n1(result);
    }
    async unpin_message(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.unpin_message(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async unread_count(arg0: string): Promise<{
        __kind__: "Ok";
        Ok: Unread;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.unread_count(arg0);
        return from_candid_variant_n84(result);
    }
    async unread_count_by_club(arg0: Principal): Promise<{
        __kind__: "Ok";
        Ok: Array<ClubUnreadSummary>;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.unread_count_by_club(arg0);
        return from_candid_variant_n85(result);
    }
    async update_group(arg0: string, arg1: string | null, arg2: string | null, arg3: string | null, arg4: boolean | null): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.update_group(arg0, to_candid_opt_n12(arg1), to_candid_opt_n12(arg2), to_candid_opt_n12(arg3), to_candid_opt_n86(arg4));
        return from_candid_variant_n2(result);
    }
    async update_message(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: Message;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.update_message(arg0, arg1);
        return from_candid_variant_n17(result);
    }
    async upsert_club_membership(arg0: Principal, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.upsert_club_membership(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async upsert_group_metadata(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string | null, arg5: Array<Principal>): Promise<{
        __kind__: "Ok";
        Ok: GroupMetadata;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.upsert_group_metadata(arg0, arg1, arg2, to_candid_opt_n12(arg3), to_candid_opt_n12(arg4), arg5);
        return from_candid_variant_n2(result);
    }
    async vote_poll(arg0: string, arg1: number): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        const result = await this.actor.vote_poll(arg0, arg1);
        return from_candid_variant_n1(result);
    }
    async ws_close(arg0: CanisterWsCloseArguments): Promise<CanisterWsCloseResult> {
        const result = await this.actor.ws_close(arg0);
        return from_candid_CanisterWsCloseResult_n87(result);
    }
    async ws_get_messages(arg0: CanisterWsGetMessagesArguments): Promise<CanisterWsGetMessagesResult> {
        const result = await this.actor.ws_get_messages(arg0);
        return from_candid_CanisterWsGetMessagesResult_n88(result);
    }
    async ws_message(arg0: CanisterWsMessageArguments, arg1: WsAppMessage | null): Promise<CanisterWsMessageResult> {
        const result = await this.actor.ws_message(arg0, to_candid_opt_n90(arg1));
        return from_candid_CanisterWsMessageResult_n93(result);
    }
    async ws_open(arg0: CanisterWsOpenArguments): Promise<CanisterWsOpenResult> {
        const result = await this.actor.ws_open(arg0);
        return from_candid_CanisterWsOpenResult_n94(result);
    }
}
function from_candid_AttachmentMetadata_n34(value: _AttachmentMetadata): AttachmentMetadata {
    return from_candid_record_n35(value);
}
function from_candid_Attachment_n21(value: _Attachment): Attachment {
    return from_candid_record_n22(value);
}
function from_candid_CanisterWsCloseResult_n87(value: _CanisterWsCloseResult): CanisterWsCloseResult {
    return from_candid_variant_n1(value);
}
function from_candid_CanisterWsGetMessagesResult_n88(value: _CanisterWsGetMessagesResult): CanisterWsGetMessagesResult {
    return from_candid_variant_n89(value);
}
function from_candid_CanisterWsMessageResult_n93(value: _CanisterWsMessageResult): CanisterWsMessageResult {
    return from_candid_variant_n1(value);
}
function from_candid_CanisterWsOpenResult_n94(value: _CanisterWsOpenResult): CanisterWsOpenResult {
    return from_candid_variant_n1(value);
}
function from_candid_Conversation_n14(value: _Conversation): Conversation {
    return from_candid_record_n15(value);
}
function from_candid_GroupMetadata_n3(value: _GroupMetadata): GroupMetadata {
    return from_candid_record_n4(value);
}
function from_candid_GroupSummary_n56(value: _GroupSummary): GroupSummary {
    return from_candid_record_n57(value);
}
function from_candid_LinkPreview_n40(value: _LinkPreview): LinkPreview {
    return from_candid_record_n41(value);
}
function from_candid_MessagePage_n61(value: _MessagePage): MessagePage {
    return from_candid_record_n62(value);
}
function from_candid_MessageWithReactions_n70(value: _MessageWithReactions): MessageWithReactions {
    return from_candid_record_n71(value);
}
function from_candid_Message_n18(value: _Message): Message {
    return from_candid_record_n19(value);
}
function from_candid_OnlineUser_n50(value: _OnlineUser): OnlineUser {
    return from_candid_record_n51(value);
}
function from_candid_PollResults_n45(value: _PollResults): PollResults {
    return from_candid_record_n46(value);
}
function from_candid_Poll_n10(value: _Poll): Poll {
    return from_candid_record_n11(value);
}
function from_candid_RecentConversation_n76(value: _RecentConversation): RecentConversation {
    return from_candid_record_n77(value);
}
function from_candid_RoleGrant_n37(value: _RoleGrant): RoleGrant {
    return from_candid_record_n38(value);
}
function from_candid_ScheduledMessage_n27(value: _ScheduledMessage): ScheduledMessage {
    return from_candid_record_n28(value);
}
function from_candid_State_n24(value: _State): State {
    return from_candid_record_n25(value);
}
function from_candid_opt_n20(value: [] | [_Attachment]): Attachment | null {
    return value.length === 0 ? null : from_candid_Attachment_n21(value[0]);
}
function from_candid_opt_n5(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(value: {
    id: string;
    closed: boolean;
    creator: Principal;
    question: string;
    conversation_id: string;
    created_at_ms: bigint;
    message_id: [] | [string];
    options: Array<string>;
}): {
    id: string;
    closed: boolean;
    creator: Principal;
    question: string;
    conversation_id: string;
    created_at_ms: bigint;
    message_id?: string;
    options: Array<string>;
} {
    return {
        id: value.id,
        closed: value.closed,
        creator: value.creator,
        question: value.question,
        conversation_id: value.conversation_id,
        created_at_ms: value.created_at_ms,
        message_id: record_opt_to_undefined(from_candid_opt_n5(value.message_id)),
        options: value.options
    };
}
function from_candid_record_n15(value: {
    id: string;
    participants: Array<Principal>;
    team_id: [] | [string];
    next_sequence: bigint;
    club_id: string;
}): {
    id: string;
    participants: Array<Principal>;
    team_id?: string;
    next_sequence: bigint;
    club_id: string;
} {
    return {
        id: value.id,
        participants: value.participants,
        team_id: record_opt_to_undefined(from_candid_opt_n5(value.team_id)),
        next_sequence: value.next_sequence,
        club_id: value.club_id
    };
}
function from_candid_record_n19(value: {
    id: string;
    conversation_id: string;
    body: string;
    reply_to_id: [] | [string];
    sender: Principal;
    created_at_ms: bigint;
    edited_at_ms: [] | [bigint];
    attachment: [] | [_Attachment];
    sequence: bigint;
    idempotency_key: string;
}): {
    id: string;
    conversation_id: string;
    body: string;
    reply_to_id?: string;
    sender: Principal;
    created_at_ms: bigint;
    edited_at_ms?: bigint;
    attachment?: Attachment;
    sequence: bigint;
    idempotency_key: string;
} {
    return {
        id: value.id,
        conversation_id: value.conversation_id,
        body: value.body,
        reply_to_id: record_opt_to_undefined(from_candid_opt_n5(value.reply_to_id)),
        sender: value.sender,
        created_at_ms: value.created_at_ms,
        edited_at_ms: record_opt_to_undefined(from_candid_opt_n7(value.edited_at_ms)),
        attachment: record_opt_to_undefined(from_candid_opt_n20(value.attachment)),
        sequence: value.sequence,
        idempotency_key: value.idempotency_key
    };
}
function from_candid_record_n22(value: {
    url: [] | [string];
    kind: string;
    ref_id: string;
}): {
    url?: string;
    kind: string;
    ref_id: string;
} {
    return {
        url: record_opt_to_undefined(from_candid_opt_n5(value.url)),
        kind: value.kind,
        ref_id: value.ref_id
    };
}
function from_candid_record_n25(value: {
    forwardRecords: Array<_ForwardRecord>;
    joinRequests: Array<_JoinRequest>;
    scheduledMessages: Array<_ScheduledMessage>;
    messages: Array<_Message>;
    schema: number;
    mutePreferences: Array<_MutePreference>;
    dmAttachmentsDisabled: Array<Principal>;
    clubDmSettings: Array<_ClubDmSettings>;
    groupRoles: Array<_GroupRole>;
    unread: Array<_Unread>;
    typingPings: Array<_TypingPing>;
    groupMetadata: Array<_GroupMetadata>;
    clubMemberships: Array<_ClubMembership>;
    pollVotes: Array<_PollVote>;
    governor: Principal;
    conversations: Array<_Conversation>;
    pinnedMessages: Array<_PinnedMessage>;
    polls: Array<_Poll>;
    attachmentMetadata: Array<_AttachmentMetadata>;
    dmLinks: Array<_DmLink>;
    userMessagingSettings: Array<_UserMessagingSettings>;
    receipts: Array<_Receipt>;
    reactions: Array<_Reaction>;
    roles: Array<_RoleGrant>;
    competitionAdmins: Array<_CompetitionAdmin>;
}): {
    forwardRecords: Array<ForwardRecord>;
    joinRequests: Array<JoinRequest>;
    scheduledMessages: Array<ScheduledMessage>;
    messages: Array<Message>;
    schema: number;
    mutePreferences: Array<MutePreference>;
    dmAttachmentsDisabled: Array<Principal>;
    clubDmSettings: Array<ClubDmSettings>;
    groupRoles: Array<GroupRole>;
    unread: Array<Unread>;
    typingPings: Array<TypingPing>;
    groupMetadata: Array<GroupMetadata>;
    clubMemberships: Array<ClubMembership>;
    pollVotes: Array<PollVote>;
    governor: Principal;
    conversations: Array<Conversation>;
    pinnedMessages: Array<PinnedMessage>;
    polls: Array<Poll>;
    attachmentMetadata: Array<AttachmentMetadata>;
    dmLinks: Array<DmLink>;
    userMessagingSettings: Array<UserMessagingSettings>;
    receipts: Array<Receipt>;
    reactions: Array<Reaction>;
    roles: Array<RoleGrant>;
    competitionAdmins: Array<CompetitionAdmin>;
} {
    return {
        forwardRecords: value.forwardRecords,
        joinRequests: value.joinRequests,
        scheduledMessages: from_candid_vec_n26(value.scheduledMessages),
        messages: from_candid_vec_n29(value.messages),
        schema: value.schema,
        mutePreferences: value.mutePreferences,
        dmAttachmentsDisabled: value.dmAttachmentsDisabled,
        clubDmSettings: value.clubDmSettings,
        groupRoles: value.groupRoles,
        unread: value.unread,
        typingPings: value.typingPings,
        groupMetadata: from_candid_vec_n30(value.groupMetadata),
        clubMemberships: value.clubMemberships,
        pollVotes: value.pollVotes,
        governor: value.governor,
        conversations: from_candid_vec_n31(value.conversations),
        pinnedMessages: value.pinnedMessages,
        polls: from_candid_vec_n32(value.polls),
        attachmentMetadata: from_candid_vec_n33(value.attachmentMetadata),
        dmLinks: value.dmLinks,
        userMessagingSettings: value.userMessagingSettings,
        receipts: value.receipts,
        reactions: value.reactions,
        roles: from_candid_vec_n36(value.roles),
        competitionAdmins: value.competitionAdmins
    };
}
function from_candid_record_n28(value: {
    id: string;
    replayed_message_id: [] | [string];
    conversation_id: string;
    body: string;
    sender: Principal;
    scheduled_at_ms: bigint;
    replayed_at_ms: [] | [bigint];
}): {
    id: string;
    replayed_message_id?: string;
    conversation_id: string;
    body: string;
    sender: Principal;
    scheduled_at_ms: bigint;
    replayed_at_ms?: bigint;
} {
    return {
        id: value.id,
        replayed_message_id: record_opt_to_undefined(from_candid_opt_n5(value.replayed_message_id)),
        conversation_id: value.conversation_id,
        body: value.body,
        sender: value.sender,
        scheduled_at_ms: value.scheduled_at_ms,
        replayed_at_ms: record_opt_to_undefined(from_candid_opt_n7(value.replayed_at_ms))
    };
}
function from_candid_record_n35(value: {
    id: string;
    url: [] | [string];
    conversation_id: string;
    kind: string;
    size_bytes: [] | [bigint];
    created_at_ms: bigint;
    uploader: Principal;
    message_id: [] | [string];
    ref_id: string;
}): {
    id: string;
    url?: string;
    conversation_id: string;
    kind: string;
    size_bytes?: bigint;
    created_at_ms: bigint;
    uploader: Principal;
    message_id?: string;
    ref_id: string;
} {
    return {
        id: value.id,
        url: record_opt_to_undefined(from_candid_opt_n5(value.url)),
        conversation_id: value.conversation_id,
        kind: value.kind,
        size_bytes: record_opt_to_undefined(from_candid_opt_n7(value.size_bytes)),
        created_at_ms: value.created_at_ms,
        uploader: value.uploader,
        message_id: record_opt_to_undefined(from_candid_opt_n5(value.message_id)),
        ref_id: value.ref_id
    };
}
function from_candid_record_n38(value: {
    role: string;
    user: Principal;
    team_id: [] | [string];
    club_id: [] | [string];
}): {
    role: string;
    user: Principal;
    team_id?: string;
    club_id?: string;
} {
    return {
        role: value.role,
        user: value.user,
        team_id: record_opt_to_undefined(from_candid_opt_n5(value.team_id)),
        club_id: record_opt_to_undefined(from_candid_opt_n5(value.club_id))
    };
}
function from_candid_record_n4(value: {
    deleted: boolean;
    members: Array<Principal>;
    conversation_id: string;
    kind: string;
    name: string;
    team_id: [] | [string];
    description: [] | [string];
    created_at_ms: bigint;
    admin_only_posting: boolean;
    deleted_by: [] | [Principal];
    club_id: [] | [string];
    deleted_at_ms: [] | [bigint];
    avatar: [] | [string];
}): {
    deleted: boolean;
    members: Array<Principal>;
    conversation_id: string;
    kind: string;
    name: string;
    team_id?: string;
    description?: string;
    created_at_ms: bigint;
    admin_only_posting: boolean;
    deleted_by?: Principal;
    club_id?: string;
    deleted_at_ms?: bigint;
    avatar?: string;
} {
    return {
        deleted: value.deleted,
        members: value.members,
        conversation_id: value.conversation_id,
        kind: value.kind,
        name: value.name,
        team_id: record_opt_to_undefined(from_candid_opt_n5(value.team_id)),
        description: record_opt_to_undefined(from_candid_opt_n5(value.description)),
        created_at_ms: value.created_at_ms,
        admin_only_posting: value.admin_only_posting,
        deleted_by: record_opt_to_undefined(from_candid_opt_n6(value.deleted_by)),
        club_id: record_opt_to_undefined(from_candid_opt_n5(value.club_id)),
        deleted_at_ms: record_opt_to_undefined(from_candid_opt_n7(value.deleted_at_ms)),
        avatar: record_opt_to_undefined(from_candid_opt_n5(value.avatar))
    };
}
function from_candid_record_n41(value: {
    title: [] | [string];
    description: [] | [string];
    site_name: [] | [string];
    image: [] | [string];
}): {
    title?: string;
    description?: string;
    site_name?: string;
    image?: string;
} {
    return {
        title: record_opt_to_undefined(from_candid_opt_n5(value.title)),
        description: record_opt_to_undefined(from_candid_opt_n5(value.description)),
        site_name: record_opt_to_undefined(from_candid_opt_n5(value.site_name)),
        image: record_opt_to_undefined(from_candid_opt_n5(value.image))
    };
}
function from_candid_record_n46(value: {
    poll: _Poll;
    total_votes: number;
    counts: Uint32Array;
}): {
    poll: Poll;
    total_votes: number;
    counts: Uint32Array;
} {
    return {
        poll: from_candid_Poll_n10(value.poll),
        total_votes: value.total_votes,
        counts: value.counts
    };
}
function from_candid_record_n51(value: {
    last_seen_ms: bigint;
    user: Principal;
    platform: [] | [string];
}): {
    last_seen_ms: bigint;
    user: Principal;
    platform?: string;
} {
    return {
        last_seen_ms: value.last_seen_ms,
        user: value.user,
        platform: record_opt_to_undefined(from_candid_opt_n5(value.platform))
    };
}
function from_candid_record_n57(value: {
    conversation_id: string;
    kind: string;
    name: string;
    team_id: [] | [string];
    description: [] | [string];
    is_member: boolean;
    member_count: number;
    club_id: [] | [string];
    avatar: [] | [string];
}): {
    conversation_id: string;
    kind: string;
    name: string;
    team_id?: string;
    description?: string;
    is_member: boolean;
    member_count: number;
    club_id?: string;
    avatar?: string;
} {
    return {
        conversation_id: value.conversation_id,
        kind: value.kind,
        name: value.name,
        team_id: record_opt_to_undefined(from_candid_opt_n5(value.team_id)),
        description: record_opt_to_undefined(from_candid_opt_n5(value.description)),
        is_member: value.is_member,
        member_count: value.member_count,
        club_id: record_opt_to_undefined(from_candid_opt_n5(value.club_id)),
        avatar: record_opt_to_undefined(from_candid_opt_n5(value.avatar))
    };
}
function from_candid_record_n62(value: {
    messages: Array<_Message>;
    latest_sequence: bigint;
    next_sequence: [] | [bigint];
}): {
    messages: Array<Message>;
    latest_sequence: bigint;
    next_sequence?: bigint;
} {
    return {
        messages: from_candid_vec_n29(value.messages),
        latest_sequence: value.latest_sequence,
        next_sequence: record_opt_to_undefined(from_candid_opt_n7(value.next_sequence))
    };
}
function from_candid_record_n71(value: {
    message: _Message;
    reactions: Array<_ReactionSummary>;
}): {
    message: Message;
    reactions: Array<ReactionSummary>;
} {
    return {
        message: from_candid_Message_n18(value.message),
        reactions: value.reactions
    };
}
function from_candid_record_n77(value: {
    last_message_sequence: bigint;
    conversation_id: string;
    kind: string;
    last_message_at_ms: [] | [bigint];
}): {
    last_message_sequence: bigint;
    conversation_id: string;
    kind: string;
    last_message_at_ms?: bigint;
} {
    return {
        last_message_sequence: value.last_message_sequence,
        conversation_id: value.conversation_id,
        kind: value.kind,
        last_message_at_ms: record_opt_to_undefined(from_candid_opt_n7(value.last_message_at_ms))
    };
}
function from_candid_variant_n1(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n13(value: {
    Ok: _Conversation;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Conversation;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Conversation_n14(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n16(value: {
    Ok: number;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: number;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n17(value: {
    Ok: _Message;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Message;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Message_n18(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n2(value: {
    Ok: _GroupMetadata;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: GroupMetadata;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_GroupMetadata_n3(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n23(value: {
    Ok: _State;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: State;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_State_n24(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n39(value: {
    Ok: _LinkPreview;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: LinkPreview;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_LinkPreview_n40(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n42(value: {
    Ok: string;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n43(value: {
    Ok: Array<[string, string]>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<[string, string]>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n44(value: {
    Ok: _PollResults;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: PollResults;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_PollResults_n45(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n47(value: {
    Ok: Array<Principal>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<Principal>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n48(value: {
    Ok: Array<_OnlineUser>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<OnlineUser>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n49(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n52(value: {
    Ok: Array<_ClubDmSettings>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<ClubDmSettings>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n53(value: {
    Ok: Array<_GroupMetadata>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<GroupMetadata>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n30(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n54(value: {
    Ok: Array<_GroupSummary>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<GroupSummary>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n55(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n58(value: {
    Ok: Array<_JoinRequest>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<JoinRequest>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n60(value: {
    Ok: _MessagePage;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: MessagePage;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_MessagePage_n61(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n63(value: {
    Ok: Array<_PinnedMessage>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<PinnedMessage>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n64(value: {
    Ok: Array<_Reaction>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<Reaction>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n65(value: {
    Ok: Array<_Receipt>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<Receipt>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n66(value: {
    Ok: Array<_TypingUser>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<TypingUser>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n67(value: {
    Ok: _Receipt;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Receipt;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n68(value: {
    Ok: Array<_MessageWithReactions>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<MessageWithReactions>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n69(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n72(value: {
    Ok: bigint;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n73(value: {
    Ok: _PinnedMessage;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: PinnedMessage;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n74(value: {
    Ok: Array<_RecentConversation>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<RecentConversation>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_vec_n75(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n78(value: {
    Ok: _AttachmentMetadata;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: AttachmentMetadata;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_AttachmentMetadata_n34(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n79(value: {
    Ok: _ScheduledMessage;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: ScheduledMessage;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_ScheduledMessage_n27(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n8(value: {
    Ok: _BroadcastResult;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: BroadcastResult;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n84(value: {
    Ok: _Unread;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Unread;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n85(value: {
    Ok: Array<_ClubUnreadSummary>;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Array<ClubUnreadSummary>;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n89(value: {
    Ok: _CanisterOutputCertifiedMessages;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: CanisterOutputCertifiedMessages;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n9(value: {
    Ok: _Poll;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Poll;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_Poll_n10(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n26(value: Array<_ScheduledMessage>): Array<ScheduledMessage> {
    return value.map((x)=>from_candid_ScheduledMessage_n27(x));
}
function from_candid_vec_n29(value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n18(x));
}
function from_candid_vec_n30(value: Array<_GroupMetadata>): Array<GroupMetadata> {
    return value.map((x)=>from_candid_GroupMetadata_n3(x));
}
function from_candid_vec_n31(value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n14(x));
}
function from_candid_vec_n32(value: Array<_Poll>): Array<Poll> {
    return value.map((x)=>from_candid_Poll_n10(x));
}
function from_candid_vec_n33(value: Array<_AttachmentMetadata>): Array<AttachmentMetadata> {
    return value.map((x)=>from_candid_AttachmentMetadata_n34(x));
}
function from_candid_vec_n36(value: Array<_RoleGrant>): Array<RoleGrant> {
    return value.map((x)=>from_candid_RoleGrant_n37(x));
}
function from_candid_vec_n49(value: Array<_OnlineUser>): Array<OnlineUser> {
    return value.map((x)=>from_candid_OnlineUser_n50(x));
}
function from_candid_vec_n55(value: Array<_GroupSummary>): Array<GroupSummary> {
    return value.map((x)=>from_candid_GroupSummary_n56(x));
}
function from_candid_vec_n69(value: Array<_MessageWithReactions>): Array<MessageWithReactions> {
    return value.map((x)=>from_candid_MessageWithReactions_n70(x));
}
function from_candid_vec_n75(value: Array<_RecentConversation>): Array<RecentConversation> {
    return value.map((x)=>from_candid_RecentConversation_n76(x));
}
function to_candid_Attachment_n81(value: Attachment): _Attachment {
    return to_candid_record_n82(value);
}
function to_candid_WsAppMessage_n91(value: WsAppMessage): _WsAppMessage {
    return to_candid_variant_n92(value);
}
function to_candid_opt_n12(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n59(value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n80(value: Attachment | null): [] | [_Attachment] {
    return value === null ? candid_none() : candid_some(to_candid_Attachment_n81(value));
}
function to_candid_opt_n83(value: RecapConfig | null): [] | [_RecapConfig] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n86(value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n90(value: WsAppMessage | null): [] | [_WsAppMessage] {
    return value === null ? candid_none() : candid_some(to_candid_WsAppMessage_n91(value));
}
function to_candid_record_n82(value: {
    url?: string;
    kind: string;
    ref_id: string;
}): {
    url: [] | [string];
    kind: string;
    ref_id: string;
} {
    return {
        url: value.url ? candid_some(value.url) : candid_none(),
        kind: value.kind,
        ref_id: value.ref_id
    };
}
function to_candid_variant_n92(value: {
    __kind__: "chat_poke";
    chat_poke: {
        conversation_id: string;
        sequence: bigint;
    };
}): {
    chat_poke: {
        conversation_id: string;
        sequence: bigint;
    };
} {
    return value.__kind__ === "chat_poke" ? {
        chat_poke: value.chat_poke
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Messaging_domain {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Messaging_domain(actor);
}
