/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'id' : string,
  'storage_path' : string,
  'retention_until_ms' : bigint,
  'album_id' : [] | [string],
  'deleted' : boolean,
  'mini_league_id' : [] | [string],
  'owner' : Principal,
  'kind' : string,
  'mime' : string,
  'team_id' : [] | [string],
  'encrypted' : boolean,
  'created_at_ms' : bigint,
  'blob_ref' : [] | [BlobRef],
  'content_length' : bigint,
  'caption' : [] | [string],
  'checksum' : string,
  'child_sensitive' : boolean,
  'event_id' : [] | [string],
  'visibility' : string,
  'competition_id' : [] | [string],
  'club_id' : string,
  'expires_at_ms' : bigint,
}
export interface BlobRef {
  'path' : string,
  'content_hash' : string,
  'canister' : string,
}
export interface Capability {
  'action' : string,
  'owner' : Principal,
  'allowed' : boolean,
  'asset_id' : string,
  'purpose' : string,
  'expires_at_ms' : bigint,
}
export interface Comment {
  'id' : string,
  'deleted' : boolean,
  'body' : string,
  'author' : Principal,
  'created_at_ms' : bigint,
  'asset_id' : string,
}
export interface GalleryChatCard {
  'id' : string,
  'uploader_id' : Principal,
  'photo_ids' : Array<string>,
  'photo_count' : number,
  'hero_image_url' : [] | [string],
  'is_prompt' : boolean,
  'team_id' : string,
  'updated_at_ms' : bigint,
  'created_at_ms' : bigint,
  'push_sent' : boolean,
  'hero_photo_id' : [] | [string],
  'event_id' : [] | [string],
  'message_id' : string,
  'club_id' : string,
}
export interface Main {
  'addBulkAccessPrincipal' : ActorMethod<
    [Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'add_comment' : ActorMethod<
    [string, string, bigint],
    { 'Ok' : Comment } |
      { 'Err' : string }
  >,
  'add_reaction' : ActorMethod<
    [string, string, bigint],
    { 'Ok' : Reaction } |
      { 'Err' : string }
  >,
  /**
   * / Public: remaining cycles (shown in admin settings).
   */
  'cycles_balance' : ActorMethod<[], bigint>,
  'delete_asset' : ActorMethod<[string], { 'Ok' : Asset } | { 'Err' : string }>,
  'delete_comment' : ActorMethod<
    [string],
    { 'Ok' : Comment } |
      { 'Err' : string }
  >,
  'delete_gallery_chat_card' : ActorMethod<
    [string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'export_state' : ActorMethod<[], { 'Ok' : State } | { 'Err' : string }>,
  'get_asset' : ActorMethod<[string], [] | [Asset]>,
  'get_gallery_chat_card' : ActorMethod<[string], [] | [GalleryChatCard]>,
  'grant_role' : ActorMethod<
    [Principal, string, [] | [string], [] | [string]],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'issue_capability' : ActorMethod<
    [string, string, string, bigint],
    { 'Ok' : Capability } |
      { 'Err' : string }
  >,
  'listBulkAccessPrincipals' : ActorMethod<
    [],
    { 'Ok' : Array<Principal> } |
      { 'Err' : string }
  >,
  'list_assets' : ActorMethod<[string], Array<Asset>>,
  'list_comments' : ActorMethod<[string], Array<Comment>>,
  'list_gallery_chat_cards' : ActorMethod<
    [string, string],
    Array<GalleryChatCard>
  >,
  'list_reactions' : ActorMethod<[string], Array<Reaction>>,
  'register_asset' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    { 'Ok' : Asset } |
      { 'Err' : string }
  >,
  'removeBulkAccessPrincipal' : ActorMethod<
    [Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'remove_reaction' : ActorMethod<
    [string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'save_gallery_chat_card' : ActorMethod<
    [
      [] | [string],
      string,
      string,
      [] | [string],
      string,
      [] | [string],
      [] | [string],
      number,
      Array<string>,
      boolean,
      boolean,
    ],
    { 'Ok' : GalleryChatCard } |
      { 'Err' : string }
  >,
  'set_asset_scope' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    { 'Ok' : Asset } |
      { 'Err' : string }
  >,
  'set_blob_ref' : ActorMethod<
    [string, [] | [BlobRef]],
    { 'Ok' : Asset } |
      { 'Err' : string }
  >,
  'transfer_governorship' : ActorMethod<
    [Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
}
export interface Reaction {
  'kind' : string,
  'user' : Principal,
  'created_at_ms' : bigint,
  'asset_id' : string,
}
export interface RoleGrant {
  'role' : string,
  'user' : Principal,
  'team_id' : [] | [string],
  'club_id' : [] | [string],
}
export interface State {
  'capabilities' : Array<Capability>,
  'schema' : number,
  'assets' : Array<Asset>,
  'governor' : Principal,
  'comments' : Array<Comment>,
  'galleryChatCards' : Array<GalleryChatCard>,
  'reactions' : Array<Reaction>,
  'roles' : Array<RoleGrant>,
}
export interface _SERVICE extends Main {}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];