/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attachment {
  'url' : [] | [string],
  'kind' : string,
  'ref_id' : string,
}
export interface BroadcastResult {
  'skipped' : Array<string>,
  'delivered' : number,
}
export interface ClubMembership { 'user' : Principal, 'club_id' : string }
export interface CompetitionAdmin {
  'conversation_id' : string,
  'user' : Principal,
}
export interface Conversation {
  'id' : string,
  'participants' : Array<Principal>,
  'team_id' : [] | [string],
  'next_sequence' : bigint,
  'club_id' : string,
}
export interface GroupMetadata {
  'members' : Array<Principal>,
  'conversation_id' : string,
  'kind' : string,
  'name' : string,
  'team_id' : [] | [string],
  'created_at_ms' : bigint,
  'club_id' : [] | [string],
}
export interface Message {
  'id' : string,
  'conversation_id' : string,
  'body' : string,
  'sender' : Principal,
  'edited_at_ms' : [] | [bigint],
  'attachment' : [] | [Attachment],
  'sequence' : bigint,
  'idempotency_key' : string,
}
export interface MessagePage {
  'messages' : Array<Message>,
  'latest_sequence' : bigint,
  'next_sequence' : [] | [bigint],
}
export interface Receipt {
  'conversation_id' : string,
  'read' : boolean,
  'user' : Principal,
  'message_id' : string,
}
export interface RoleGrant {
  'role' : string,
  'user' : Principal,
  'team_id' : [] | [string],
  'club_id' : [] | [string],
}
export interface State {
  'messages' : Array<Message>,
  'schema' : number,
  'dmAttachmentsDisabled' : Array<Principal>,
  'unread' : Array<Unread>,
  'groupMetadata' : Array<GroupMetadata>,
  'clubMemberships' : Array<ClubMembership>,
  'governor' : Principal,
  'conversations' : Array<Conversation>,
  'receipts' : Array<Receipt>,
  'roles' : Array<RoleGrant>,
  'competitionAdmins' : Array<CompetitionAdmin>,
}
export interface Unread {
  'conversation_id' : string,
  'count' : bigint,
  'user' : Principal,
  'last_read_sequence' : bigint,
}
export interface UnreadSummary {
  'conversation_id' : string,
  'kind' : string,
  'count' : bigint,
}
export interface _SERVICE {
  'addBulkAccessPrincipal' : ActorMethod<
    [Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'broadcast_announcement' : ActorMethod<
    [string, Array<string>, boolean, string, string],
    { 'Ok' : BroadcastResult } |
      { 'Err' : string }
  >,
  'can_dm_user' : ActorMethod<[Principal], boolean>,
  'create_conversation' : ActorMethod<
    [string, [] | [string], Array<Principal>],
    { 'Ok' : Conversation } |
      { 'Err' : string }
  >,
  'delete_message' : ActorMethod<
    [string],
    { 'Ok' : Message } |
      { 'Err' : string }
  >,
  'dm_attachments_disabled' : ActorMethod<[Principal], boolean>,
  'export_state' : ActorMethod<[], { 'Ok' : State } | { 'Err' : string }>,
  'get_group_metadata' : ActorMethod<
    [string],
    { 'Ok' : GroupMetadata } |
      { 'Err' : string }
  >,
  'grant_competition_admin' : ActorMethod<
    [string, Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'grant_role' : ActorMethod<
    [Principal, string, [] | [string], [] | [string]],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'initialize' : ActorMethod<[], { 'Ok' : null } | { 'Err' : string }>,
  'is_competition_admin' : ActorMethod<[string], boolean>,
  'listBulkAccessPrincipals' : ActorMethod<
    [],
    { 'Ok' : Array<Principal> } |
      { 'Err' : string }
  >,
  'list_messages' : ActorMethod<[string, [] | [bigint]], Array<Message>>,
  'list_messages_page' : ActorMethod<
    [string, [] | [bigint], number],
    { 'Ok' : MessagePage } |
      { 'Err' : string }
  >,
  'mark_read' : ActorMethod<
    [string, string],
    { 'Ok' : Receipt } |
      { 'Err' : string }
  >,
  'my_unread_counts' : ActorMethod<[], Array<UnreadSummary>>,
  'removeBulkAccessPrincipal' : ActorMethod<
    [Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'send_message' : ActorMethod<
    [string, string, string, [] | [Attachment]],
    { 'Ok' : Message } |
      { 'Err' : string }
  >,
  'set_dm_attachments_disabled' : ActorMethod<
    [Principal, boolean],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'unread_count' : ActorMethod<
    [string],
    { 'Ok' : Unread } |
      { 'Err' : string }
  >,
  'update_message' : ActorMethod<
    [string, string],
    { 'Ok' : Message } |
      { 'Err' : string }
  >,
  'upsert_club_membership' : ActorMethod<
    [Principal, string],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'upsert_group_metadata' : ActorMethod<
    [string, string, string, [] | [string], [] | [string], Array<Principal>],
    { 'Ok' : GroupMetadata } |
      { 'Err' : string }
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];