/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Account = IDL.Record({
    'id' : IDL.Text,
    'legacy_subject' : IDL.Principal,
    'version' : IDL.Nat64,
    'principals' : IDL.Vec(IDL.Principal),
  });
  const ParentInvite = IDL.Record({
    'id' : IDL.Text,
    'accepted_by' : IDL.Opt(IDL.Principal),
    'team_id' : IDL.Opt(IDL.Text),
    'child_id' : IDL.Text,
    'created_at_ms' : IDL.Nat64,
    'invited_by' : IDL.Principal,
    'club_id' : IDL.Text,
    'expires_at_ms' : IDL.Nat64,
  });
  const PendingInvite = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'kind' : IDL.Text,
    'resent_at_ms' : IDL.Opt(IDL.Nat64),
    'role' : IDL.Opt(IDL.Text),
    'accepted_by' : IDL.Opt(IDL.Principal),
    'team_id' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'child_id' : IDL.Opt(IDL.Text),
    'created_at_ms' : IDL.Nat64,
    'accepted_at_ms' : IDL.Opt(IDL.Nat64),
    'invited_by' : IDL.Principal,
    'club_id' : IDL.Text,
  });
  const TeamInvite = IDL.Record({
    'id' : IDL.Text,
    'revoked' : IDL.Bool,
    'role' : IDL.Text,
    'accepted_by' : IDL.Opt(IDL.Principal),
    'team_id' : IDL.Text,
    'email' : IDL.Text,
    'created_at_ms' : IDL.Nat64,
    'invited_by' : IDL.Principal,
    'club_id' : IDL.Text,
    'expires_at_ms' : IDL.Nat64,
  });
  const TeamInviteLink = IDL.Record({
    'id' : IDL.Text,
    'token' : IDL.Text,
    'revoked' : IDL.Bool,
    'role' : IDL.Text,
    'rotated_at_ms' : IDL.Opt(IDL.Nat64),
    'team_id' : IDL.Text,
    'created_by' : IDL.Principal,
    'created_at_ms' : IDL.Nat64,
    'club_id' : IDL.Text,
  });
  const Child = IDL.Record({
    'id' : IDL.Text,
    'teams' : IDL.Vec(IDL.Text),
    'club_id' : IDL.Opt(IDL.Text),
    'parent' : IDL.Opt(IDL.Principal),
  });
  const ClubJoinRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'decided_at_ms' : IDL.Opt(IDL.Nat64),
    'user' : IDL.Principal,
    'created_at_ms' : IDL.Nat64,
    'club_id' : IDL.Text,
    'decided_by' : IDL.Opt(IDL.Principal),
  });
  const RoleRequest = IDL.Record({
    'id' : IDL.Text,
    'account_id' : IDL.Text,
    'status' : IDL.Text,
    'decided_at_ms' : IDL.Opt(IDL.Nat64),
    'club' : IDL.Text,
    'role' : IDL.Text,
    'team' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
    'created_at_ms' : IDL.Nat64,
    'decided_by' : IDL.Opt(IDL.Principal),
  });
  const TeamCreationRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'decided_at_ms' : IDL.Opt(IDL.Nat64),
    'name' : IDL.Text,
    'division' : IDL.Opt(IDL.Text),
    'team_id' : IDL.Opt(IDL.Text),
    'requested_by' : IDL.Principal,
    'created_at_ms' : IDL.Nat64,
    'club_id' : IDL.Text,
    'decided_by' : IDL.Opt(IDL.Principal),
    'age_group' : IDL.Opt(IDL.Text),
  });
  const ClubTeam = IDL.Record({
    'id' : IDL.Text,
    'playhq_team_id' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'division' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'team_type' : IDL.Opt(IDL.Text),
    'logo_url' : IDL.Opt(IDL.Text),
    'shell_invited_by' : IDL.Opt(IDL.Principal),
    'shell_contact_name' : IDL.Opt(IDL.Text),
    'shell_claim_token' : IDL.Opt(IDL.Text),
    'is_shell' : IDL.Bool,
    'gender' : IDL.Opt(IDL.Text),
    'shell_claimed_at_ms' : IDL.Opt(IDL.Nat64),
    'is_active' : IDL.Bool,
    'playhq_auto_create_events' : IDL.Bool,
    'playhq_competition_id' : IDL.Opt(IDL.Text),
    'folder_id' : IDL.Opt(IDL.Text),
    'shell_contact_email' : IDL.Opt(IDL.Text),
    'shell_claimed_by' : IDL.Opt(IDL.Principal),
    'club_id' : IDL.Text,
    'archived' : IDL.Bool,
    'age_group' : IDL.Opt(IDL.Text),
    'deleted_at_ms' : IDL.Opt(IDL.Nat64),
  });
  const Challenge = IDL.Record({
    'id' : IDL.Nat64,
    'account_id' : IDL.Text,
    'issuer' : IDL.Principal,
    'target' : IDL.Principal,
    'accepted' : IDL.Bool,
    'expires_at_ns' : IDL.Nat64,
    'expected_version' : IDL.Nat64,
  });
  const ClubSettings = IDL.Record({
    'logo_only_mode' : IDL.Bool,
    'invite_email_style' : IDL.Opt(IDL.Text),
    'theme_dark_accent_color' : IDL.Opt(IDL.Text),
    'theme_primary_color' : IDL.Opt(IDL.Text),
    'events_sponsor_strip_enabled' : IDL.Bool,
    'header_logo_enabled' : IDL.Bool,
    'chat_thread_ads_enabled' : IDL.Bool,
    'theme_accent_color' : IDL.Opt(IDL.Text),
    'contact_email' : IDL.Opt(IDL.Text),
    'club_switcher_hint' : IDL.Opt(IDL.Text),
    'theme_dark_primary_color' : IDL.Opt(IDL.Text),
    'header_club_name_enabled' : IDL.Bool,
    'membership_open' : IDL.Bool,
    'announcement' : IDL.Opt(IDL.Text),
    'public_directory' : IDL.Bool,
    'theme_secondary_color' : IDL.Opt(IDL.Text),
    'media_header_sponsors_enabled' : IDL.Bool,
    'theme_dark_secondary_color' : IDL.Opt(IDL.Text),
    'media_sponsors_enabled' : IDL.Bool,
    'club_id' : IDL.Text,
    'theme_enabled' : IDL.Bool,
  });
  const ClubProfile = IDL.Record({
    'id' : IDL.Text,
    'secondary_color' : IDL.Opt(IDL.Text),
    'playhq_tenant' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'created_at_ms' : IDL.Nat64,
    'logo_url' : IDL.Opt(IDL.Text),
    'sport' : IDL.Opt(IDL.Text),
    'playhq_org_id' : IDL.Opt(IDL.Text),
    'is_active' : IDL.Bool,
    'primary_color' : IDL.Opt(IDL.Text),
    'deleted_at_ms' : IDL.Opt(IDL.Nat64),
  });
  const NewsAttachment = IDL.Record({
    'url' : IDL.Text,
    'kind' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Nat64,
    'mime_type' : IDL.Opt(IDL.Text),
    'anchor' : IDL.Opt(IDL.Text),
  });
  const NewsPost = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'target_team_ids' : IDL.Opt(IDL.Vec(IDL.Text)),
    'image_url' : IDL.Opt(IDL.Text),
    'body' : IDL.Text,
    'updated_at_ms' : IDL.Nat64,
    'created_by' : IDL.Principal,
    'created_at_ms' : IDL.Nat64,
    'is_important' : IDL.Bool,
    'revision' : IDL.Nat64,
    'club_id' : IDL.Text,
    'attachments' : IDL.Vec(NewsAttachment),
  });
  const InvitePayload = IDL.Record({
    'to' : IDL.Text,
    'subject' : IDL.Text,
    'body' : IDL.Text,
  });
  const Team = IDL.Record({ 'id' : IDL.Text, 'club' : IDL.Text });
  const Guardian = IDL.Record({ 'child' : IDL.Text, 'user' : IDL.Principal });
  const Exclusion = IDL.Record({ 'club' : IDL.Text, 'user' : IDL.Principal });
  const RoleGrant = IDL.Record({
    'club' : IDL.Opt(IDL.Text),
    'role' : IDL.Text,
    'team' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
  });
  const Acl = IDL.Record({
    'teams' : IDL.Vec(Team),
    'guardians' : IDL.Vec(Guardian),
    'clubs' : IDL.Vec(IDL.Text),
    'children' : IDL.Vec(Child),
    'exclusions' : IDL.Vec(Exclusion),
    'roles' : IDL.Vec(RoleGrant),
  });
  const Config = IDL.Record({
    'acl' : Acl,
    'schema' : IDL.Nat32,
    'governor' : IDL.Principal,
    'acl_version' : IDL.Nat64,
  });
  const Draft = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'is_active' : IDL.Bool,
    'open_mode' : IDL.Text,
    'subtitle' : IDL.Opt(IDL.Text),
  });
  const Link = IDL.Record({
    'id' : IDL.Text,
    'sort_order' : IDL.Nat32,
    'created_at_ms' : IDL.Nat64,
    'draft' : Draft,
    'club_id' : IDL.Text,
  });
  const Listing = IDL.Record({
    'links' : IDL.Vec(Link),
    'revision' : IDL.Nat64,
  });
  const AccountExclusion = IDL.Record({
    'account_id' : IDL.Text,
    'club' : IDL.Text,
  });
  const Family = IDL.Record({ 'account_id' : IDL.Text, 'child_id' : IDL.Text });
  const AccountRole = IDL.Record({
    'account_id' : IDL.Text,
    'club' : IDL.Opt(IDL.Text),
    'role' : IDL.Text,
    'team' : IDL.Opt(IDL.Text),
  });
  const State = IDL.Record({
    'schema' : IDL.Nat32,
    'accounts' : IDL.Vec(Account),
    'exclusions' : IDL.Vec(AccountExclusion),
    'families' : IDL.Vec(Family),
    'challenges' : IDL.Vec(Challenge),
    'roles' : IDL.Vec(AccountRole),
    'next_challenge' : IDL.Nat64,
  });
  const Snapshot = IDL.Record({
    'schema' : IDL.Nat32,
    'clubs' : IDL.Vec(IDL.Tuple(IDL.Text, Listing)),
  });
  const ClubBranding = IDL.Record({
    'name' : IDL.Text,
    'contact_email' : IDL.Opt(IDL.Text),
    'logo_url' : IDL.Opt(IDL.Text),
  });
  const ClubSubscription = IDL.Record({
    'activated_at_ms' : IDL.Opt(IDL.Nat64),
    'trial_ends_at_ms' : IDL.Opt(IDL.Nat64),
    'team_limit' : IDL.Opt(IDL.Nat32),
    'is_trial' : IDL.Bool,
    'plan' : IDL.Text,
    'is_pro' : IDL.Bool,
    'is_pro_football' : IDL.Bool,
    'admin_pro_football_override' : IDL.Bool,
    'admin_pro_override' : IDL.Bool,
    'cancelled_at_ms' : IDL.Opt(IDL.Nat64),
    'club_id' : IDL.Text,
    'expires_at_ms' : IDL.Opt(IDL.Nat64),
  });
  const Season = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'updated_at_ms' : IDL.Nat64,
    'end_date' : IDL.Text,
    'created_at_ms' : IDL.Nat64,
    'start_date' : IDL.Text,
    'club_id' : IDL.Text,
  });
  const ClubSponsor = IDL.Record({
    'id' : IDL.Text,
    'website_url' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'sort_order' : IDL.Nat32,
    'description' : IDL.Opt(IDL.Text),
    'logo_url' : IDL.Opt(IDL.Text),
    'is_team_only' : IDL.Bool,
    'is_active' : IDL.Bool,
    'club_id' : IDL.Text,
    'exposure_percentage' : IDL.Opt(IDL.Nat8),
  });
  const TeamPlayerPosition = IDL.Record({
    'team_id' : IDL.Text,
    'member_id' : IDL.Text,
    'position' : IDL.Text,
  });
  const TeamSubscription = IDL.Record({
    'max_spread_minutes' : IDL.Opt(IDL.Nat32),
    'formation' : IDL.Opt(IDL.Text),
    'trial_ends_at_ms' : IDL.Opt(IDL.Nat64),
    'is_trial' : IDL.Bool,
    'rotate_gk_at_halftime' : IDL.Bool,
    'show_lineup_picker' : IDL.Bool,
    'team_id' : IDL.Text,
    'rotation_speed' : IDL.Nat32,
    'is_pro' : IDL.Bool,
    'disable_auto_subs' : IDL.Bool,
    'team_size' : IDL.Opt(IDL.Nat32),
    'is_pro_football' : IDL.Bool,
    'admin_pro_football_override' : IDL.Bool,
    'disable_batch_subs' : IDL.Bool,
    'admin_pro_override' : IDL.Bool,
    'cancelled_at_ms' : IDL.Opt(IDL.Nat64),
    'minutes_per_half' : IDL.Opt(IDL.Nat32),
    'disable_position_swaps' : IDL.Bool,
    'disable_team_pom_rewards' : IDL.Bool,
  });
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'status_code' : IDL.Nat16,
  });
  const InviteStats = IDL.Record({ 'total' : IDL.Nat, 'accepted' : IDL.Nat });
  const AcceptedInvite = IDL.Record({
    'id' : IDL.Text,
    'invited_user_id' : IDL.Text,
    'accepted_at_ms' : IDL.Nat64,
  });
  const ClubTerm = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'end_date' : IDL.Text,
    'created_at_ms' : IDL.Nat64,
    'start_date' : IDL.Text,
    'is_active' : IDL.Bool,
    'club_id' : IDL.Text,
  });
  const MemberPayment = IDL.Record({
    'id' : IDL.Text,
    'payment_type' : IDL.Text,
    'marked_by' : IDL.Principal,
    'user_id' : IDL.Text,
    'child_id' : IDL.Opt(IDL.Text),
    'created_at_ms' : IDL.Nat64,
    'notes' : IDL.Opt(IDL.Text),
    'payment_period' : IDL.Text,
    'amount' : IDL.Float64,
    'club_id' : IDL.Text,
  });
  const RemovedMember = IDL.Record({
    'club' : IDL.Text,
    'user' : IDL.Principal,
    'removed_at_ms' : IDL.Nat64,
    'removed_by' : IDL.Principal,
  });
  const SeasonPlayerStat = IDL.Record({
    'season_id' : IDL.Text,
    'team_id' : IDL.Text,
    'updated_at_ms' : IDL.Nat64,
    'player_name' : IDL.Text,
    'club_player_id' : IDL.Text,
    'events_total' : IDL.Nat32,
    'attendance_pct' : IDL.Float64,
    'events_attended' : IDL.Nat32,
    'games_played' : IDL.Nat32,
    'club_id' : IDL.Text,
  });
  const SeasonTeamSummary = IDL.Record({
    'season_id' : IDL.Text,
    'avg_attendance_pct' : IDL.Float64,
    'team_id' : IDL.Text,
    'updated_at_ms' : IDL.Nat64,
    'roster_size' : IDL.Nat32,
    'team_name' : IDL.Text,
    'events_count' : IDL.Nat32,
    'club_id' : IDL.Text,
  });
  const TeamCaptain = IDL.Record({
    'user' : IDL.Principal,
    'team_id' : IDL.Text,
  });
  const TeamFolder = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'sort_order' : IDL.Nat32,
    'description' : IDL.Opt(IDL.Text),
    'created_by' : IDL.Principal,
    'created_at_ms' : IDL.Nat64,
    'club_id' : IDL.Text,
  });
  const TeamSponsorAllocation = IDL.Record({
    'team_id' : IDL.Text,
    'sponsor_id' : IDL.Text,
  });
  const Operation = IDL.Variant({
    'SetActive' : IDL.Record({ 'id' : IDL.Text, 'active' : IDL.Bool }),
    'Save' : IDL.Record({ 'id' : IDL.Opt(IDL.Text), 'draft' : Draft }),
    'Remove' : IDL.Record({ 'id' : IDL.Text }),
    'Reorder' : IDL.Record({ 'first' : IDL.Text, 'second' : IDL.Text }),
  });
  const Request = IDL.Record({
    'request_id' : IDL.Text,
    'club' : IDL.Text,
    'operation' : Operation,
    'expected_revision' : IDL.Nat64,
  });
  const Mutation = IDL.Record({
    'link' : IDL.Opt(Link),
    'revision' : IDL.Nat64,
  });
  const ProfileTeamHistoryEntry = IDL.Record({
    'season_start_date' : IDL.Text,
    'season_id' : IDL.Text,
    'team_id' : IDL.Text,
    'season_name' : IDL.Text,
    'team_level_age' : IDL.Opt(IDL.Text),
    'team_name' : IDL.Text,
    'joined_at_ms' : IDL.Nat64,
    'membership_id' : IDL.Text,
    'season_end_date' : IDL.Text,
    'club_name' : IDL.Text,
    'club_id' : IDL.Text,
    'season_status' : IDL.Text,
  });
  const Main = IDL.Service({
    'accept_identity_link' : IDL.Func(
        [IDL.Nat64],
        [IDL.Variant({ 'Ok' : Account, 'Err' : IDL.Text })],
        [],
      ),
    'accept_parent_invite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ParentInvite, 'Err' : IDL.Text })],
        [],
      ),
    'accept_pending_invite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : PendingInvite, 'Err' : IDL.Text })],
        [],
      ),
    'accept_team_invite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : TeamInvite, 'Err' : IDL.Text })],
        [],
      ),
    'accept_team_invite_link' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : TeamInviteLink, 'Err' : IDL.Text })],
        [],
      ),
    'add_role_grant' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'add_team_captain' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'admin_link_child_to_parent' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Variant({ 'Ok' : Child, 'Err' : IDL.Text })],
        [],
      ),
    'approve_club_join_request' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ClubJoinRequest, 'Err' : IDL.Text })],
        [],
      ),
    'approve_role_request' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : RoleRequest, 'Err' : IDL.Text })],
        [],
      ),
    'approve_team_creation_request' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : TeamCreationRequest, 'Err' : IDL.Text })],
        [],
      ),
    'archive_team' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ClubTeam, 'Err' : IDL.Text })],
        [],
      ),
    'begin_identity_link' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'Ok' : Challenge, 'Err' : IDL.Text })],
        [],
      ),
    'bulk_add_team_members' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Principal)],
        [IDL.Variant({ 'Ok' : IDL.Nat, 'Err' : IDL.Text })],
        [],
      ),
    'check_team_name_unique' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Bool, 'Err' : IDL.Text })],
        ['query'],
      ),
    'claim_shell_team' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ClubTeam, 'Err' : IDL.Text })],
        [],
      ),
    'clear_club_theme' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ClubSettings, 'Err' : IDL.Text })],
        [],
      ),
    'create_child_for_parent_in_club' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Variant({ 'Ok' : Child, 'Err' : IDL.Text })],
        [],
      ),
    'create_child_for_parent_on_team' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal],
        [IDL.Variant({ 'Ok' : Child, 'Err' : IDL.Text })],
        [],
      ),
    'create_club' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : ClubProfile, 'Err' : IDL.Text })],
        [],
      ),
    'create_news_post' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Vec(NewsAttachment),
        ],
        [IDL.Variant({ 'Ok' : NewsPost, 'Err' : IDL.Text })],
        [],
      ),
    'create_parent_invite' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Variant({ 'Ok' : ParentInvite, 'Err' : IDL.Text })],
        [],
      ),
    'create_pending_invite' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [
          IDL.Variant({
            'Ok' : IDL.Record({
              'invite' : PendingInvite,
              'payload' : InvitePayload,
            }),
            'Err' : IDL.Text,
          }),
        ],
        [],
      ),
    'create_shell_team_invite' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : ClubTeam, 'Err' : IDL.Text })],
        [],
      ),
    'create_team_invite' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : TeamInvite, 'Err' : IDL.Text })],
        [],
      ),
    'create_team_invite_link' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : TeamInviteLink, 'Err' : IDL.Text })],
        [],
      ),
    'delete_club_permanent' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'delete_club_term' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'delete_news_post' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'delete_sponsor' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'delete_team_folder' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'delete_team_permanent' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'ensure_club_conversations' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Nat32, 'Err' : IDL.Text })],
        [],
      ),
    'export_acl' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : Config, 'Err' : IDL.Text })],
        ['query'],
      ),
    'export_frozen_club' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : Listing, 'Err' : IDL.Text })],
        ['query'],
      ),
    'export_identity_state' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : State, 'Err' : IDL.Text })],
        ['query'],
      ),
    'export_links' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : Snapshot, 'Err' : IDL.Text })],
        ['query'],
      ),
    'freeze_club' : IDL.Func(
        [IDL.Text, IDL.Nat64],
        [IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : IDL.Text })],
        [],
      ),
    'get_app_config' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'get_club_branding' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ClubBranding, 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_club_link' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Opt(Link), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_club_profile' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Opt(ClubProfile), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_club_profiles' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Vec(ClubProfile), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_club_settings' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Opt(ClubSettings), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_club_subscription' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Opt(ClubSubscription), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_club_subscriptions' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Vec(ClubSubscription), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_current_season' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Opt(Season), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_link' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : Listing, 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_my_theme_preference' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Opt(IDL.Text), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_parent_invite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ParentInvite, 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_pending_invite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : PendingInvite, 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_shell_team_by_token' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ClubTeam, 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_sponsor' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Opt(ClubSponsor), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_team' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Opt(ClubTeam), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_team_invite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : TeamInvite, 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_team_invite_link_by_token' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : TeamInviteLink, 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_team_player_positions' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(TeamPlayerPosition), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_team_subscription' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Opt(TeamSubscription), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_team_subscriptions' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Vec(TeamSubscription), 'Err' : IDL.Text })],
        ['query'],
      ),
    'get_teams' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Vec(ClubTeam), 'Err' : IDL.Text })],
        ['query'],
      ),
    'has_club_staff_role' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'import_frozen_club' : IDL.Func(
        [IDL.Text, Listing],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'import_links' : IDL.Func(
        [Snapshot],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'invite_stats' : IDL.Func(
        [IDL.Text, IDL.Nat64, IDL.Nat64],
        [IDL.Variant({ 'Ok' : InviteStats, 'Err' : IDL.Text })],
        ['query'],
      ),
    'is_app_admin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'is_member_removed' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'link_guardian' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'list_accepted_invites' : IDL.Func(
        [IDL.Text, IDL.Nat64, IDL.Nat64],
        [IDL.Variant({ 'Ok' : IDL.Vec(AcceptedInvite), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_all_sponsors' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Vec(ClubSponsor), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_children' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Vec(Child), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_club_admins' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'list_club_join_requests' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(ClubJoinRequest), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_club_terms' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(ClubTerm), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_clubs' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat16],
        [IDL.Variant({ 'Ok' : IDL.Vec(ClubProfile), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_links' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'Ok' : Listing, 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_member_payments' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(MemberPayment), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_news' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(NewsPost), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_news_multi' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Vec(NewsPost), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_pending_invites_by_club' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(PendingInvite), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_removed_members' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(RemovedMember), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_role_grants' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(AccountRole), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_role_requests' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(RoleRequest), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_season_player_stats' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(SeasonPlayerStat), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_season_team_summary' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(SeasonTeamSummary), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_seasons' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(Season), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_sponsors' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(ClubSponsor), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_team_captains' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(TeamCaptain), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_team_creation_requests' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'Ok' : IDL.Vec(TeamCreationRequest),
            'Err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'list_team_folders' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(TeamFolder), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_team_invites' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Vec(TeamInvite), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_team_role_grants' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(AccountRole), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_team_sponsor_allocations' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'Ok' : IDL.Vec(TeamSponsorAllocation),
            'Err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'list_teams' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Vec(ClubTeam), 'Err' : IDL.Text })],
        ['query'],
      ),
    'list_teams_multi' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Vec(ClubTeam), 'Err' : IDL.Text })],
        ['query'],
      ),
    'mark_member_paid' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'Ok' : MemberPayment, 'Err' : IDL.Text })],
        [],
      ),
    'move_child_to_team' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Variant({ 'Ok' : Child, 'Err' : IDL.Text })],
        [],
      ),
    'move_member_to_team' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'mutate' : IDL.Func(
        [Request],
        [IDL.Variant({ 'Ok' : Mutation, 'Err' : IDL.Text })],
        [],
      ),
    'my_role_grants' : IDL.Func([], [IDL.Vec(RoleGrant)], ['query']),
    'profile_team_history' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProfileTeamHistoryEntry)],
        ['query'],
      ),
    'purge_expired_deletions' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : IDL.Nat32, 'Err' : IDL.Text })],
        [],
      ),
    'reject_club_join_request' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ClubJoinRequest, 'Err' : IDL.Text })],
        [],
      ),
    'reject_role_request' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : RoleRequest, 'Err' : IDL.Text })],
        [],
      ),
    'reject_team_creation_request' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : TeamCreationRequest, 'Err' : IDL.Text })],
        [],
      ),
    'remove_member' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'remove_role_grant' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'remove_team_captain' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'replace_acl' : IDL.Func(
        [IDL.Nat64, Acl],
        [IDL.Variant({ 'Ok' : IDL.Nat64, 'Err' : IDL.Text })],
        [],
      ),
    'request_club_join' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ClubJoinRequest, 'Err' : IDL.Text })],
        [],
      ),
    'request_role' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : RoleRequest, 'Err' : IDL.Text })],
        [],
      ),
    'request_team_creation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : TeamCreationRequest, 'Err' : IDL.Text })],
        [],
      ),
    'resend_pending_invite' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'Ok' : IDL.Record({
              'invite' : PendingInvite,
              'payload' : InvitePayload,
            }),
            'Err' : IDL.Text,
          }),
        ],
        [],
      ),
    'restore_club' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'Ok' : ClubProfile, 'Err' : IDL.Text })],
        [],
      ),
    'restore_member' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'restore_team' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ClubTeam, 'Err' : IDL.Text })],
        [],
      ),
    'revoke_identity' : IDL.Func(
        [IDL.Principal, IDL.Nat64],
        [IDL.Variant({ 'Ok' : Account, 'Err' : IDL.Text })],
        [],
      ),
    'revoke_pending_invite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'revoke_team_invite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'revoke_team_invite_link' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'rotate_team_invite_link' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : TeamInviteLink, 'Err' : IDL.Text })],
        [],
      ),
    'save_club_profile' : IDL.Func(
        [ClubProfile],
        [IDL.Variant({ 'Ok' : ClubProfile, 'Err' : IDL.Text })],
        [],
      ),
    'save_club_settings' : IDL.Func(
        [ClubSettings],
        [IDL.Variant({ 'Ok' : ClubSettings, 'Err' : IDL.Text })],
        [],
      ),
    'save_club_subscription' : IDL.Func(
        [ClubSubscription],
        [IDL.Variant({ 'Ok' : ClubSubscription, 'Err' : IDL.Text })],
        [],
      ),
    'save_club_term' : IDL.Func(
        [ClubTerm],
        [IDL.Variant({ 'Ok' : ClubTerm, 'Err' : IDL.Text })],
        [],
      ),
    'save_season' : IDL.Func(
        [Season],
        [IDL.Variant({ 'Ok' : Season, 'Err' : IDL.Text })],
        [],
      ),
    'save_season_player_stat' : IDL.Func(
        [SeasonPlayerStat],
        [IDL.Variant({ 'Ok' : SeasonPlayerStat, 'Err' : IDL.Text })],
        [],
      ),
    'save_season_team_summary' : IDL.Func(
        [SeasonTeamSummary],
        [IDL.Variant({ 'Ok' : SeasonTeamSummary, 'Err' : IDL.Text })],
        [],
      ),
    'save_sponsor' : IDL.Func(
        [ClubSponsor],
        [IDL.Variant({ 'Ok' : ClubSponsor, 'Err' : IDL.Text })],
        [],
      ),
    'save_team' : IDL.Func(
        [ClubTeam],
        [IDL.Variant({ 'Ok' : ClubTeam, 'Err' : IDL.Text })],
        [],
      ),
    'save_team_folder' : IDL.Func(
        [TeamFolder],
        [IDL.Variant({ 'Ok' : TeamFolder, 'Err' : IDL.Text })],
        [],
      ),
    'save_team_pitch_settings' : IDL.Func(
        [
          IDL.Text,
          IDL.Bool,
          IDL.Nat32,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Nat32),
          IDL.Opt(IDL.Nat32),
          IDL.Opt(IDL.Nat32),
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Bool,
        ],
        [IDL.Variant({ 'Ok' : TeamSubscription, 'Err' : IDL.Text })],
        [],
      ),
    'save_team_subscription' : IDL.Func(
        [TeamSubscription],
        [IDL.Variant({ 'Ok' : TeamSubscription, 'Err' : IDL.Text })],
        [],
      ),
    'send_fee_reminders' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Nat16, 'Err' : IDL.Text })],
        [],
      ),
    'set_app_config' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'set_club_header_toggles' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool],
        [IDL.Variant({ 'Ok' : ClubSettings, 'Err' : IDL.Text })],
        [],
      ),
    'set_club_invite_email_style' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : ClubSettings, 'Err' : IDL.Text })],
        [],
      ),
    'set_club_logo_only_mode' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'Ok' : ClubSettings, 'Err' : IDL.Text })],
        [],
      ),
    'set_club_switcher_hint' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : ClubSettings, 'Err' : IDL.Text })],
        [],
      ),
    'set_club_term_status' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : ClubTerm, 'Err' : IDL.Text })],
        [],
      ),
    'set_club_theme_enabled' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'Ok' : ClubSettings, 'Err' : IDL.Text })],
        [],
      ),
    'set_club_theme_palette' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'Ok' : ClubSettings, 'Err' : IDL.Text })],
        [],
      ),
    'set_events_domain_canister' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'set_messaging_domain_canister' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'set_notification_queue_canister' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'set_pii_canister' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'set_team_folder' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'Ok' : ClubTeam, 'Err' : IDL.Text })],
        [],
      ),
    'set_team_player_position' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'set_team_sponsor_allocation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'set_theme_preference' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'soft_delete_club' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'Ok' : ClubProfile, 'Err' : IDL.Text })],
        [],
      ),
    'soft_delete_team' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ClubTeam, 'Err' : IDL.Text })],
        [],
      ),
    'transfer_governorship' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'unarchive_team' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : ClubTeam, 'Err' : IDL.Text })],
        [],
      ),
    'unfreeze_club' : IDL.Func(
        [IDL.Text, IDL.Nat64],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'unlink_guardian' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'unmark_member_paid' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text })],
        [],
      ),
    'update_news_post' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Vec(NewsAttachment),
          IDL.Nat64,
        ],
        [IDL.Variant({ 'Ok' : NewsPost, 'Err' : IDL.Text })],
        [],
      ),
    'whoami' : IDL.Func(
        [],
        [IDL.Variant({ 'Ok' : Account, 'Err' : IDL.Text })],
        ['query'],
      ),
  });
  
  return Main;
};

export const init = ({ IDL }) => { return [IDL.Principal]; };